[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: start_1_node
[32mINFO    [0m src.node.status_node:status_node.py:39 Starting node with command: ['./status-cli', 'serve', '-n', 'first_node', '-p', '16512']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025-01-20T00:25:32.731Z	INFO	status-cli/serve.go:34	Running serve command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -name first_node
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -port 16512
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -light false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -api-modules waku,wakuext,wakuv2,permissions,eth
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -telemetry-server-url
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -fleet status.staging
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025-01-20T00:25:32.731Z	INFO	first_node	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [01-20|00:25:34.929] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [01-20|00:25:34.935] New local node record                    seq=1,737,332,734,933 id=0373916140f7f2c8 ip=127.0.0.1 udp=0 tcp=38597
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [01-20|00:25:34.935] Started P2P networking                   self="enode://f1277f7cde5fd705191cd1243f54f9160237a7d6b79972c1e209a69f34cccd8d80515478d629440e317999e49523421af12e487c9d7721a2a595bafcb169ac55@127.0.0.1:38597?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - ERROR[01-20|00:25:34.935] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [01-20|00:25:34.936] HTTP server started                      endpoint=127.0.0.1:16512 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [01-20|00:25:34.955] New local node record                    seq=1,737,332,734,939 id=1a4ac5c76715902f ip=10.1.0.18 udp=0 tcp=35111
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [01-20|00:25:34.957] New local node record                    seq=1,737,332,734,940 id=1a4ac5c76715902f ip=10.1.0.18 udp=59129 tcp=35111
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [01-20|00:25:34.962] New local node record                    seq=1,737,332,734,941 id=1a4ac5c76715902f ip=10.1.0.18 udp=59129 tcp=35111
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025-01-20T00:25:35.396Z	INFO	first_node	status-cli/util.go:68	account created, key UID: 0x107e70dd44dbfadef2a90be8f4d91b63fd120a55d64bb63746ccb04e6e819103
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [01-20|00:25:35.396] New local node record                    seq=1,737,332,734,942 id=1a4ac5c76715902f ip=10.1.0.18 udp=59129 tcp=35111
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025-01-20T00:25:35.424Z	INFO	first_node	status-cli/util.go:93	messenger started, public key: 0x0434b469ebafa1c414a8058a66832be6e131a507605b4212a56b6eef8c40ccb775cbdf2973ded3bfaf5d831eff22a8b6340d62ba801bb4a0a448c3e6e5a66e0c0f
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025-01-20T00:25:40.425Z	INFO	first_node	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x0262a45b93d6b04e177d73fae7f95f9289c880bcf7e824933ce2e055238012e98b_6131', '-kid', '0x318e25b042b429ec764e0258b3e34525b6d0ffaa13d6dd0a68ba3d5cc8c11392']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - 2025-01-20T00:25:40.728Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - -name 0x0262a45b93d6b04e177d73fae7f95f9289c880bcf7e824933ce2e055238012e98b_6131
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - -key-uid 0x318e25b042b429ec764e0258b3e34525b6d0ffaa13d6dd0a68ba3d5cc8c11392
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - 2025-01-20T00:25:40.728Z	INFO	0x0262a45b93d6b04e177d73fae7f95f9289c880bcf7e824933ce2e055238012e98b_6131	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - INFO [01-20|00:25:40.760] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - INFO [01-20|00:25:40.765] New local node record                    seq=1,736,315,414,675 id=461975f0c72cbc16 ip=127.0.0.1 udp=0 tcp=36199
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - INFO [01-20|00:25:40.765] Started P2P networking                   self="enode://ee83895eaae78bb7bbfc7067bf8e53d77602b13bbebd4576aa44541a3718d2ca08edc5fb2534cbdc4414bcb93361ac271101867188c94b5fe79ad4610bab2c05@127.0.0.1:36199?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - ERROR[01-20|00:25:40.767] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - INFO [01-20|00:25:40.768] HTTP server started                      endpoint=127.0.0.1:6131 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - INFO [01-20|00:25:40.787] New local node record                    seq=1,737,332,740,771 id=3e8a9184ea9c36bb ip=10.1.0.18 udp=0 tcp=40549
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - INFO [01-20|00:25:40.789] New local node record                    seq=1,737,332,740,772 id=3e8a9184ea9c36bb ip=10.1.0.18 udp=44064 tcp=40549
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - INFO [01-20|00:25:40.794] New local node record                    seq=1,737,332,740,773 id=3e8a9184ea9c36bb ip=10.1.0.18 udp=44064 tcp=40549
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - 2025-01-20T00:25:40.925Z	INFO	0x0262a45b93d6b04e177d73fae7f95f9289c880bcf7e824933ce2e055238012e98b_6131	status-cli/util.go:62	existing account, key UID: 0x318e25b042b429ec764e0258b3e34525b6d0ffaa13d6dd0a68ba3d5cc8c11392
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - INFO [01-20|00:25:40.926] New local node record                    seq=1,737,332,740,774 id=3e8a9184ea9c36bb ip=10.1.0.18 udp=44064 tcp=40549
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - 2025-01-20T00:25:40.945Z	INFO	0x0262a45b93d6b04e177d73fae7f95f9289c880bcf7e824933ce2e055238012e98b_6131	status-cli/util.go:93	messenger started, public key: 0x042bcad344d9b1497d7beb6a43e75d89a7890adc0f0ff382548681514ecbb2bf95e8b79fc2fe20d8ce84f1b0ba6be71ae16eb8f1c467fab7bacd08343d8dd1d44a
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x027c4daf49abb525306fe58eca0d83a292640f55b074bf273121d3cf36045609ce_6138', '-kid', '0x601f5d3cdb4e5b88c3ff16f048ae40007d6286156316ca1c672630689bf9921a']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - 2025-01-20T00:25:42.733Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - -name 0x027c4daf49abb525306fe58eca0d83a292640f55b074bf273121d3cf36045609ce_6138
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - -key-uid 0x601f5d3cdb4e5b88c3ff16f048ae40007d6286156316ca1c672630689bf9921a
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - 2025-01-20T00:25:42.733Z	INFO	0x027c4daf49abb525306fe58eca0d83a292640f55b074bf273121d3cf36045609ce_6138	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - INFO [01-20|00:25:42.765] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - INFO [01-20|00:25:42.770] New local node record                    seq=1,736,315,478,560 id=f7f3920bc8a72e6b ip=127.0.0.1 udp=0 tcp=34605
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - INFO [01-20|00:25:42.770] Started P2P networking                   self="enode://3ac5ea424c2432f8abea83f2bda40eb6a9d547a3a13689037567b082b6294f69992e815498c4bf31b64552d0966076c88f979f25f2d9229dab39676753262ac8@127.0.0.1:34605?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - ERROR[01-20|00:25:42.772] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - INFO [01-20|00:25:42.773] HTTP server started                      endpoint=127.0.0.1:6138 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - INFO [01-20|00:25:42.799] New local node record                    seq=1,737,332,742,782 id=add408c9f73b361c ip=10.1.0.18 udp=0 tcp=42889
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - INFO [01-20|00:25:42.801] New local node record                    seq=1,737,332,742,783 id=add408c9f73b361c ip=10.1.0.18 udp=39051 tcp=42889
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - INFO [01-20|00:25:42.804] New local node record                    seq=1,737,332,742,784 id=add408c9f73b361c ip=10.1.0.18 udp=39051 tcp=42889
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - 2025-01-20T00:25:42.940Z	INFO	0x027c4daf49abb525306fe58eca0d83a292640f55b074bf273121d3cf36045609ce_6138	status-cli/util.go:62	existing account, key UID: 0x601f5d3cdb4e5b88c3ff16f048ae40007d6286156316ca1c672630689bf9921a
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - INFO [01-20|00:25:42.941] New local node record                    seq=1,737,332,742,785 id=add408c9f73b361c ip=10.1.0.18 udp=39051 tcp=42889
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - 2025-01-20T00:25:42.965Z	INFO	0x027c4daf49abb525306fe58eca0d83a292640f55b074bf273121d3cf36045609ce_6138	status-cli/util.go:93	messenger started, public key: 0x04b1b3dd79a7c6ddc51eb5cd008812c32509ffacc3283a2c94c4183287c34e936181bb9da951efe7ca39b3d8e54beaab1bd0d82faed7de3557ee07a3d0fbaa9080
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x0367a8c7dc84fbe094059c2f552078f4daaca83048fa839d29e9e4195e1b16457f_6132', '-kid', '0x76b265c33f51e1e29b14c7a9e3e1043c624d5f9628abc7a37bb32326168a9a29']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - 2025-01-20T00:25:44.734Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - -name 0x0367a8c7dc84fbe094059c2f552078f4daaca83048fa839d29e9e4195e1b16457f_6132
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - -key-uid 0x76b265c33f51e1e29b14c7a9e3e1043c624d5f9628abc7a37bb32326168a9a29
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - 2025-01-20T00:25:44.734Z	INFO	0x0367a8c7dc84fbe094059c2f552078f4daaca83048fa839d29e9e4195e1b16457f_6132	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - INFO [01-20|00:25:44.767] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - ERROR[01-20|00:25:44.772] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - INFO [01-20|00:25:44.773] New local node record                    seq=1,736,315,423,817 id=232f620b5bea021f ip=127.0.0.1 udp=0 tcp=34331
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - INFO [01-20|00:25:44.773] Started P2P networking                   self="enode://b3542774027c24d996420dff85eb139ae23bdcde18d453dbc3c73ffaf416adf50129aa503379fb51c568c61438d87b7857765de2b8b849dc0fc3db3f6457a335@127.0.0.1:34331?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - INFO [01-20|00:25:44.773] HTTP server started                      endpoint=127.0.0.1:6132 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - INFO [01-20|00:25:44.798] New local node record                    seq=1,737,332,744,780 id=9545cc2d70aa3e80 ip=10.1.0.18 udp=0 tcp=35653
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - INFO [01-20|00:25:44.799] New local node record                    seq=1,737,332,744,781 id=9545cc2d70aa3e80 ip=10.1.0.18 udp=35433 tcp=35653
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - INFO [01-20|00:25:44.802] New local node record                    seq=1,737,332,744,782 id=9545cc2d70aa3e80 ip=10.1.0.18 udp=35433 tcp=35653
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - 2025-01-20T00:25:44.941Z	INFO	0x0367a8c7dc84fbe094059c2f552078f4daaca83048fa839d29e9e4195e1b16457f_6132	status-cli/util.go:62	existing account, key UID: 0x76b265c33f51e1e29b14c7a9e3e1043c624d5f9628abc7a37bb32326168a9a29
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - INFO [01-20|00:25:44.943] New local node record                    seq=1,737,332,744,783 id=9545cc2d70aa3e80 ip=10.1.0.18 udp=35433 tcp=35653
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - 2025-01-20T00:25:44.962Z	INFO	0x0367a8c7dc84fbe094059c2f552078f4daaca83048fa839d29e9e4195e1b16457f_6132	status-cli/util.go:93	messenger started, public key: 0x047c462afdfee45ebea4494ac9913d2a615a015c5e5869443959f9e234c3a6ce77857e2878f7c4929ba6a9ba05bcfced693b6482a305f1a5e1ffd6d3a16bd343e5
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - INFO [01-20|00:25:45.784] New local node record                    seq=1,737,332,740,775 id=3e8a9184ea9c36bb ip=20.246.77.167 udp=44064 tcp=16384
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - 2025-01-20T00:25:45.945Z	INFO	0x0262a45b93d6b04e177d73fae7f95f9289c880bcf7e824933ce2e055238012e98b_6131	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x02ca408a7d4eff12329f0370dd24e7738863d4649728898f520a4bd163d4b55f08_6135', '-kid', '0x708a30bfc69bdd791e0554d9713b660435d7a8e345d566251689005c3c87ac19']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - 2025-01-20T00:25:46.744Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - -name 0x02ca408a7d4eff12329f0370dd24e7738863d4649728898f520a4bd163d4b55f08_6135
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - -key-uid 0x708a30bfc69bdd791e0554d9713b660435d7a8e345d566251689005c3c87ac19
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - 2025-01-20T00:25:46.744Z	INFO	0x02ca408a7d4eff12329f0370dd24e7738863d4649728898f520a4bd163d4b55f08_6135	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - INFO [01-20|00:25:46.776] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - INFO [01-20|00:25:46.781] New local node record                    seq=1,736,315,451,186 id=c4a6f603a5f298f7 ip=127.0.0.1 udp=0 tcp=37391
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - ERROR[01-20|00:25:46.781] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - INFO [01-20|00:25:46.782] Started P2P networking                   self="enode://c9b636283622d5569b588181599af7fa3c6e235be801e8fd89379129098d75b2af07b24ea20b223ab0a7ba6168a6442477bace4a227044e32d212495bed19cda@127.0.0.1:37391?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - INFO [01-20|00:25:46.782] HTTP server started                      endpoint=127.0.0.1:6135 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - INFO [01-20|00:25:46.814] New local node record                    seq=1,737,332,746,792 id=a2e8a0203fa0a653 ip=10.1.0.18 udp=0 tcp=35115
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - INFO [01-20|00:25:46.815] New local node record                    seq=1,737,332,746,793 id=a2e8a0203fa0a653 ip=10.1.0.18 udp=48984 tcp=35115
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - INFO [01-20|00:25:46.817] New local node record                    seq=1,737,332,746,794 id=a2e8a0203fa0a653 ip=10.1.0.18 udp=48984 tcp=35115
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - 2025-01-20T00:25:46.952Z	INFO	0x02ca408a7d4eff12329f0370dd24e7738863d4649728898f520a4bd163d4b55f08_6135	status-cli/util.go:62	existing account, key UID: 0x708a30bfc69bdd791e0554d9713b660435d7a8e345d566251689005c3c87ac19
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - INFO [01-20|00:25:46.953] New local node record                    seq=1,737,332,746,795 id=a2e8a0203fa0a653 ip=10.1.0.18 udp=48984 tcp=35115
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - 2025-01-20T00:25:46.974Z	INFO	0x02ca408a7d4eff12329f0370dd24e7738863d4649728898f520a4bd163d4b55f08_6135	status-cli/util.go:93	messenger started, public key: 0x048056281da125dfc429df85b69fcf13286a346faae25073a1dc0955d86f91661764d928b6ee59e0ae150a977d497c79fe069266e80890a3b106d4ec6ca8b3bc14
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - INFO [01-20|00:25:47.795] New local node record                    seq=1,737,332,742,786 id=add408c9f73b361c ip=20.246.77.167 udp=39051 tcp=16385
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - 2025-01-20T00:25:47.965Z	INFO	0x027c4daf49abb525306fe58eca0d83a292640f55b074bf273121d3cf36045609ce_6138	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x0256150046af3c90e47d162c844a4d3e4c98be2ca6a4fe3e8d63b996b1afd6dd02_6136', '-kid', '0x924a030ee7140e04e1f74fef2d6293d230a53f7a73f77c29ad6df870b0c26f58']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - 2025-01-20T00:25:48.738Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - -name 0x0256150046af3c90e47d162c844a4d3e4c98be2ca6a4fe3e8d63b996b1afd6dd02_6136
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - -key-uid 0x924a030ee7140e04e1f74fef2d6293d230a53f7a73f77c29ad6df870b0c26f58
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - 2025-01-20T00:25:48.738Z	INFO	0x0256150046af3c90e47d162c844a4d3e4c98be2ca6a4fe3e8d63b996b1afd6dd02_6136	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - INFO [01-20|00:25:48.770] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - ERROR[01-20|00:25:48.776] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - INFO [01-20|00:25:48.776] New local node record                    seq=1,736,315,460,313 id=0f414d769065d7f6 ip=127.0.0.1 udp=0 tcp=40745
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - INFO [01-20|00:25:48.776] Started P2P networking                   self="enode://85e0d6a952fbc7dd1220f73edbc39659c964d8be3a2a4d8f951f1bb019758fa87a78eb700fe780127b6d0e15ec2a9b723d1f8fb8441c74f48eb19871dd884220@127.0.0.1:40745?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - INFO [01-20|00:25:48.778] HTTP server started                      endpoint=127.0.0.1:6136 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - INFO [01-20|00:25:48.799] New local node record                    seq=1,737,332,748,782 id=2059434cab32d513 ip=10.1.0.18 udp=0 tcp=37873
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - INFO [01-20|00:25:48.800] New local node record                    seq=1,737,332,748,783 id=2059434cab32d513 ip=10.1.0.18 udp=51276 tcp=37873
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - INFO [01-20|00:25:48.802] New local node record                    seq=1,737,332,748,784 id=2059434cab32d513 ip=10.1.0.18 udp=51276 tcp=37873
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - 2025-01-20T00:25:48.943Z	INFO	0x0256150046af3c90e47d162c844a4d3e4c98be2ca6a4fe3e8d63b996b1afd6dd02_6136	status-cli/util.go:62	existing account, key UID: 0x924a030ee7140e04e1f74fef2d6293d230a53f7a73f77c29ad6df870b0c26f58
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - INFO [01-20|00:25:48.944] New local node record                    seq=1,737,332,748,785 id=2059434cab32d513 ip=10.1.0.18 udp=51276 tcp=37873
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - 2025-01-20T00:25:48.971Z	INFO	0x0256150046af3c90e47d162c844a4d3e4c98be2ca6a4fe3e8d63b996b1afd6dd02_6136	status-cli/util.go:93	messenger started, public key: 0x045c64ff62014879abe06ac69aedd119afe6a0dd7b37a813d8ed09cb36b04be0e2d4e6dfaff4a272676b5f9e2441638d1c9dbb6aa7eee0f81ea865628018bdab45
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - INFO [01-20|00:25:49.795] New local node record                    seq=1,737,332,744,784 id=9545cc2d70aa3e80 ip=20.246.77.167 udp=35433 tcp=16386
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - 2025-01-20T00:25:49.962Z	INFO	0x0367a8c7dc84fbe094059c2f552078f4daaca83048fa839d29e9e4195e1b16457f_6132	status-cli/serve.go:107	retrieve messages...
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - WARN [01-20|00:25:49.968] Served personal_ecRecover                reqid=1 duration="59.119µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - WARN [01-20|00:25:49.969] Served personal_ecRecover                reqid=2 duration="23.224µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - WARN [01-20|00:25:49.971] Served personal_ecRecover                reqid=3 duration="25.798µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - WARN [01-20|00:25:49.974] Served personal_ecRecover                reqid=4 duration="30.747µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - WARN [01-20|00:25:49.976] Served personal_ecRecover                reqid=5 duration="27.171µs" err="signature must be 65 bytes long"
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x03d6bf5f2f19521f6149adef0adf597655810e21edb2a1c885bb1519e8ea7708fd_6134', '-kid', '0x5d0a17a7274481d620bacfcb493efc223184541a71176880cd945de1a20e55e4']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - 2025-01-20T00:25:50.738Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - -name 0x03d6bf5f2f19521f6149adef0adf597655810e21edb2a1c885bb1519e8ea7708fd_6134
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - -key-uid 0x5d0a17a7274481d620bacfcb493efc223184541a71176880cd945de1a20e55e4
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - 2025-01-20T00:25:50.738Z	INFO	0x03d6bf5f2f19521f6149adef0adf597655810e21edb2a1c885bb1519e8ea7708fd_6134	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - INFO [01-20|00:25:50.772] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - INFO [01-20|00:25:50.777] New local node record                    seq=1,736,315,442,058 id=b01a6054d8c74f08 ip=127.0.0.1 udp=0 tcp=46235
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - INFO [01-20|00:25:50.777] Started P2P networking                   self="enode://7033cd3427730b644b017c2de11010f24f9acdc444028e0e10a4cde4a83415096594264e4e7148521a04e3cca5ba9c7ea697361a60be9cd991d30d21cb58896f@127.0.0.1:46235?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - ERROR[01-20|00:25:50.779] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - INFO [01-20|00:25:50.779] HTTP server started                      endpoint=127.0.0.1:6134 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - INFO [01-20|00:25:50.808] New local node record                    seq=1,737,332,750,782 id=9e9cf4887046dfe4 ip=10.1.0.18 udp=0 tcp=35467
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - INFO [01-20|00:25:50.810] New local node record                    seq=1,737,332,750,783 id=9e9cf4887046dfe4 ip=10.1.0.18 udp=48806 tcp=35467
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - INFO [01-20|00:25:50.811] New local node record                    seq=1,737,332,750,784 id=9e9cf4887046dfe4 ip=10.1.0.18 udp=48806 tcp=35467
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - 2025-01-20T00:25:50.952Z	INFO	0x03d6bf5f2f19521f6149adef0adf597655810e21edb2a1c885bb1519e8ea7708fd_6134	status-cli/util.go:62	existing account, key UID: 0x5d0a17a7274481d620bacfcb493efc223184541a71176880cd945de1a20e55e4
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - INFO [01-20|00:25:50.953] New local node record                    seq=1,737,332,750,785 id=9e9cf4887046dfe4 ip=10.1.0.18 udp=48806 tcp=35467
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - 2025-01-20T00:25:50.979Z	INFO	0x03d6bf5f2f19521f6149adef0adf597655810e21edb2a1c885bb1519e8ea7708fd_6134	status-cli/util.go:93	messenger started, public key: 0x048e51e7f5ef88ba97ed543053d8cea3fe3a8b4f10242680a4ab05a26bc78e4d665312b3145003835d5376c79f5da46cd5c7bc3a3472ca25e52a6ae5f96cf08189
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - INFO [01-20|00:25:51.810] New local node record                    seq=1,737,332,746,796 id=a2e8a0203fa0a653 ip=20.246.77.167 udp=48984 tcp=16389
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - 2025-01-20T00:25:51.977Z	INFO	0x02ca408a7d4eff12329f0370dd24e7738863d4649728898f520a4bd163d4b55f08_6135	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x027e44751004d002d708ccd30f2847da5333a92627516e540d643605c60579adb0_6137', '-kid', '0x798f0322faaab75637cc33ad2713eec5e6cae3c334b3132f326831c529ff1f1b']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - 2025-01-20T00:25:52.737Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - -name 0x027e44751004d002d708ccd30f2847da5333a92627516e540d643605c60579adb0_6137
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - -key-uid 0x798f0322faaab75637cc33ad2713eec5e6cae3c334b3132f326831c529ff1f1b
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - 2025-01-20T00:25:52.737Z	INFO	0x027e44751004d002d708ccd30f2847da5333a92627516e540d643605c60579adb0_6137	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - INFO [01-20|00:25:52.770] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - INFO [01-20|00:25:52.776] New local node record                    seq=1,736,315,469,431 id=a03b19848aa8ae71 ip=127.0.0.1 udp=0 tcp=44589
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - INFO [01-20|00:25:52.776] Started P2P networking                   self="enode://47ec99314e9bd4433887524e8d1bb5cef991529c6327fd581e7092f7718939d40d4faa42e4196d56827662015e63c194bdfab39c442a8c5991d53d86f96e7944@127.0.0.1:44589?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - ERROR[01-20|00:25:52.776] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - INFO [01-20|00:25:52.777] HTTP server started                      endpoint=127.0.0.1:6137 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - INFO [01-20|00:25:52.795] New local node record                    seq=1,737,332,742,787 id=add408c9f73b361c ip=20.246.77.167 udp=39051 tcp=16385
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - INFO [01-20|00:25:52.803] New local node record                    seq=1,737,332,752,782 id=268b8942c4c3c8c8 ip=10.1.0.18 udp=0 tcp=36771
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - INFO [01-20|00:25:52.804] New local node record                    seq=1,737,332,752,783 id=268b8942c4c3c8c8 ip=10.1.0.18 udp=36103 tcp=36771
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - INFO [01-20|00:25:52.808] New local node record                    seq=1,737,332,752,784 id=268b8942c4c3c8c8 ip=10.1.0.18 udp=36103 tcp=36771
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - 2025-01-20T00:25:52.945Z	INFO	0x027e44751004d002d708ccd30f2847da5333a92627516e540d643605c60579adb0_6137	status-cli/util.go:62	existing account, key UID: 0x798f0322faaab75637cc33ad2713eec5e6cae3c334b3132f326831c529ff1f1b
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - INFO [01-20|00:25:52.945] New local node record                    seq=1,737,332,752,785 id=268b8942c4c3c8c8 ip=10.1.0.18 udp=36103 tcp=36771
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - 2025-01-20T00:25:52.970Z	INFO	0x027e44751004d002d708ccd30f2847da5333a92627516e540d643605c60579adb0_6137	status-cli/util.go:93	messenger started, public key: 0x040476b36b9b1e21e10d1f4692b77831000daab6e950e3f7945a72b143866d3fcb36546535a7ca0690cac29d228922ed111e5b3ec93c3da2db664bcc5c6c517536
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - INFO [01-20|00:25:53.795] New local node record                    seq=1,737,332,748,786 id=2059434cab32d513 ip=20.246.77.167 udp=51276 tcp=16389
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - 2025-01-20T00:25:53.972Z	INFO	0x0256150046af3c90e47d162c844a4d3e4c98be2ca6a4fe3e8d63b996b1afd6dd02_6136	status-cli/serve.go:107	retrieve messages...
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - WARN [01-20|00:25:53.979] Served personal_ecRecover                reqid=1 duration="59.21µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - WARN [01-20|00:25:53.981] Served personal_ecRecover                reqid=2 duration="24.526µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - WARN [01-20|00:25:53.983] Served personal_ecRecover                reqid=3 duration="22.121µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - WARN [01-20|00:25:53.985] Served personal_ecRecover                reqid=4 duration="21.299µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0367A8C7DC84FBE094059C2F552078F4DAACA83048FA839D29E9E4195E1B16457F_6132 - WARN [01-20|00:25:53.987] Served personal_ecRecover                reqid=5 duration="18.224µs" err="signature must be 65 bytes long"
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x0380a412be83772589a7ad5b47fc338483149386996f5ecd8f24e8b8ab5692ffe1_6133', '-kid', '0xc6b69f738454549ebe9b59807d3b3503c2851546856bae718220827d11c9b27e']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - 2025-01-20T00:25:54.742Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - -name 0x0380a412be83772589a7ad5b47fc338483149386996f5ecd8f24e8b8ab5692ffe1_6133
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - -key-uid 0xc6b69f738454549ebe9b59807d3b3503c2851546856bae718220827d11c9b27e
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - 2025-01-20T00:25:54.742Z	INFO	0x0380a412be83772589a7ad5b47fc338483149386996f5ecd8f24e8b8ab5692ffe1_6133	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - INFO [01-20|00:25:54.776] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - INFO [01-20|00:25:54.783] New local node record                    seq=1,736,315,432,934 id=05ef2615206d52de ip=127.0.0.1 udp=0 tcp=40825
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - INFO [01-20|00:25:54.783] Started P2P networking                   self="enode://ee17158108f7505794695af5548af97aa71823dc2595397bb6227242f669702d3502511f3c79a42b83171d53ff66ad61a9311848d7c91a0f09bc9bcab95f676e@127.0.0.1:40825?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - ERROR[01-20|00:25:54.783] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - INFO [01-20|00:25:54.784] HTTP server started                      endpoint=127.0.0.1:6133 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - INFO [01-20|00:25:54.809] New local node record                    seq=1,737,332,754,788 id=c4eeb1e18907f13e ip=10.1.0.18 udp=0 tcp=37631
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - INFO [01-20|00:25:54.811] New local node record                    seq=1,737,332,754,789 id=c4eeb1e18907f13e ip=10.1.0.18 udp=55024 tcp=37631
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - INFO [01-20|00:25:54.813] New local node record                    seq=1,737,332,754,790 id=c4eeb1e18907f13e ip=10.1.0.18 udp=55024 tcp=37631
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - WARN [01-20|00:25:54.960] Served personal_ecRecover                reqid=1 duration="76.482µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - 2025-01-20T00:25:54.961Z	INFO	0x0380a412be83772589a7ad5b47fc338483149386996f5ecd8f24e8b8ab5692ffe1_6133	status-cli/util.go:62	existing account, key UID: 0xc6b69f738454549ebe9b59807d3b3503c2851546856bae718220827d11c9b27e
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - INFO [01-20|00:25:54.962] New local node record                    seq=1,737,332,754,791 id=c4eeb1e18907f13e ip=10.1.0.18 udp=55024 tcp=37631
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - WARN [01-20|00:25:54.963] Served personal_ecRecover                reqid=2 duration="26.95µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - WARN [01-20|00:25:54.966] Served personal_ecRecover                reqid=3 duration="55.914µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - WARN [01-20|00:25:54.969] Served personal_ecRecover                reqid=4 duration="20.608µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - WARN [01-20|00:25:54.970] Served personal_ecRecover                reqid=5 duration="22.812µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - 2025-01-20T00:25:54.984Z	INFO	0x0380a412be83772589a7ad5b47fc338483149386996f5ecd8f24e8b8ab5692ffe1_6133	status-cli/util.go:93	messenger started, public key: 0x049e70b35da90477771dc072daad7f5d2a9e9c47242ee1fa00b8291ed90cc899e88f919e77d838966aa59c0f7c935c18519c019c990077c309ca7c9d24a8b3c401
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0262A45B93D6B04E177D73FAE7F95F9289C880BCF7E824933CE2E055238012E98B_6131 - INFO [01-20|00:25:55.784] New local node record                    seq=1,737,332,740,776 id=3e8a9184ea9c36bb ip=20.246.77.167 udp=44064 tcp=16384
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - INFO [01-20|00:25:55.802] New local node record                    seq=1,737,332,750,786 id=9e9cf4887046dfe4 ip=20.246.77.167 udp=48806 tcp=16390
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - WARN [01-20|00:25:55.976] Served personal_ecRecover                reqid=1 duration="60.272µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - WARN [01-20|00:25:55.977] Served personal_ecRecover                reqid=2 duration="28.423µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - WARN [01-20|00:25:55.979] Served personal_ecRecover                reqid=3 duration="23.844µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - 2025-01-20T00:25:55.980Z	INFO	0x03d6bf5f2f19521f6149adef0adf597655810e21edb2a1c885bb1519e8ea7708fd_6134	status-cli/serve.go:107	retrieve messages...
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - WARN [01-20|00:25:55.981] Served personal_ecRecover                reqid=4 duration="32.811µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - WARN [01-20|00:25:55.982] Served personal_ecRecover                reqid=5 duration="26.94µs" err="signature must be 65 bytes long"
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139', '-kid', '0x74fe52cbce9a0f5b5f54a3a7de81c5e1d33d442b688c78cb0d9103e3737199e2']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:25:56.746Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - -name 0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - -key-uid 0x74fe52cbce9a0f5b5f54a3a7de81c5e1d33d442b688c78cb0d9103e3737199e2
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:25:56.746Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - INFO [01-20|00:25:56.781] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - INFO [01-20|00:25:56.787] New local node record                    seq=1,736,315,487,685 id=6a9c74352e0bbe70 ip=127.0.0.1 udp=0 tcp=41369
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - INFO [01-20|00:25:56.787] Started P2P networking                   self="enode://9cc4d3c1df1a690a18d32400d61656479914198d14fc843cca7825d5afabc2b51698872e9f1224d153e63dce363fff5f99e0552968c8294ae01fe35c6f0af3c0@127.0.0.1:41369?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - ERROR[01-20|00:25:56.787] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - INFO [01-20|00:25:56.788] HTTP server started                      endpoint=127.0.0.1:6139 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - INFO [01-20|00:25:56.813] New local node record                    seq=1,737,332,756,793 id=6dd1c7ca78d01dc7 ip=10.1.0.18 udp=0 tcp=43989
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - INFO [01-20|00:25:56.814] New local node record                    seq=1,737,332,756,794 id=6dd1c7ca78d01dc7 ip=10.1.0.18 udp=48937 tcp=43989
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - INFO [01-20|00:25:56.818] New local node record                    seq=1,737,332,756,795 id=6dd1c7ca78d01dc7 ip=10.1.0.18 udp=48937 tcp=43989
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:25:56.972Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/util.go:62	existing account, key UID: 0x74fe52cbce9a0f5b5f54a3a7de81c5e1d33d442b688c78cb0d9103e3737199e2
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - INFO [01-20|00:25:56.973] New local node record                    seq=1,737,332,756,796 id=6dd1c7ca78d01dc7 ip=10.1.0.18 udp=48937 tcp=43989
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:25:57.002Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/util.go:93	messenger started, public key: 0x047d0a4d5c33b400598215eccc7ec9425c3f1f7a06cc2a7bd6aa9620b68a12b42fc1a6ff5a90de2e932c8bf1dbb3da4f19b5c434c2cd090a6855803b01cb914892
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - INFO [01-20|00:25:57.798] New local node record                    seq=1,737,332,752,786 id=268b8942c4c3c8c8 ip=20.246.77.167 udp=36103 tcp=16388
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - 2025-01-20T00:25:57.970Z	INFO	0x027e44751004d002d708ccd30f2847da5333a92627516e540d643605c60579adb0_6137	status-cli/serve.go:107	retrieve messages...
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 4 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0256150046AF3C90E47D162C844A4D3E4C98BE2CA6A4FE3E8D63B996B1AFD6DD02_6136 - INFO [01-20|00:25:58.795] New local node record                    seq=1,737,332,748,787 id=2059434cab32d513 ip=20.246.77.167 udp=51276 tcp=16389
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - INFO [01-20|00:25:59.805] New local node record                    seq=1,737,332,754,792 id=c4eeb1e18907f13e ip=20.246.77.167 udp=55024 tcp=16392
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - 2025-01-20T00:25:59.985Z	INFO	0x0380a412be83772589a7ad5b47fc338483149386996f5ecd8f24e8b8ab5692ffe1_6133	status-cli/serve.go:107	retrieve messages...
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - WARN [01-20|00:26:00.981] Served personal_ecRecover                reqid=1 duration="61.804µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - WARN [01-20|00:26:00.983] Served personal_ecRecover                reqid=2 duration="27.722µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - WARN [01-20|00:26:00.985] Served personal_ecRecover                reqid=3 duration="30.677µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - WARN [01-20|00:26:00.987] Served personal_ecRecover                reqid=4 duration="25.517µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CA408A7D4EFF12329F0370DD24E7738863D4649728898F520A4BD163D4B55F08_6135 - WARN [01-20|00:26:00.989] Served personal_ecRecover                reqid=5 duration="27.962µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - INFO [01-20|00:26:01.810] New local node record                    seq=1,737,332,756,797 id=6dd1c7ca78d01dc7 ip=20.246.77.167 udp=48937 tcp=16393
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - WARN [01-20|00:26:01.977] Served personal_ecRecover                reqid=1 duration="65.632µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - WARN [01-20|00:26:01.979] Served personal_ecRecover                reqid=2 duration="22.131µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - WARN [01-20|00:26:01.980] Served personal_ecRecover                reqid=3 duration="18.855µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027E44751004D002D708CCD30F2847DA5333A92627516E540D643605C60579ADB0_6137 - WARN [01-20|00:26:01.982] Served personal_ecRecover                reqid=4 duration="27.471µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - WARN [01-20|00:26:01.984] Served personal_ecRecover                reqid=1 duration="43.63µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - WARN [01-20|00:26:01.986] Served personal_ecRecover                reqid=2 duration="25.908µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - WARN [01-20|00:26:01.988] Served personal_ecRecover                reqid=3 duration="54.852µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - WARN [01-20|00:26:01.990] Served personal_ecRecover                reqid=4 duration="51.435µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - WARN [01-20|00:26:01.992] Served personal_ecRecover                reqid=5 duration="50.934µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.002Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:107	retrieve messages...
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - WARN [01-20|00:26:02.210] Served personal_ecRecover                reqid=1 duration="90.898µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - WARN [01-20|00:26:02.212] Served personal_ecRecover                reqid=2 duration="21.069µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - WARN [01-20|00:26:02.214] Served personal_ecRecover                reqid=3 duration="48.42µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - WARN [01-20|00:26:02.218] Served personal_ecRecover                reqid=4 duration=1.395515ms err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - WARN [01-20|00:26:02.221] Served personal_ecRecover                reqid=5 duration="22.271µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - WARN [01-20|00:26:02.222] Served personal_ecRecover                reqid=6 duration="20.257µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - WARN [01-20|00:26:02.224] Served personal_ecRecover                reqid=7 duration="23.263µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - WARN [01-20|00:26:02.226] Served personal_ecRecover                reqid=8 duration="20.678µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.251Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: 913ce274-acfc-4b43-9a5b-b01aba2480f7_message_from_0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139_18 (ID=0x6eea185df856eeb47afcaee9363c8c767e50ba73fbfb9133e7bc23fe87ce7924)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.251Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: bf9e5214-03a8-4865-a3a1-c81637c6e830_message_from_first_node_13 (ID=0x465d7b638f172fbb3ee5babac389e41621ceeca3a55a42682b95bedc0b6edb79)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.251Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: e4c89eb6-5692-44fa-ab03-b54f9dadbfb6_message_from_0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139_10 (ID=0x321bb8d371de56bea7c31c0218bbd8a7a7bb7e61f0ce9b3df1c12d7341c99ff2)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.251Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: 46c92d14-3a8d-42a9-b2b2-abeca0eb3943_message_from_0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139_24 (ID=0x632265d90a28548d597c0c541058b6f8777c0aff7bf73a7e656ac223f517ac70)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.251Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: dd0dfd20-cd4a-4eeb-801b-b1a7fe99947f_message_from_first_node_19 (ID=0xf9f84443fa0d44455bfce7221780c0b2d2e0c79223656c1321655f409ee7ce38)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.251Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: 1375b51f-0a5d-469d-a72e-0658b1cf8a5f_message_from_0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139_4 (ID=0x68246b48f881aa5f131d61efd0ef734d9fb6a0cf1f55d98d1d3f5cc6127099ea)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.251Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: b2f88e75-6009-46bd-a94b-0d3dba0199af_message_from_0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139_2 (ID=0x3aff77cc6225e302847b34a7b995df5645166e3f0ec45fb4aa5ff719e07544d4)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.252Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: 8b6bdf44-e517-4e14-bfed-bb044e3cf8e2_message_from_first_node_1 (ID=0xe964a3b30517bf112483bca6f7a37c2381084ae9e2ede31bb2686acd79902d6f)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.252Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: 4446c114-71af-4b9c-8ce7-590c003e2ceb_message_from_0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139_22 (ID=0x482f7c7a3443b047debd1d614bf9f8cfb67b7fadefb1ba9ea3229e2f3766ebbd)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.252Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: 4966abd9-79a1-439b-948b-6f9d3d13fd46_message_from_0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139_16 (ID=0x3ca35e126f737c1eda377c5d17d1d6f9c577d73eba2254a439a24e699221e916)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.252Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: 45053b95-e59f-4c12-9fa2-4d9291e82067_message_from_0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139_14 (ID=0x2a829b01a17d580d710dcdc967c9123d8e9f49b287b7700a2b9790a85edb96d2)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.252Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: a526ac8d-b189-44f9-8efb-b3bc4a321d17_message_from_first_node_11 (ID=0xea235bc5f691924b1dcbbdaa52b8f9b187c40af35cf9183e64561482dfb64fc7)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.252Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: ff44df73-ecf1-4be7-a1f0-8ae0ed0cf1c7_message_from_first_node_9 (ID=0xdefd62453d003d6e04eb97332735327c95b120f72ba870e198aa0ffa07b1899a)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.252Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: 0b218841-b159-4145-bcfc-e757893b5d34_message_from_0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139_8 (ID=0xfc162351ff14d04762ee03cca6f271684ba65b61c42461f6ed6b01fc1c0de595)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.252Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: 70acac48-eaf9-4e98-8d91-5193a1b8f0e2_message_from_0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139_0 (ID=0x6a450270cbfde0b758d62e2974cdd25b65176db21e47023ba902338b0394f2ca)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.252Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: cf1b105a-e13c-4ac3-b26b-d97833a1b73a_message_from_first_node_23 (ID=0xa75f57e72dc3679cb396ddcfd2f0b084df861dd241c3670a346fe39051d4989d)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.252Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: 2758248e-413b-407d-a754-ab537154e7a7_message_from_first_node_7 (ID=0xa0d546a2a23a9361d6be2edfc63ba28b3bf268071a486a4ddced2211539af8a5)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.252Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: 579afc06-12f7-4d57-9dcd-081f3cbd9e2b_message_from_0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139_6 (ID=0x1891c60b338bb0f50531b40949620dbf3e1e2bd5197326328955a7739790bc01)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.252Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: deb3dbd1-63ff-4c5b-93f8-716ff11613d4 (ID=0xc060aacae2f83290811ba1d1428618c87432e82a7684b6fa174257fc5397e1f6)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.252Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: 6b986fdc-e29b-4790-8e02-bcef43a99d9c (ID=0x99dc0df407021ef16aa6e328379cc037c4fba528bdb339d8b4fe71ed2b952cd8)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.252Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: 53e3d039-01e1-4606-8702-b623296296ba_message_from_0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139_20 (ID=0x08ef76a2bd44d38073e45ae62f97e4d2181c8a2ed409d40da6763735df43f46f)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.252Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: 5e511825-4749-4499-9716-74a12067b649_message_from_first_node_5 (ID=0xbc76cf98d7f8d3af63c709aa3f3962102fac0228f6f8ce3fa624ac2ecdf0cf14)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.252Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: a302ba59-841b-46b4-be56-253cf272bcbe_message_from_first_node_21 (ID=0xb239880ae6f7e8480d272c7eb6f9a5a7304d034f5e99f1fddb297fafb865b313)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.252Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: 7162bd53-c9f0-4ec3-93b3-bd58039368a6_message_from_first_node_17 (ID=0x1f7562ced002daa9dafd42f055a54ceea10b0d5bbddcbfd4c515326b6128e3e1)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.252Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: 542237fa-0ea7-4c5e-8fc1-90b5e11e7b7f_message_from_first_node_15 (ID=0xc6f4056f9e1b5fcb9175409ab6c612c2a28ab0763db542c0875bc7203cb76b9a)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.252Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: fa0737ae-4b2f-428b-9026-4b154ea64305_message_from_0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139_12 (ID=0xa45f7b3daa938cc7be84b8e42bd78ebe28e6973f9bb0feccaadba00cf7a26ae8)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022E34EA7105F4A5AD44CBC7094B2F7AD4FC29200F05FDC4E473F90F4CD41CA73C_6139 - 2025-01-20T00:26:02.252Z	INFO	0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139	status-cli/serve.go:70	message received: 0644df6a-8550-4a2c-9f05-41089d7324b0_message_from_first_node_3 (ID=0x165b916e63412e2fd61207f45e605aaec097472301faefba2afad8d752577162)
[35mDEBUG   [0m src.steps.common:common.py:49 Entering context manager: add_packet_loss
[35mDEBUG   [0m src.node.rpc_client:rpc_client.py:21 Node: first_node sends request at address: http://127.0.0.1:16512 with payload: {"jsonrpc": "2.0", "method": "wakuext_fetchCommunity", "params": [{"communityKey": "0x0262a45b93d6b04e177d73fae7f95f9289c880bcf7e824933ce2e055238012e98b", "waitForResponse": true, "tryDatabase": true}], "id": 1}
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - INFO [01-20|00:26:04.806] New local node record                    seq=1,737,332,754,793 id=c4eeb1e18907f13e ip=20.246.77.167 udp=55024 tcp=16391
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - WARN [01-20|00:26:04.990] Served personal_ecRecover                reqid=1 duration="91.299µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - WARN [01-20|00:26:04.992] Served personal_ecRecover                reqid=2 duration="25.187µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - WARN [01-20|00:26:04.993] Served personal_ecRecover                reqid=3 duration="24.536µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0380A412BE83772589A7AD5B47FC338483149386996F5ECD8F24E8B8AB5692FFE1_6133 - WARN [01-20|00:26:04.995] Served personal_ecRecover                reqid=4 duration="26.229µs" err="signature must be 65 bytes long"
[31m[1mERROR   [0m src.node.rpc_client:rpc_client.py:32 Request to http://127.0.0.1:16512 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node
[35mDEBUG   [0m src.node.rpc_client:rpc_client.py:21 Node: first_node sends request at address: http://127.0.0.1:16512 with payload: {"jsonrpc": "2.0", "method": "wakuext_fetchCommunity", "params": [{"communityKey": "0x0262a45b93d6b04e177d73fae7f95f9289c880bcf7e824933ce2e055238012e98b", "waitForResponse": true, "tryDatabase": true}], "id": 1}
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X027C4DAF49ABB525306FE58ECA0D83A292640F55B074BF273121D3CF36045609CE_6138 - INFO [01-20|00:26:17.796] New local node record                    seq=1,737,332,742,788 id=add408c9f73b361c ip=20.246.77.167 udp=39051 tcp=16385
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03D6BF5F2F19521F6149ADEF0ADF597655810E21EDB2A1C885BB1519E8EA7708FD_6134 - INFO [01-20|00:26:20.803] New local node record                    seq=1,737,332,750,787 id=9e9cf4887046dfe4 ip=20.246.77.167 udp=48806 tcp=16391
[31m[1mERROR   [0m src.node.rpc_client:rpc_client.py:32 Request to http://127.0.0.1:16512 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node
[35mDEBUG   [0m src.node.rpc_client:rpc_client.py:21 Node: first_node sends request at address: http://127.0.0.1:16512 with payload: {"jsonrpc": "2.0", "method": "wakuext_fetchCommunity", "params": [{"communityKey": "0x0262a45b93d6b04e177d73fae7f95f9289c880bcf7e824933ce2e055238012e98b", "waitForResponse": true, "tryDatabase": true}], "id": 1}
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [01-20|00:26:32.665] New local node record                    seq=1,737,332,734,943 id=1a4ac5c76715902f ip=20.246.77.167 udp=16404 tcp=35111
[31m[1mERROR   [0m src.node.rpc_client:rpc_client.py:32 Request to http://127.0.0.1:16512 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node
[35mDEBUG   [0m src.steps.common:common.py:54 Exiting context manager: add_packet_loss
[35mDEBUG   [0m tests.conftest:conftest.py:42 Running fixture teardown: save_node_logs_on_fail
[35mDEBUG   [0m tests.conftest:conftest.py:45 Test failed, attempting to rename and move logs to the test_results folder
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x0262a45b93d6b04e177d73fae7f95f9289c880bcf7e824933ce2e055238012e98b_6131.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x0262a45b93d6b04e177d73fae7f95f9289c880bcf7e824933ce2e055238012e98b_6131.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x027e44751004d002d708ccd30f2847da5333a92627516e540d643605c60579adb0_6137.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x027e44751004d002d708ccd30f2847da5333a92627516e540d643605c60579adb0_6137.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x0256150046af3c90e47d162c844a4d3e4c98be2ca6a4fe3e8d63b996b1afd6dd02_6136.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x0256150046af3c90e47d162c844a4d3e4c98be2ca6a4fe3e8d63b996b1afd6dd02_6136.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x0380a412be83772589a7ad5b47fc338483149386996f5ecd8f24e8b8ab5692ffe1_6133.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x0380a412be83772589a7ad5b47fc338483149386996f5ecd8f24e8b8ab5692ffe1_6133.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x02ca408a7d4eff12329f0370dd24e7738863d4649728898f520a4bd163d4b55f08_6135.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x02ca408a7d4eff12329f0370dd24e7738863d4649728898f520a4bd163d4b55f08_6135.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x027c4daf49abb525306fe58eca0d83a292640f55b074bf273121d3cf36045609ce_6138.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x027c4daf49abb525306fe58eca0d83a292640f55b074bf273121d3cf36045609ce_6138.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x03d6bf5f2f19521f6149adef0adf597655810e21edb2a1c885bb1519e8ea7708fd_6134.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x03d6bf5f2f19521f6149adef0adf597655810e21edb2a1c885bb1519e8ea7708fd_6134.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file first_node.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_first_node.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x0367a8c7dc84fbe094059c2f552078f4daaca83048fa839d29e9e4195e1b16457f_6132.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x0367a8c7dc84fbe094059c2f552078f4daaca83048fa839d29e9e4195e1b16457f_6132.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139.log
[35mDEBUG   [0m tests.conftest:conftest.py:62 Running fixture teardown: clear_open_nodes
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: first_node
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x0262a45b93d6b04e177d73fae7f95f9289c880bcf7e824933ce2e055238012e98b_6131
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x027c4daf49abb525306fe58eca0d83a292640f55b074bf273121d3cf36045609ce_6138
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x0367a8c7dc84fbe094059c2f552078f4daaca83048fa839d29e9e4195e1b16457f_6132
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x02ca408a7d4eff12329f0370dd24e7738863d4649728898f520a4bd163d4b55f08_6135
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x0256150046af3c90e47d162c844a4d3e4c98be2ca6a4fe3e8d63b996b1afd6dd02_6136
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x03d6bf5f2f19521f6149adef0adf597655810e21edb2a1c885bb1519e8ea7708fd_6134
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x027e44751004d002d708ccd30f2847da5333a92627516e540d643605c60579adb0_6137
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x0380a412be83772589a7ad5b47fc338483149386996f5ecd8f24e8b8ab5692ffe1_6133
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x022e34ea7105f4a5ad44cbc7094b2f7ad4fc29200f05fdc4e473f90f4cd41ca73c_6139