[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: start_1_node
[32mINFO    [0m src.node.status_node:status_node.py:39 Starting node with command: ['./status-cli', 'serve', '-n', 'first_node', '-p', '19444']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025-02-21T00:29:57.305Z	INFO	status-cli/serve.go:34	Running serve command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -name first_node
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -port 19444
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -light false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -api-modules waku,wakuext,wakuv2,permissions,eth
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -telemetry-server-url
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -fleet status.staging
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025-02-21T00:29:57.305Z	INFO	first_node	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [02-21|00:29:59.518] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.22.3
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [02-21|00:29:59.524] New local node record                    seq=1,740,097,799,523 id=5545f5fbbfd1fb3c ip=127.0.0.1 udp=0 tcp=44809
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [02-21|00:29:59.524] Started P2P networking                   self="enode://f3b56203c4f3d27dbc9062c8163943f5abd714c2707b14189092abc3599e3954b15c4b3b4bd103d85a3a1f03bc75b63ad33f0cf50db7758e7a87e9be2b8278ae@127.0.0.1:44809?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - ERROR[02-21|00:29:59.524] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [02-21|00:29:59.525] HTTP server started                      endpoint=127.0.0.1:19444 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [02-21|00:29:59.553] New local node record                    seq=1,740,097,799,534 id=62f97de21d176a71 ip=10.1.1.94 udp=0 tcp=45289
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [02-21|00:29:59.555] New local node record                    seq=1,740,097,799,535 id=62f97de21d176a71 ip=10.1.1.94 udp=57138 tcp=45289
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [02-21|00:29:59.556] New local node record                    seq=1,740,097,799,536 id=62f97de21d176a71 ip=10.1.1.94 udp=57138 tcp=45289
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025/02/21 00:29:59 httpu: error while parsing response: malformed HTTP response "Æ«4\xd9\xdaS\xc99$\xed\xf63$\xbf\xc7u\x10\xac\x05\rc=L\xebq\x0f\"\xde6\xda\xde\x1c\xe3?Ä€\x0fvK]\xe9\xbaMV-\x88\x1c\xf3h\x11\xe1n\x85\xf6\xc7\xd6\x04\xe0\xc8}\xff\x8f\xfd"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025/02/21 00:29:59 httpu: error while parsing response: malformed HTTP response "\xb7\xbf\xa4A\xb1\xa6\xfd\xe1\x030\xbe\xd2[\xc3\xc2\xe1\xf4+\x0e\xb0g\xe9Ë¦\xedah\xdf\xf1\x05@\f\xf5\xdfG\xdfq\xfe[\xb7\xd6\xf0F\xe8e\xe8\x16t`\x89J\xbc\xdbr\x8c\xa4\b\x7f7\\\xd3O+-\xc826C\x10\xaa\x7f2\x17\xf7\xed)Ð§g\xfc_\xc1\xdcw\x93+\xda0~xu\xa4\xfc\xe3u\xa0R\x0fh+\x9c\x81Ë´\xfa\x06;"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025-02-21T00:29:59.987Z	INFO	first_node	status-cli/util.go:68	account created, key UID: 0x5e4dd577a0997c3d6c239b26a64575779df436d99527f88219c223891d51eaa0
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [02-21|00:29:59.988] New local node record                    seq=1,740,097,799,537 id=62f97de21d176a71 ip=10.1.1.94 udp=57138 tcp=45289
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025-02-21T00:30:00.018Z	INFO	first_node	status-cli/util.go:93	messenger started, public key: 0x04b8beb2fd3ebbc01952c268a3fb8b71c6511222bebf5dbf75cd8ade2b9325060fe94b2fe3ae2f70d09a5e804b257d4367ec8619efb7cf8d8a3a7068ab2d56963e
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025/02/21 00:30:00 httpu: error while parsing response: malformed HTTP response "\x92\xc5\xd1\xf2\xe1&\xbf\x1a\x1bÈ”5\x0fwi\xbcR\xda\xe6\xb3Å“l\x8dm\xf7\x18\xc0\xb2"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025/02/21 00:30:00 httpu: error while parsing response: malformed HTTP response "A\xacp\x00\xf5\x11\x18Du\xd7]\xa9\xeb\xdf<\x88\x11\x91\xa5|\xc6d#7\x04U!a/\x96\xb9\xces'dAÃ´\xe9\x9bÄŠ,\x8et\x9a\xcbBrF\xd8\x1c\xcf$\x89\xb3\xfcQ\xa0\xb7\xd78\x04"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025/02/21 00:30:00 httpu: error while parsing response: malformed HTTP response "×š\xe3\xe0n8.q\x8d\xba\xf4T\xdfq\xb0f9D\xfeKX\xfc\xa8r\x98V:\x1f~\x1fu\xbdw\xcb\xdaw\x8bR=3'\xeak\x03sU:\f&\x18tt\x8f\x15\x1e^\ah\xb3\x17\x82&\x93"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025-02-21T00:30:05.018Z	INFO	first_node	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130', '-kid', '0xd8d0a6ec6b7198cb0217115fd766fab8ff146a351ef79446c2dec6d7dbf7a007']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - 2025-02-21T00:30:05.315Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - -name 0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - -key-uid 0xd8d0a6ec6b7198cb0217115fd766fab8ff146a351ef79446c2dec6d7dbf7a007
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - 2025-02-21T00:30:05.315Z	INFO	0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [02-21|00:30:05.359] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.22.3
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - ERROR[02-21|00:30:05.368] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [02-21|00:30:05.368] New local node record                    seq=1,737,419,564,795 id=21e155c21669159a ip=127.0.0.1 udp=0 tcp=38315
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [02-21|00:30:05.368] Started P2P networking                   self="enode://3adb140cde1eb80c72ac2a83452dabbd2d236498950c66e2194aba96737679facd1c9dc1ec9a7a2052df0b0b89ad1b038868776452403d573e8f3551b0e26fbc@127.0.0.1:38315?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [02-21|00:30:05.368] HTTP server started                      endpoint=127.0.0.1:6130 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [02-21|00:30:05.396] New local node record                    seq=1,740,097,805,372 id=852eb4fa8fdd32a5 ip=10.1.1.94 udp=0 tcp=40073
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [02-21|00:30:05.398] New local node record                    seq=1,740,097,805,373 id=852eb4fa8fdd32a5 ip=10.1.1.94 udp=46293 tcp=40073
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [02-21|00:30:05.400] New local node record                    seq=1,740,097,805,374 id=852eb4fa8fdd32a5 ip=10.1.1.94 udp=46293 tcp=40073
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - 2025-02-21T00:30:05.529Z	INFO	0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130	status-cli/util.go:62	existing account, key UID: 0xd8d0a6ec6b7198cb0217115fd766fab8ff146a351ef79446c2dec6d7dbf7a007
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [02-21|00:30:05.530] New local node record                    seq=1,740,097,805,375 id=852eb4fa8fdd32a5 ip=10.1.1.94 udp=46293 tcp=40073
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - 2025-02-21T00:30:05.548Z	INFO	0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130	status-cli/util.go:93	messenger started, public key: 0x04c61f8fa3515a136d6a0860b6cdb68ecd4b2d8df3f494a1b628b5f159c8168eb431422a84d88654a8bcffcccf7130e656351c12b7f31eb621de6d944d9c62b38d
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137', '-kid', '0x19f84f473f249eb2a536e729d1f2c0efd07cf8c214901a0faa4d83f2e71ece36']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-02-21T00:30:07.320Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - -name 0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - -key-uid 0x19f84f473f249eb2a536e729d1f2c0efd07cf8c214901a0faa4d83f2e71ece36
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-02-21T00:30:07.320Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [02-21|00:30:07.359] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.22.3
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - ERROR[02-21|00:30:07.368] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [02-21|00:30:07.368] New local node record                    seq=1,737,419,633,056 id=4d486e8dbc7eb7b6 ip=127.0.0.1 udp=0 tcp=42871
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [02-21|00:30:07.368] Started P2P networking                   self="enode://88fdc7f7abca4ed0a72cfac7bbeb5ff6e6aeeb5dc2f2baf3f0e4dc9c1a9781862fa1544e09a59c772ded4335d9dbb9bc1e53eace961ebeb40bc9456f10dafa8f@127.0.0.1:42871?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [02-21|00:30:07.369] HTTP server started                      endpoint=127.0.0.1:6137 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [02-21|00:30:07.389] New local node record                    seq=1,740,097,807,372 id=20fa6d1d6a83fa64 ip=10.1.1.94 udp=0 tcp=40733
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [02-21|00:30:07.390] New local node record                    seq=1,740,097,807,373 id=20fa6d1d6a83fa64 ip=10.1.1.94 udp=48988 tcp=40733
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [02-21|00:30:07.393] New local node record                    seq=1,740,097,807,374 id=20fa6d1d6a83fa64 ip=10.1.1.94 udp=48988 tcp=40733
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-02-21T00:30:07.522Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/util.go:62	existing account, key UID: 0x19f84f473f249eb2a536e729d1f2c0efd07cf8c214901a0faa4d83f2e71ece36
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [02-21|00:30:07.523] New local node record                    seq=1,740,097,807,375 id=20fa6d1d6a83fa64 ip=10.1.1.94 udp=48988 tcp=40733
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-02-21T00:30:07.542Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/util.go:93	messenger started, public key: 0x04f4a3da8d5133481b6c157534cf62275127bb04b5f4dd1fde013c583a2708bc40001ecc2ffbf4edcc4f03aab32c3f76de8ff673dc40d690ccda6d9dea3ada4f6c
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133', '-kid', '0xa9461a9f60364bb61116eabe5cc9b95fd07f7c283d742e3ad11dfd6dbe9b5d89']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-02-21T00:30:09.316Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - -name 0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - -key-uid 0xa9461a9f60364bb61116eabe5cc9b95fd07f7c283d742e3ad11dfd6dbe9b5d89
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-02-21T00:30:09.316Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [02-21|00:30:09.355] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.22.3
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - ERROR[02-21|00:30:09.360] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [02-21|00:30:09.360] New local node record                    seq=1,737,419,596,535 id=ceb3ac46208d5874 ip=127.0.0.1 udp=0 tcp=39405
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [02-21|00:30:09.360] Started P2P networking                   self="enode://258928b145e8e2cfa71d9f79b1c6107f8a42182ee831449209e212c28895554f9555253596f26c14c2f2aebc9bab14e51fea9341444f9f3da43e3fb66230428b@127.0.0.1:39405?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [02-21|00:30:09.361] HTTP server started                      endpoint=127.0.0.1:6133 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [02-21|00:30:09.383] New local node record                    seq=1,740,097,809,365 id=d71d5d420da8fbf6 ip=10.1.1.94 udp=0 tcp=35769
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [02-21|00:30:09.385] New local node record                    seq=1,740,097,809,366 id=d71d5d420da8fbf6 ip=10.1.1.94 udp=42632 tcp=35769
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [02-21|00:30:09.386] New local node record                    seq=1,740,097,809,367 id=d71d5d420da8fbf6 ip=10.1.1.94 udp=42632 tcp=35769
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-02-21T00:30:09.522Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/util.go:62	existing account, key UID: 0xa9461a9f60364bb61116eabe5cc9b95fd07f7c283d742e3ad11dfd6dbe9b5d89
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [02-21|00:30:09.523] New local node record                    seq=1,740,097,809,368 id=d71d5d420da8fbf6 ip=10.1.1.94 udp=42632 tcp=35769
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-02-21T00:30:09.546Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/util.go:93	messenger started, public key: 0x040da8af244c48efedcce3e6d3c3ff3fa0059e8f99a00ee714878a2bd4596de3ce1a5d9869df28bd689db33753d4b39223a1a5d78d16b123c27c2c4d23a9e72f3e
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [02-21|00:30:10.392] New local node record                    seq=1,740,097,805,376 id=852eb4fa8fdd32a5 ip=20.168.85.50 udp=46293 tcp=1312
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - 2025-02-21T00:30:10.549Z	INFO	0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135', '-kid', '0x5991c117b01d9f460b63cae2ec74abb9afd2b85661af889425db7acf2047c393']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - 2025-02-21T00:30:11.321Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - -name 0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - -key-uid 0x5991c117b01d9f460b63cae2ec74abb9afd2b85661af889425db7acf2047c393
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - 2025-02-21T00:30:11.321Z	INFO	0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [02-21|00:30:11.361] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.22.3
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - ERROR[02-21|00:30:11.367] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [02-21|00:30:11.367] New local node record                    seq=1,737,419,614,800 id=3120ffa1600d036e ip=127.0.0.1 udp=0 tcp=44839
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [02-21|00:30:11.367] Started P2P networking                   self="enode://1eee99e98b47a050566c4564713970fad84b9429798d00aea57ad2415987c1634a030183bee393717b626509c0bb811572a545295a0a6affb26c297bb7a1fbf9@127.0.0.1:44839?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [02-21|00:30:11.368] HTTP server started                      endpoint=127.0.0.1:6135 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [02-21|00:30:11.392] New local node record                    seq=1,740,097,811,376 id=7dfc40b512fe2a2c ip=10.1.1.94 udp=0 tcp=45885
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [02-21|00:30:11.393] New local node record                    seq=1,740,097,811,377 id=7dfc40b512fe2a2c ip=10.1.1.94 udp=54215 tcp=45885
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [02-21|00:30:11.395] New local node record                    seq=1,740,097,811,378 id=7dfc40b512fe2a2c ip=10.1.1.94 udp=54215 tcp=45885
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - 2025-02-21T00:30:11.531Z	INFO	0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135	status-cli/util.go:62	existing account, key UID: 0x5991c117b01d9f460b63cae2ec74abb9afd2b85661af889425db7acf2047c393
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [02-21|00:30:11.531] New local node record                    seq=1,740,097,811,379 id=7dfc40b512fe2a2c ip=10.1.1.94 udp=54215 tcp=45885
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - 2025-02-21T00:30:11.555Z	INFO	0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135	status-cli/util.go:93	messenger started, public key: 0x04890fe10a90ba0a415f5f05e7becd52b45f8f4c7c38236a549036dde17457d50811ab1bfb1b3144b4f859a3c323542ff810a716ef579e51035298bc110536cb3c
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [02-21|00:30:12.385] New local node record                    seq=1,740,097,807,376 id=20fa6d1d6a83fa64 ip=20.168.85.50 udp=48988 tcp=1313
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-02-21T00:30:12.543Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134', '-kid', '0xc74a6694789777559695ac9bf06c43cc94c5d4dd1cbd3c1d3eaabe55410855c4']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - 2025-02-21T00:30:13.319Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - -name 0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - -key-uid 0xc74a6694789777559695ac9bf06c43cc94c5d4dd1cbd3c1d3eaabe55410855c4
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - 2025-02-21T00:30:13.320Z	INFO	0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [02-21|00:30:13.358] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.22.3
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - ERROR[02-21|00:30:13.367] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [02-21|00:30:13.367] New local node record                    seq=1,737,419,605,674 id=1e19dde297f8874d ip=127.0.0.1 udp=0 tcp=40177
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [02-21|00:30:13.367] Started P2P networking                   self="enode://99a2b3d7a793500a85f73e4baddc4643c65467df907e6eb7d569a6434b36f4a3255fc0d41038ce07a88508f57eb8e3613c00a996639de8c6b65ea83232116fd0@127.0.0.1:40177?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [02-21|00:30:13.368] HTTP server started                      endpoint=127.0.0.1:6134 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [02-21|00:30:13.397] New local node record                    seq=1,740,097,813,379 id=6ce1c5eadbe3101e ip=10.1.1.94 udp=0 tcp=37787
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [02-21|00:30:13.399] New local node record                    seq=1,740,097,813,380 id=6ce1c5eadbe3101e ip=10.1.1.94 udp=49744 tcp=37787
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [02-21|00:30:13.401] New local node record                    seq=1,740,097,813,381 id=6ce1c5eadbe3101e ip=10.1.1.94 udp=49744 tcp=37787
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - 2025-02-21T00:30:13.546Z	INFO	0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134	status-cli/util.go:62	existing account, key UID: 0xc74a6694789777559695ac9bf06c43cc94c5d4dd1cbd3c1d3eaabe55410855c4
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [02-21|00:30:13.547] New local node record                    seq=1,740,097,813,382 id=6ce1c5eadbe3101e ip=10.1.1.94 udp=49744 tcp=37787
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - 2025-02-21T00:30:13.568Z	INFO	0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134	status-cli/util.go:93	messenger started, public key: 0x044da57de11adc9391ad5ca1677b0ff2da9e02f50f2184d27852966cb46e21a0759e1e0af6514a5d60dbec05dda5ab574f265a71a340caa3f98c92f9091f927a6d
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [02-21|00:30:14.380] New local node record                    seq=1,740,097,809,369 id=d71d5d420da8fbf6 ip=20.168.85.50 udp=42632 tcp=1314
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-02-21T00:30:14.547Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/serve.go:107	retrieve messages...
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [02-21|00:30:14.551] New local node record                    seq=1,740,097,799,538 id=62f97de21d176a71 ip=20.168.85.50 udp=57138 tcp=1312
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - WARN [02-21|00:30:14.552] Served personal_ecRecover                reqid=1 duration="51.847Âµs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - WARN [02-21|00:30:14.555] Served personal_ecRecover                reqid=2 duration="22.682Âµs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - WARN [02-21|00:30:14.557] Served personal_ecRecover                reqid=3 duration="41.918Âµs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - WARN [02-21|00:30:14.559] Served personal_ecRecover                reqid=4 duration="21.44Âµs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - WARN [02-21|00:30:14.560] Served personal_ecRecover                reqid=5 duration="19.987Âµs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - WARN [02-21|00:30:14.562] Served personal_ecRecover                reqid=6 duration="27.291Âµs" err="signature must be 65 bytes long"
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139', '-kid', '0x98806521a617d0fb4d2140c292e22157c3d3197b212f81cd0a3bf164774580f0']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - 2025-02-21T00:30:15.323Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - -name 0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - -key-uid 0x98806521a617d0fb4d2140c292e22157c3d3197b212f81cd0a3bf164774580f0
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - 2025-02-21T00:30:15.323Z	INFO	0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [02-21|00:30:15.361] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.22.3
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - ERROR[02-21|00:30:15.369] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [02-21|00:30:15.369] New local node record                    seq=1,737,419,651,311 id=acb6477d150fec3c ip=127.0.0.1 udp=0 tcp=41131
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [02-21|00:30:15.370] Started P2P networking                   self="enode://437d152e7e8c57d86065f0879910c1f64ae6e14f007b9dc5b5c671ecfb463b66da4ffe7a8753f396f6232e58841a36808d6b65b1c05fb2a3aa9d8ed97ef447e0@127.0.0.1:41131?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [02-21|00:30:15.371] HTTP server started                      endpoint=127.0.0.1:6139 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [02-21|00:30:15.402] New local node record                    seq=1,740,097,815,384 id=e3b94445fe36af5c ip=10.1.1.94 udp=0 tcp=44997
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [02-21|00:30:15.404] New local node record                    seq=1,740,097,815,385 id=e3b94445fe36af5c ip=10.1.1.94 udp=54251 tcp=44997
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [02-21|00:30:15.405] New local node record                    seq=1,740,097,815,386 id=e3b94445fe36af5c ip=10.1.1.94 udp=54251 tcp=44997
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - 2025-02-21T00:30:15.541Z	INFO	0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139	status-cli/util.go:62	existing account, key UID: 0x98806521a617d0fb4d2140c292e22157c3d3197b212f81cd0a3bf164774580f0
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [02-21|00:30:15.542] New local node record                    seq=1,740,097,815,387 id=e3b94445fe36af5c ip=10.1.1.94 udp=54251 tcp=44997
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - 2025-02-21T00:30:15.565Z	INFO	0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139	status-cli/util.go:93	messenger started, public key: 0x040d9cf92cec5a7f9e887525cd79bfc4a927af9e1ce7c4d89246d974613d6ea084c360b2bd11007d57e296de08a6fb0dd0d813d28e57cf5f797745241ddabdd973
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [02-21|00:30:16.389] New local node record                    seq=1,740,097,811,380 id=7dfc40b512fe2a2c ip=20.168.85.50 udp=54215 tcp=1315
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - 2025-02-21T00:30:16.555Z	INFO	0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132', '-kid', '0x317d1096e362af7561ea2f494e3cf3f715137ba7da24d801eea4ac7e10895318']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - 2025-02-21T00:30:17.323Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - -name 0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - -key-uid 0x317d1096e362af7561ea2f494e3cf3f715137ba7da24d801eea4ac7e10895318
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - 2025-02-21T00:30:17.323Z	INFO	0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [02-21|00:30:17.362] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.22.3
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [02-21|00:30:17.369] New local node record                    seq=1,737,419,587,417 id=a3e6d7f2cfadb3c4 ip=127.0.0.1 udp=0 tcp=34751
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [02-21|00:30:17.369] Started P2P networking                   self="enode://aad0dc447a381566b4aa3dc121ad9ba5674e454f820fcda769e16c748042a1e278d4c98d22a4e518f933d8135d897befd8ecfe65c0f92930c9606e794e24e381@127.0.0.1:34751?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - ERROR[02-21|00:30:17.369] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [02-21|00:30:17.370] HTTP server started                      endpoint=127.0.0.1:6132 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [02-21|00:30:17.402] New local node record                    seq=1,740,097,817,381 id=bf7c27f89cdb8814 ip=10.1.1.94 udp=0 tcp=40967
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [02-21|00:30:17.403] New local node record                    seq=1,740,097,817,382 id=bf7c27f89cdb8814 ip=10.1.1.94 udp=33657 tcp=40967
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [02-21|00:30:17.405] New local node record                    seq=1,740,097,817,383 id=bf7c27f89cdb8814 ip=10.1.1.94 udp=33657 tcp=40967
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - 2025-02-21T00:30:17.547Z	INFO	0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132	status-cli/util.go:62	existing account, key UID: 0x317d1096e362af7561ea2f494e3cf3f715137ba7da24d801eea4ac7e10895318
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [02-21|00:30:17.548] New local node record                    seq=1,740,097,817,384 id=bf7c27f89cdb8814 ip=10.1.1.94 udp=33657 tcp=40967
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - 2025-02-21T00:30:17.575Z	INFO	0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132	status-cli/util.go:93	messenger started, public key: 0x041389374bcaf9a1c36230942c58f4e3968c0a2472bfa9041916414f11d228a3b0605c6ede03ff65463fe8a22126d1f2c750991f03bdf352eeb6442611e2b87aa1
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - WARN [02-21|00:30:17.885] Served personal_ecRecover                reqid=1 duration="53.951Âµs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - WARN [02-21|00:30:17.886] Served personal_ecRecover                reqid=2 duration="21.239Âµs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - WARN [02-21|00:30:17.888] Served personal_ecRecover                reqid=3 duration="19.346Âµs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - WARN [02-21|00:30:17.889] Served personal_ecRecover                reqid=4 duration="19.156Âµs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - WARN [02-21|00:30:17.890] Served personal_ecRecover                reqid=5 duration="25.188Âµs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [02-21|00:30:18.395] New local node record                    seq=1,740,097,813,383 id=6ce1c5eadbe3101e ip=20.168.85.50 udp=49744 tcp=1316
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - 2025-02-21T00:30:18.569Z	INFO	0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138', '-kid', '0x1226dcff3cb70a51c0f10a4a47de02a888068b914e654e5626095edc6edf1707']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-02-21T00:30:19.325Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - -name 0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - -key-uid 0x1226dcff3cb70a51c0f10a4a47de02a888068b914e654e5626095edc6edf1707
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-02-21T00:30:19.325Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [02-21|00:30:19.366] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.22.3
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [02-21|00:30:19.376] New local node record                    seq=1,737,419,642,180 id=e3228c0ebd0ad048 ip=127.0.0.1 udp=0 tcp=43681
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [02-21|00:30:19.376] Started P2P networking                   self="enode://e1e8dc76505064a0cd4888bcc75868421543cdfbbcdbe271fd2f512ec4e0013e1e8829edf9dfcf895198aad4056c5e9c238c1c63eab627cfd4fa85b5908c1664@127.0.0.1:43681?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - ERROR[02-21|00:30:19.376] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [02-21|00:30:19.377] HTTP server started                      endpoint=127.0.0.1:6138 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [02-21|00:30:19.404] New local node record                    seq=1,740,097,819,380 id=3da420a861637712 ip=10.1.1.94 udp=0 tcp=41975
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [02-21|00:30:19.406] New local node record                    seq=1,740,097,819,381 id=3da420a861637712 ip=10.1.1.94 udp=36624 tcp=41975
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [02-21|00:30:19.409] New local node record                    seq=1,740,097,819,382 id=3da420a861637712 ip=10.1.1.94 udp=36624 tcp=41975
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-02-21T00:30:19.550Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/util.go:62	existing account, key UID: 0x1226dcff3cb70a51c0f10a4a47de02a888068b914e654e5626095edc6edf1707
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [02-21|00:30:19.554] New local node record                    seq=1,740,097,819,383 id=3da420a861637712 ip=10.1.1.94 udp=36624 tcp=41975
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-02-21T00:30:19.590Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/util.go:93	messenger started, public key: 0x04c05ffc7fbe973116e8a7017bbd49632c7aaa31715924eb62497ce229bd52a6ffe6904b99dd534f66d4b1364770dce92fcc97a901a1adb98dbebddaf6bd876eb6
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-02-21T00:30:19.721Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/serve.go:70	message received: b6aa84b7-07bf-4bed-bc9a-9f35392d5cdf_message_from_0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133_6 (ID=0x1c015e28d09a0bea13fbec2b34d903f712db31e0c75ade7d8addb7cb5fef5ba7)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-02-21T00:30:19.721Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/serve.go:70	message received: 31d88bc1-7723-4801-8587-e6669c3bb9d5 (ID=0x3d8991111740ec3c3dc6976a42a94dcb208b3ddd9d3066e3e48543487253837e)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-02-21T00:30:19.721Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/serve.go:70	message received: 93bc755a-6a8c-4a6d-ada9-af87df0e6f61_message_from_0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133_22 (ID=0x798b16f8ff865e912a9cdc1a5baf52df5473d6b62f4841151b797b700ad32498)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-02-21T00:30:19.721Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/serve.go:70	message received: a96a601c-c9fc-4785-ac46-67617800b20b_message_from_0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133_18 (ID=0x674b87f070485d10654be13ac7162a346af704135525bbdc91aba49e03ecfd7e)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-02-21T00:30:19.721Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/serve.go:70	message received: 83f66acb-d741-4417-a980-aef310a72e1d_message_from_0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133_14 (ID=0xd882d8ad878366a1f9ce7583cc6a12564a5d2fa7eb938bb3c858ccabcb05137c)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-02-21T00:30:19.721Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/serve.go:70	message received: 2a82c9ba-7850-497d-be67-3e9291e80ad2_message_from_0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133_8 (ID=0x5cfda691ca1e2de0282729b397824bc1fd1cc7d3383faa39de67e2a4a80afabd)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-02-21T00:30:19.721Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/serve.go:70	message received: 24ecdd80-27a4-43c9-ad89-be2ead8d976a_message_from_0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133_4 (ID=0xa427ae6851be44f4d485c0b44dc29ce05090ead0560c9659fcd07523d3816b1a)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-02-21T00:30:19.721Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/serve.go:70	message received: bbfa9ebd-4e6a-4612-b802-0a98fa8afadb_message_from_0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133_12 (ID=0x24e01335253a024b183dc7fc9c89f000905713f5040ad828aab98703ec027420)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-02-21T00:30:19.721Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/serve.go:70	message received: 8e28ee95-aeaf-4fa3-8c97-3cff96ab67bc_message_from_0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133_10 (ID=0x0b74d4cf7bab1b929655bdd7cd0aac5388701ab1abf9a5093dcfeecd564108f0)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-02-21T00:30:19.721Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/serve.go:70	message received: c45e5307-6b9f-4cf4-9cec-5d4b9b0fcca7_message_from_0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133_0 (ID=0x1dd325b6e0c43d7b5963c36128f9c970e28a37e9a98fad616dae823cfeb75ead)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-02-21T00:30:19.721Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/serve.go:70	message received: 4b43de54-4ccd-470e-bb0c-0a3a90b8aea7_message_from_0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133_24 (ID=0xe21fc8e359d9e7fe6fb0233e4bcfdcced49e17e94ef495606aab028a22deef63)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-02-21T00:30:19.721Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/serve.go:70	message received: ed8bcf38-8800-49ec-ab6c-02a730f96269_message_from_0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133_20 (ID=0xab02fae4ddab4ca9508a11f8f5eb7173e04bd24170b5b2b6334b7dc575010e42)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-02-21T00:30:19.721Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/serve.go:70	message received: 37257f46-975f-4e79-b6c9-aa3ea7c7011c_message_from_0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133_16 (ID=0x51641192b8de53ebec98729aafb607b77c9aace23a3b933546fa3eed65684cb7)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-02-21T00:30:19.721Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/serve.go:70	message received: 431fbc39-1970-494d-8467-e32e7a4afcd1_message_from_0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133_2 (ID=0xc70dbba7ad951f4ce4c52e4596c16c7c0d3c5eb4206712723a743aba8dcae1b8)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [02-21|00:30:20.393] New local node record                    seq=1,740,097,805,377 id=852eb4fa8fdd32a5 ip=20.168.85.50 udp=46293 tcp=1312
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [02-21|00:30:20.398] New local node record                    seq=1,740,097,815,388 id=e3b94445fe36af5c ip=20.168.85.50 udp=54251 tcp=1318
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - 2025-02-21T00:30:20.565Z	INFO	0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136', '-kid', '0x81bb8c3cf7199471bd4b3dda97fca44a8d2a482f9cda5e413efb11fa68db3f52']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - 2025-02-21T00:30:21.321Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - -name 0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - -key-uid 0x81bb8c3cf7199471bd4b3dda97fca44a8d2a482f9cda5e413efb11fa68db3f52
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - 2025-02-21T00:30:21.322Z	INFO	0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [02-21|00:30:21.363] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.22.3
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [02-21|00:30:21.369] New local node record                    seq=1,737,419,623,946 id=877b25ac259fbb61 ip=127.0.0.1 udp=0 tcp=43403
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [02-21|00:30:21.369] Started P2P networking                   self="enode://3c43eceef4f4dee8fd369a60b6400d45eefc85a84579959675a0d624fbbe868f4dbc522c79a78bf55c7844278981e3bd2bbe4ed39727170d2035215ea236eb0c@127.0.0.1:43403?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - ERROR[02-21|00:30:21.370] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [02-21|00:30:21.371] HTTP server started                      endpoint=127.0.0.1:6136 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [02-21|00:30:21.397] New local node record                    seq=1,740,097,821,379 id=0d6e52cfe2c28dd3 ip=10.1.1.94 udp=0 tcp=42269
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [02-21|00:30:21.399] New local node record                    seq=1,740,097,821,380 id=0d6e52cfe2c28dd3 ip=10.1.1.94 udp=38383 tcp=42269
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [02-21|00:30:21.400] New local node record                    seq=1,740,097,821,381 id=0d6e52cfe2c28dd3 ip=10.1.1.94 udp=38383 tcp=42269
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - 2025-02-21T00:30:21.545Z	INFO	0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136	status-cli/util.go:62	existing account, key UID: 0x81bb8c3cf7199471bd4b3dda97fca44a8d2a482f9cda5e413efb11fa68db3f52
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [02-21|00:30:21.546] New local node record                    seq=1,740,097,821,382 id=0d6e52cfe2c28dd3 ip=10.1.1.94 udp=38383 tcp=42269
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - WARN [02-21|00:30:21.559] Served personal_ecRecover                reqid=1 duration="54.923Âµs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - 2025-02-21T00:30:21.567Z	INFO	0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136	status-cli/util.go:93	messenger started, public key: 0x042898fe963497a6d5cdf4bae695090aae18993c81f12e39be2b51b3980b806fa22fd3688e25d44663ce4c02010d7d8856c7bff8c610d1c0d3be4f2d1187426bfe
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [02-21|00:30:22.385] New local node record                    seq=1,740,097,807,377 id=20fa6d1d6a83fa64 ip=20.168.85.50 udp=48988 tcp=1313
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [02-21|00:30:22.399] New local node record                    seq=1,740,097,817,385 id=bf7c27f89cdb8814 ip=20.168.85.50 udp=33657 tcp=1319
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - 2025-02-21T00:30:22.575Z	INFO	0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132	status-cli/serve.go:107	retrieve messages...
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - WARN [02-21|00:30:22.577] Served personal_ecRecover                reqid=1 duration="54.923Âµs" err="signature must be 65 bytes long"
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131', '-kid', '0xe171a00735b54dcf9ecb7a27904fdd4b143362df5354c1e469753d5f08023459']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - 2025-02-21T00:30:23.324Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - -name 0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - -key-uid 0xe171a00735b54dcf9ecb7a27904fdd4b143362df5354c1e469753d5f08023459
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - 2025-02-21T00:30:23.324Z	INFO	0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [02-21|00:30:23.366] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.22.3
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - ERROR[02-21|00:30:23.373] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [02-21|00:30:23.374] New local node record                    seq=1,737,419,578,301 id=91b1bc7236045679 ip=127.0.0.1 udp=0 tcp=36253
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [02-21|00:30:23.374] Started P2P networking                   self="enode://91d8c4c0322908732547f0a21fe21a53e4a636758e1615a385e922f834ad499c271c69dcee9a8fefe3c7479c1584e71ead9adf547235b9547d0349db0b06bee9@127.0.0.1:36253?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [02-21|00:30:23.374] HTTP server started                      endpoint=127.0.0.1:6131 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [02-21|00:30:23.404] New local node record                    seq=1,740,097,823,387 id=55c75b4bc87a4b1f ip=10.1.1.94 udp=0 tcp=37773
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [02-21|00:30:23.406] New local node record                    seq=1,740,097,823,388 id=55c75b4bc87a4b1f ip=10.1.1.94 udp=38099 tcp=37773
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [02-21|00:30:23.407] New local node record                    seq=1,740,097,823,389 id=55c75b4bc87a4b1f ip=10.1.1.94 udp=38099 tcp=37773
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - 2025-02-21T00:30:23.556Z	INFO	0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131	status-cli/util.go:62	existing account, key UID: 0xe171a00735b54dcf9ecb7a27904fdd4b143362df5354c1e469753d5f08023459
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [02-21|00:30:23.556] New local node record                    seq=1,740,097,823,390 id=55c75b4bc87a4b1f ip=10.1.1.94 udp=38099 tcp=37773
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - 2025-02-21T00:30:23.585Z	INFO	0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131	status-cli/util.go:93	messenger started, public key: 0x047171e21124210e88fa7e404355815ceac9793d65706770d642813fdfaacc4e0def04dd42a5be6f28ef68d9e76a297cb7f6fe0326d50547faffaffbaf0fd1a662
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [02-21|00:30:24.380] New local node record                    seq=1,740,097,809,370 id=d71d5d420da8fbf6 ip=20.168.85.50 udp=42632 tcp=1314
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [02-21|00:30:24.401] New local node record                    seq=1,740,097,819,384 id=3da420a861637712 ip=20.168.85.50 udp=36624 tcp=1320
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [02-21|00:30:24.550] New local node record                    seq=1,740,097,799,539 id=62f97de21d176a71 ip=10.1.1.94 udp=57138 tcp=45289
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-02-21T00:30:24.590Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/serve.go:107	retrieve messages...
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 4 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [02-21|00:30:26.393] New local node record                    seq=1,740,097,821,383 id=0d6e52cfe2c28dd3 ip=20.168.85.50 udp=38383 tcp=1321
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - 2025-02-21T00:30:26.568Z	INFO	0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136	status-cli/serve.go:107	retrieve messages...
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - WARN [02-21|00:30:26.581] Served personal_ecRecover                reqid=1 duration="60.554Âµs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [02-21|00:30:27.399] New local node record                    seq=1,740,097,817,386 id=bf7c27f89cdb8814 ip=20.168.85.50 udp=33657 tcp=1318
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - WARN [02-21|00:30:27.579] Served personal_ecRecover                reqid=1 duration="53.831Âµs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - WARN [02-21|00:30:27.595] Served personal_ecRecover                reqid=1 duration="57.548Âµs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [02-21|00:30:28.401] New local node record                    seq=1,740,097,823,391 id=55c75b4bc87a4b1f ip=20.168.85.50 udp=38099 tcp=1322
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - 2025-02-21T00:30:28.586Z	INFO	0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131	status-cli/serve.go:107	retrieve messages...
[35mDEBUG   [0m src.steps.common:common.py:39 Entering context manager: add_latency
[35mDEBUG   [0m src.node.rpc_client:rpc_client.py:21 Node: first_node sends request at address: http://127.0.0.1:19444 with payload: {"jsonrpc": "2.0", "method": "wakuext_fetchCommunity", "params": [{"communityKey": "0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2", "waitForResponse": true, "tryDatabase": true}], "id": 1}
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [02-21|00:30:29.401] New local node record                    seq=1,740,097,819,385 id=3da420a861637712 ip=20.168.85.50 udp=36624 tcp=1319
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [02-21|00:30:29.551] New local node record                    seq=1,740,097,799,540 id=62f97de21d176a71 ip=20.168.85.50 udp=57138 tcp=1322
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - WARN [02-21|00:30:29.569] Served personal_ecRecover                reqid=1 duration="59.271Âµs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [02-21|00:30:31.392] New local node record                    seq=1,740,097,821,384 id=0d6e52cfe2c28dd3 ip=20.168.85.50 udp=38383 tcp=1321
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [02-21|00:30:33.402] New local node record                    seq=1,740,097,823,392 id=55c75b4bc87a4b1f ip=20.168.85.50 udp=38099 tcp=1321
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [02-21|00:30:34.551] New local node record                    seq=1,740,097,799,541 id=62f97de21d176a71 ip=20.168.85.50 udp=57138 tcp=1312
[1m[31mERROR   [0m src.node.rpc_client:rpc_client.py:32 Request to http://127.0.0.1:19444 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node
[35mDEBUG   [0m src.node.rpc_client:rpc_client.py:21 Node: first_node sends request at address: http://127.0.0.1:19444 with payload: {"jsonrpc": "2.0", "method": "wakuext_fetchCommunity", "params": [{"communityKey": "0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2", "waitForResponse": true, "tryDatabase": true}], "id": 1}
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - WARN [02-21|00:30:43.571] Served personal_ecRecover                reqid=1 duration="47.389Âµs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [02-21|00:30:46.393] New local node record                    seq=1,740,097,821,385 id=0d6e52cfe2c28dd3 ip=20.168.85.50 udp=38383 tcp=1321
[1m[31mERROR   [0m src.node.rpc_client:rpc_client.py:32 Request to http://127.0.0.1:19444 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node
[35mDEBUG   [0m src.node.rpc_client:rpc_client.py:21 Node: first_node sends request at address: http://127.0.0.1:19444 with payload: {"jsonrpc": "2.0", "method": "wakuext_fetchCommunity", "params": [{"communityKey": "0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2", "waitForResponse": true, "tryDatabase": true}], "id": 1}
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - WARN [02-21|00:30:56.589] Served personal_ecRecover                reqid=1 duration="67.987Âµs" err="signature must be 65 bytes long"
[1m[31mERROR   [0m src.node.rpc_client:rpc_client.py:32 Request to http://127.0.0.1:19444 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node
[35mDEBUG   [0m src.steps.common:common.py:44 Exiting context manager: add_latency
[35mDEBUG   [0m tests.conftest:conftest.py:42 Running fixture teardown: save_node_logs_on_fail
[35mDEBUG   [0m tests.conftest:conftest.py:45 Test failed, attempting to rename and move logs to the test_results folder
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137.log to test_results/testjoincommunity_test_join_community_with_latency_0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136.log to test_results/testjoincommunity_test_join_community_with_latency_0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135.log to test_results/testjoincommunity_test_join_community_with_latency_0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file first_node.log to test_results/testjoincommunity_test_join_community_with_latency_first_node.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138.log to test_results/testjoincommunity_test_join_community_with_latency_0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130.log to test_results/testjoincommunity_test_join_community_with_latency_0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133.log to test_results/testjoincommunity_test_join_community_with_latency_0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132.log to test_results/testjoincommunity_test_join_community_with_latency_0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131.log to test_results/testjoincommunity_test_join_community_with_latency_0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139.log to test_results/testjoincommunity_test_join_community_with_latency_0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134.log to test_results/testjoincommunity_test_join_community_with_latency_0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134.log
[35mDEBUG   [0m tests.conftest:conftest.py:62 Running fixture teardown: clear_open_nodes
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: first_node
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131