[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: start_1_node
[32mINFO    [0m src.node.status_node:status_node.py:39 Starting node with command: ['./status-cli', 'serve', '-n', 'first_node', '-p', '30570']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2024-12-27T00:33:23.838Z	INFO	status-cli/serve.go:34	Running serve command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -name first_node
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -port 30570
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -light false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -api-modules waku,wakuext,wakuv2,permissions,eth
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -telemetry-server-url
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -fleet status.staging
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2024-12-27T00:33:23.838Z	INFO	first_node	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [12-27|00:33:26.051] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [12-27|00:33:26.055] New local node record                    seq=1,735,259,606,054 id=e5c117990a36e783 ip=127.0.0.1 udp=0 tcp=34209
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [12-27|00:33:26.056] Started P2P networking                   self="enode://d79790498ce457ed10948f96389ac7e4f3f1d27e2ce8f59644ccb9a68ca62ac3c4a4b4574d856dc7731979047cc48019b26cf5dd043829c827f5f1e1f1332493@127.0.0.1:34209?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - ERROR[12-27|00:33:26.056] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [12-27|00:33:26.056] HTTP server started                      endpoint=127.0.0.1:30570 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [12-27|00:33:26.079] New local node record                    seq=1,735,259,606,063 id=694dc3071bc64731 ip=10.1.0.12 udp=49002 tcp=42011
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [12-27|00:33:26.081] New local node record                    seq=1,735,259,606,064 id=694dc3071bc64731 ip=10.1.0.12 udp=49002 tcp=42011
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2024-12-27T00:33:26.521Z	INFO	first_node	status-cli/util.go:68	account created, key UID: 0x00201745af424bd59b87e735e824cac2aec516a8eea6d09401c405c4cb30904e
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [12-27|00:33:26.522] New local node record                    seq=1,735,259,606,065 id=694dc3071bc64731 ip=10.1.0.12 udp=49002 tcp=42011
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2024-12-27T00:33:26.551Z	INFO	first_node	status-cli/util.go:93	messenger started, public key: 0x0491adf58030808a2edc63c695012a42511351bf584f5dc240216c6fb946eae027b8693e9b7c6af208e1a1a7a9304e7e24b8d93ca41daec0d025baff8343fc1f52
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [12-27|00:33:31.076] New local node record                    seq=1,735,259,606,066 id=694dc3071bc64731 ip=172.200.199.144 udp=49002 tcp=23498
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2024-12-27T00:33:31.551Z	INFO	first_node	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x03600e1152158616f5e0b6b8213bd9a2a0b52410f2aef58398f02c1b681fbad117_6131', '-kid', '0x3b37564e663adeaa98537e7feda63dd3abc98654d1e93ee22283bb5d75da1ead']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - 2024-12-27T00:33:31.847Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - -name 0x03600e1152158616f5e0b6b8213bd9a2a0b52410f2aef58398f02c1b681fbad117_6131
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - -key-uid 0x3b37564e663adeaa98537e7feda63dd3abc98654d1e93ee22283bb5d75da1ead
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - 2024-12-27T00:33:31.847Z	INFO	0x03600e1152158616f5e0b6b8213bd9a2a0b52410f2aef58398f02c1b681fbad117_6131	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - INFO [12-27|00:33:31.902] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - ERROR[12-27|00:33:31.910] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - INFO [12-27|00:33:31.910] New local node record                    seq=1,727,788,918,300 id=9ac808199823a0eb ip=127.0.0.1 udp=0 tcp=41079
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - INFO [12-27|00:33:31.910] Started P2P networking                   self="enode://366246209c5b872e1aa920d3ab72272857edc4d85c78f0a6724bda35332b0b0084aded52eae6d53a1af57895fae210d1fb607aba4db9358fa56e61b990433b9c@127.0.0.1:41079?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - INFO [12-27|00:33:31.910] HTTP server started                      endpoint=127.0.0.1:6131 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - INFO [12-27|00:33:31.932] New local node record                    seq=1,735,259,611,914 id=83d47679e6120307 ip=10.1.0.12 udp=0 tcp=39977
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - INFO [12-27|00:33:31.934] New local node record                    seq=1,735,259,611,915 id=83d47679e6120307 ip=10.1.0.12 udp=43387 tcp=39977
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - INFO [12-27|00:33:31.936] New local node record                    seq=1,735,259,611,916 id=83d47679e6120307 ip=10.1.0.12 udp=43387 tcp=39977
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - 2024-12-27T00:33:32.077Z	INFO	0x03600e1152158616f5e0b6b8213bd9a2a0b52410f2aef58398f02c1b681fbad117_6131	status-cli/util.go:62	existing account, key UID: 0x3b37564e663adeaa98537e7feda63dd3abc98654d1e93ee22283bb5d75da1ead
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - INFO [12-27|00:33:32.078] New local node record                    seq=1,735,259,611,917 id=83d47679e6120307 ip=10.1.0.12 udp=43387 tcp=39977
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - 2024-12-27T00:33:32.099Z	INFO	0x03600e1152158616f5e0b6b8213bd9a2a0b52410f2aef58398f02c1b681fbad117_6131	status-cli/util.go:93	messenger started, public key: 0x04f9be3ecf73726466655b09c261c7cc3b5bd99ca4b5b10fee6768970ee93e7f004ac362e30b66944c16a1137de5d6955d0ec3a80e72970eb0c3f032985ab08cc0
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x02afc3fe72d25d01723d97275041e5c000248ca36851c4b7947623561dc957f618_6136', '-kid', '0xb4e057eeae4db5ea877a4280c0b283b66aa7d166cafa34a296236add87d62ae8']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - 2024-12-27T00:33:33.851Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - -name 0x02afc3fe72d25d01723d97275041e5c000248ca36851c4b7947623561dc957f618_6136
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - -key-uid 0xb4e057eeae4db5ea877a4280c0b283b66aa7d166cafa34a296236add87d62ae8
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - 2024-12-27T00:33:33.851Z	INFO	0x02afc3fe72d25d01723d97275041e5c000248ca36851c4b7947623561dc957f618_6136	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - INFO [12-27|00:33:33.905] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - INFO [12-27|00:33:33.911] New local node record                    seq=1,727,788,963,926 id=c47d3ec3d9408d8d ip=127.0.0.1 udp=0 tcp=44227
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - INFO [12-27|00:33:33.911] Started P2P networking                   self="enode://e2f58bef4853d045ae3b7029c10da1acd43702b1b725b9df294d9df01a42beb9cdb6902f860a00971a7c9fd54b8f0cc6b6520c327317487d9930fe63b272609f@127.0.0.1:44227?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - ERROR[12-27|00:33:33.912] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - INFO [12-27|00:33:33.912] HTTP server started                      endpoint=127.0.0.1:6136 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - INFO [12-27|00:33:33.938] New local node record                    seq=1,735,259,613,916 id=063f5cbc7080d01a ip=10.1.0.12 udp=0 tcp=37091
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - INFO [12-27|00:33:33.939] New local node record                    seq=1,735,259,613,917 id=063f5cbc7080d01a ip=10.1.0.12 udp=60950 tcp=37091
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - INFO [12-27|00:33:33.941] New local node record                    seq=1,735,259,613,918 id=063f5cbc7080d01a ip=10.1.0.12 udp=60950 tcp=37091
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - 2024-12-27T00:33:34.087Z	INFO	0x02afc3fe72d25d01723d97275041e5c000248ca36851c4b7947623561dc957f618_6136	status-cli/util.go:62	existing account, key UID: 0xb4e057eeae4db5ea877a4280c0b283b66aa7d166cafa34a296236add87d62ae8
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - INFO [12-27|00:33:34.088] New local node record                    seq=1,735,259,613,919 id=063f5cbc7080d01a ip=10.1.0.12 udp=60950 tcp=37091
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - 2024-12-27T00:33:34.108Z	INFO	0x02afc3fe72d25d01723d97275041e5c000248ca36851c4b7947623561dc957f618_6136	status-cli/util.go:93	messenger started, public key: 0x045bb4b679cf59e10ad9668a6c96413b4b966726b3e70e196db21a1013a982357fc9f6b5dc4cda8f9f1763cb0097b06c12906ead9c2149e4e7b34942cac7ead355
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x035e0af74f39fb6e72c21c1484305dbe5b028a72c3637c333c3c963f276944ee96_6138', '-kid', '0x381cd65f19f50af924e50033c56dd17a3bdbdd8622ac7de38657a11618b8e881']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - 2024-12-27T00:33:35.849Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - -name 0x035e0af74f39fb6e72c21c1484305dbe5b028a72c3637c333c3c963f276944ee96_6138
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - -key-uid 0x381cd65f19f50af924e50033c56dd17a3bdbdd8622ac7de38657a11618b8e881
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - 2024-12-27T00:33:35.849Z	INFO	0x035e0af74f39fb6e72c21c1484305dbe5b028a72c3637c333c3c963f276944ee96_6138	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - INFO [12-27|00:33:35.904] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - INFO [12-27|00:33:35.911] New local node record                    seq=1,727,788,982,191 id=33c271785e99a5eb ip=127.0.0.1 udp=0 tcp=37629
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - INFO [12-27|00:33:35.911] Started P2P networking                   self="enode://f9196f44644a0758153110a9b3a7439e60dd1f7aae7d2d6cdf98d921b40c07e8c8814d73f89926b31aecf7a8b768f7c1320ddf32c53d13d259fae14305b21f40@127.0.0.1:37629?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - ERROR[12-27|00:33:35.912] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - INFO [12-27|00:33:35.913] HTTP server started                      endpoint=127.0.0.1:6138 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - INFO [12-27|00:33:35.933] New local node record                    seq=1,735,259,615,916 id=6f7801b73163c1c9 ip=10.1.0.12 udp=0 tcp=35775
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - INFO [12-27|00:33:35.935] New local node record                    seq=1,735,259,615,917 id=6f7801b73163c1c9 ip=10.1.0.12 udp=54255 tcp=35775
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - INFO [12-27|00:33:35.937] New local node record                    seq=1,735,259,615,918 id=6f7801b73163c1c9 ip=10.1.0.12 udp=54255 tcp=35775
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - 2024-12-27T00:33:36.085Z	INFO	0x035e0af74f39fb6e72c21c1484305dbe5b028a72c3637c333c3c963f276944ee96_6138	status-cli/util.go:62	existing account, key UID: 0x381cd65f19f50af924e50033c56dd17a3bdbdd8622ac7de38657a11618b8e881
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - INFO [12-27|00:33:36.086] New local node record                    seq=1,735,259,615,919 id=6f7801b73163c1c9 ip=10.1.0.12 udp=54255 tcp=35775
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - 2024-12-27T00:33:36.105Z	INFO	0x035e0af74f39fb6e72c21c1484305dbe5b028a72c3637c333c3c963f276944ee96_6138	status-cli/util.go:93	messenger started, public key: 0x04ee16839ad4a02acb8245cfd42d13aca6302bdceab767e73ef3a9bbef9e9b25b3dfa5ffbfe6231d263cee6d2f7fba0f119abcc6ee3753788c002368c0c3706a30
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - INFO [12-27|00:33:36.927] New local node record                    seq=1,735,259,611,918 id=83d47679e6120307 ip=172.200.199.144 udp=43387 tcp=23488
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - 2024-12-27T00:33:37.099Z	INFO	0x03600e1152158616f5e0b6b8213bd9a2a0b52410f2aef58398f02c1b681fbad117_6131	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x036b8c7ea8e7a0651a39c433b661b77eb9fe31b8db28dfda593c30526ac726f5de_6139', '-kid', '0xe38a5af51deca8771d81bc5bdd1d2fc7d970d68fe161b9012c5dc663f3f2d4b0']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - 2024-12-27T00:33:37.870Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - -name 0x036b8c7ea8e7a0651a39c433b661b77eb9fe31b8db28dfda593c30526ac726f5de_6139
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - -key-uid 0xe38a5af51deca8771d81bc5bdd1d2fc7d970d68fe161b9012c5dc663f3f2d4b0
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - 2024-12-27T00:33:37.870Z	INFO	0x036b8c7ea8e7a0651a39c433b661b77eb9fe31b8db28dfda593c30526ac726f5de_6139	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - INFO [12-27|00:33:37.941] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - ERROR[12-27|00:33:37.947] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - INFO [12-27|00:33:37.948] HTTP server started                      endpoint=127.0.0.1:6139 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - INFO [12-27|00:33:37.949] New local node record                    seq=1,727,788,991,302 id=9a0e42401d062218 ip=127.0.0.1 udp=0 tcp=34623
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - INFO [12-27|00:33:37.949] Started P2P networking                   self="enode://634b69d13dc4d2de9aef02e6b7137a2e2f1e3287d55b6e8c554ca9d92f2d4ce0200e13d1867a2a11ed26172701df1c4a1cf7376706cd73e0bae188a2b5d2e414@127.0.0.1:34623?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - INFO [12-27|00:33:37.987] New local node record                    seq=1,735,259,617,966 id=129d5d24c8c3adc3 ip=10.1.0.12 udp=44040 tcp=37231
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - INFO [12-27|00:33:37.994] New local node record                    seq=1,735,259,617,967 id=129d5d24c8c3adc3 ip=10.1.0.12 udp=44040 tcp=37231
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - 2024-12-27T00:33:38.166Z	INFO	0x036b8c7ea8e7a0651a39c433b661b77eb9fe31b8db28dfda593c30526ac726f5de_6139	status-cli/util.go:62	existing account, key UID: 0xe38a5af51deca8771d81bc5bdd1d2fc7d970d68fe161b9012c5dc663f3f2d4b0
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - INFO [12-27|00:33:38.167] New local node record                    seq=1,735,259,617,968 id=129d5d24c8c3adc3 ip=10.1.0.12 udp=44040 tcp=37231
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - 2024-12-27T00:33:38.196Z	INFO	0x036b8c7ea8e7a0651a39c433b661b77eb9fe31b8db28dfda593c30526ac726f5de_6139	status-cli/util.go:93	messenger started, public key: 0x04c02626669e62a78419296d13a637bace2fa91bbf26bab96a4bf71cf68265c2cb392f3af427156676ebc9531df3aff38a5f941d7c312b86e37ccd6e7de8506dc5
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - INFO [12-27|00:33:38.931] New local node record                    seq=1,735,259,613,920 id=063f5cbc7080d01a ip=172.200.199.144 udp=60950 tcp=23489
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - 2024-12-27T00:33:39.109Z	INFO	0x02afc3fe72d25d01723d97275041e5c000248ca36851c4b7947623561dc957f618_6136	status-cli/serve.go:107	retrieve messages...
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.674] Served personal_ecRecover                reqid=1 duration="62.507µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.676] Served personal_ecRecover                reqid=2 duration="36.668µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.677] Served personal_ecRecover                reqid=3 duration="20.588µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.679] Served personal_ecRecover                reqid=4 duration="21.36µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.681] Served personal_ecRecover                reqid=5 duration="28.924µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.682] Served personal_ecRecover                reqid=6 duration="20.839µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.684] Served personal_ecRecover                reqid=7 duration="22.041µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.686] Served personal_ecRecover                reqid=8 duration="24.456µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.687] Served personal_ecRecover                reqid=9 duration="22.302µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.689] Served personal_ecRecover                reqid=10 duration="19.847µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.690] Served personal_ecRecover                reqid=11 duration="22.733µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.693] Served personal_ecRecover                reqid=12 duration="20.749µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.695] Served personal_ecRecover                reqid=13 duration="21.19µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.696] Served personal_ecRecover                reqid=14 duration="18.385µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.697] Served personal_ecRecover                reqid=15 duration="40.102µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.699] Served personal_ecRecover                reqid=16 duration="15.559µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.701] Served personal_ecRecover                reqid=17 duration="20.739µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.702] Served personal_ecRecover                reqid=18 duration="21.77µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.704] Served personal_ecRecover                reqid=19 duration="19.827µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.706] Served personal_ecRecover                reqid=20 duration="35.497µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.707] Served personal_ecRecover                reqid=21 duration="19.446µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.709] Served personal_ecRecover                reqid=22 duration="22.021µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.711] Served personal_ecRecover                reqid=23 duration="21.22µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.713] Served personal_ecRecover                reqid=24 duration="20.678µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.715] Served personal_ecRecover                reqid=25 duration="20.699µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.720] Served personal_ecRecover                reqid=26 duration="21.79µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.722] Served personal_ecRecover                reqid=27 duration="21.821µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.727] Served personal_ecRecover                reqid=28 duration="26.871µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.729] Served personal_ecRecover                reqid=29 duration="21.54µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.730] Served personal_ecRecover                reqid=30 duration="20.819µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.732] Served personal_ecRecover                reqid=31 duration="20.589µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.734] Served personal_ecRecover                reqid=32 duration="20.347µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.736] Served personal_ecRecover                reqid=33 duration="21.371µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.738] Served personal_ecRecover                reqid=34 duration="20.649µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.739] Served personal_ecRecover                reqid=35 duration="21.2µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.741] Served personal_ecRecover                reqid=36 duration="19.757µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.743] Served personal_ecRecover                reqid=37 duration="20.629µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.745] Served personal_ecRecover                reqid=38 duration="33.272µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.746] Served personal_ecRecover                reqid=39 duration="22.121µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.748] Served personal_ecRecover                reqid=40 duration="21.751µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.750] Served personal_ecRecover                reqid=41 duration="22.863µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.752] Served personal_ecRecover                reqid=42 duration="23.073µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.754] Served personal_ecRecover                reqid=43 duration="22.903µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.755] Served personal_ecRecover                reqid=44 duration="20.729µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.757] Served personal_ecRecover                reqid=45 duration="41.528µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.758] Served personal_ecRecover                reqid=46 duration="21.46µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.760] Served personal_ecRecover                reqid=47 duration="16.481µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.761] Served personal_ecRecover                reqid=48 duration="16.551µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.763] Served personal_ecRecover                reqid=49 duration="20.939µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.764] Served personal_ecRecover                reqid=50 duration="20.118µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.765] Served personal_ecRecover                reqid=51 duration="20.438µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.767] Served personal_ecRecover                reqid=52 duration="21.861µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.769] Served personal_ecRecover                reqid=53 duration="22.191µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.770] Served personal_ecRecover                reqid=54 duration="21.17µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.772] Served personal_ecRecover                reqid=55 duration="17.503µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.773] Served personal_ecRecover                reqid=56 duration="21.36µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.777] Served personal_ecRecover                reqid=57 duration="21.43µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.778] Served personal_ecRecover                reqid=58 duration="41.247µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.780] Served personal_ecRecover                reqid=59 duration="21.45µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.782] Served personal_ecRecover                reqid=60 duration="20.999µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.784] Served personal_ecRecover                reqid=61 duration="21.17µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.786] Served personal_ecRecover                reqid=62 duration="17.183µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.787] Served personal_ecRecover                reqid=63 duration="23.313µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.789] Served personal_ecRecover                reqid=64 duration="21.781µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.791] Served personal_ecRecover                reqid=65 duration="21.5µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.792] Served personal_ecRecover                reqid=66 duration="17.523µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.794] Served personal_ecRecover                reqid=67 duration="21.3µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.795] Served personal_ecRecover                reqid=68 duration="21.67µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.796] Served personal_ecRecover                reqid=69 duration="15.899µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.798] Served personal_ecRecover                reqid=70 duration="19.086µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.800] Served personal_ecRecover                reqid=71 duration="23.023µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.801] Served personal_ecRecover                reqid=72 duration="16.681µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.802] Served personal_ecRecover                reqid=73 duration="19.527µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.804] Served personal_ecRecover                reqid=74 duration="16.541µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.805] Served personal_ecRecover                reqid=75 duration="18.184µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.807] Served personal_ecRecover                reqid=76 duration="20.088µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.808] Served personal_ecRecover                reqid=77 duration="21.51µs" err="signature must be 65 bytes long"
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x0226cbc810a4c88c49da9920b74287463556974170eb628cc791639263b7c9e324_6130', '-kid', '0xdeae06f118e333ee383ea227f1310aa78c41068e95145583e90c1637ea61aa99']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.810] Served personal_ecRecover                reqid=78 duration="21.47µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.811] Served personal_ecRecover                reqid=79 duration="38.181µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.813] Served personal_ecRecover                reqid=80 duration="23.814µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.814] Served personal_ecRecover                reqid=81 duration="20.87µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.816] Served personal_ecRecover                reqid=82 duration="20.178µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.817] Served personal_ecRecover                reqid=83 duration="17.202µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.819] Served personal_ecRecover                reqid=84 duration="20.167µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.820] Served personal_ecRecover                reqid=85 duration="16.761µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.822] Served personal_ecRecover                reqid=86 duration="18.985µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.823] Served personal_ecRecover                reqid=87 duration="20.398µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.825] Served personal_ecRecover                reqid=88 duration="21.45µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.826] Served personal_ecRecover                reqid=89 duration="16.29µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.828] Served personal_ecRecover                reqid=90 duration="15.9µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.829] Served personal_ecRecover                reqid=91 duration="16.651µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.830] Served personal_ecRecover                reqid=92 duration="29.695µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.832] Served personal_ecRecover                reqid=93 duration="21.38µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.833] Served personal_ecRecover                reqid=94 duration="17.192µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.835] Served personal_ecRecover                reqid=95 duration="20.819µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.836] Served personal_ecRecover                reqid=96 duration="21.44µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.839] Served personal_ecRecover                reqid=97 duration="23.464µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.841] Served personal_ecRecover                reqid=98 duration="20.379µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.842] Served personal_ecRecover                reqid=99 duration="44.043µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - WARN [12-27|00:33:39.844] Served personal_ecRecover                reqid=100 duration="23.143µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0226CBC810A4C88C49DA9920B74287463556974170EB628CC791639263B7C9E324_6130 - 2024-12-27T00:33:39.866Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0226CBC810A4C88C49DA9920B74287463556974170EB628CC791639263B7C9E324_6130 - -name 0x0226cbc810a4c88c49da9920b74287463556974170eb628cc791639263b7c9e324_6130
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0226CBC810A4C88C49DA9920B74287463556974170EB628CC791639263B7C9E324_6130 - -key-uid 0xdeae06f118e333ee383ea227f1310aa78c41068e95145583e90c1637ea61aa99
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0226CBC810A4C88C49DA9920B74287463556974170EB628CC791639263B7C9E324_6130 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0226CBC810A4C88C49DA9920B74287463556974170EB628CC791639263B7C9E324_6130 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0226CBC810A4C88C49DA9920B74287463556974170EB628CC791639263B7C9E324_6130 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0226CBC810A4C88C49DA9920B74287463556974170EB628CC791639263B7C9E324_6130 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0226CBC810A4C88C49DA9920B74287463556974170EB628CC791639263B7C9E324_6130 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0226CBC810A4C88C49DA9920B74287463556974170EB628CC791639263B7C9E324_6130 - 2024-12-27T00:33:39.866Z	INFO	0x0226cbc810a4c88c49da9920b74287463556974170eb628cc791639263b7c9e324_6130	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0226CBC810A4C88C49DA9920B74287463556974170EB628CC791639263B7C9E324_6130 - INFO [12-27|00:33:39.938] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0226CBC810A4C88C49DA9920B74287463556974170EB628CC791639263B7C9E324_6130 - INFO [12-27|00:33:39.946] New local node record                    seq=1,727,788,904,679 id=a82bc60840bbedd8 ip=127.0.0.1 udp=0 tcp=36609
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0226CBC810A4C88C49DA9920B74287463556974170EB628CC791639263B7C9E324_6130 - INFO [12-27|00:33:39.946] Started P2P networking                   self="enode://10316046411954dfad1622da44b4780d9d58585a0db23811f71d520113812aedc03c0242250b73418fb01854a82cb3b7a93df0bb3301979f7cb23f2c422521de@127.0.0.1:36609?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0226CBC810A4C88C49DA9920B74287463556974170EB628CC791639263B7C9E324_6130 - ERROR[12-27|00:33:39.948] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0226CBC810A4C88C49DA9920B74287463556974170EB628CC791639263B7C9E324_6130 - INFO [12-27|00:33:39.949] HTTP server started                      endpoint=127.0.0.1:6130 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0226CBC810A4C88C49DA9920B74287463556974170EB628CC791639263B7C9E324_6130 - INFO [12-27|00:33:39.990] New local node record                    seq=1,735,259,619,955 id=dd51cf4c0cbd33bc ip=10.1.0.12 udp=0 tcp=46409
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0226CBC810A4C88C49DA9920B74287463556974170EB628CC791639263B7C9E324_6130 - INFO [12-27|00:33:39.993] New local node record                    seq=1,735,259,619,956 id=dd51cf4c0cbd33bc ip=10.1.0.12 udp=59711 tcp=46409
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0226CBC810A4C88C49DA9920B74287463556974170EB628CC791639263B7C9E324_6130 - INFO [12-27|00:33:39.995] New local node record                    seq=1,735,259,619,957 id=dd51cf4c0cbd33bc ip=10.1.0.12 udp=59711 tcp=46409
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0226CBC810A4C88C49DA9920B74287463556974170EB628CC791639263B7C9E324_6130 - 2024-12-27T00:33:40.230Z	INFO	0x0226cbc810a4c88c49da9920b74287463556974170eb628cc791639263b7c9e324_6130	status-cli/util.go:62	existing account, key UID: 0xdeae06f118e333ee383ea227f1310aa78c41068e95145583e90c1637ea61aa99
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0226CBC810A4C88C49DA9920B74287463556974170EB628CC791639263B7C9E324_6130 - INFO [12-27|00:33:40.230] New local node record                    seq=1,735,259,619,958 id=dd51cf4c0cbd33bc ip=10.1.0.12 udp=59711 tcp=46409
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0226CBC810A4C88C49DA9920B74287463556974170EB628CC791639263B7C9E324_6130 - 2024-12-27T00:33:40.275Z	INFO	0x0226cbc810a4c88c49da9920b74287463556974170eb628cc791639263b7c9e324_6130	status-cli/util.go:93	messenger started, public key: 0x04cc73b3e56c2ad33f184831f2826f69136e8bf1cf9b0e4aaa34cd742b17a7b95f332ca5d038b4eb46effd056e06e3335cb5f10eed2274ede353f56bab8fe558c1
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:40.420] Served personal_ecRecover                reqid=1 duration="57.637µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:40.422] Served personal_ecRecover                reqid=2 duration="38.121µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:40.424] Served personal_ecRecover                reqid=3 duration="32.701µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:40.426] Served personal_ecRecover                reqid=4 duration="63.849µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:40.429] Served personal_ecRecover                reqid=5 duration="76.042µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:40.431] Served personal_ecRecover                reqid=6 duration="62.386µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:40.433] Served personal_ecRecover                reqid=7 duration="59.141µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - 2024-12-27T00:33:40.681Z	INFO	0x03600e1152158616f5e0b6b8213bd9a2a0b52410f2aef58398f02c1b681fbad117_6131	status-cli/serve.go:70	message received: 4b7a408a-425c-431b-aad6-562633ab3f29 (ID=0xd82c53eb8c83fc29d866894cae84c29734c28345ffcb29d96d17ce6b4c530c8d)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - INFO [12-27|00:33:40.930] New local node record                    seq=1,735,259,615,920 id=6f7801b73163c1c9 ip=172.200.199.144 udp=54255 tcp=23490
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - 2024-12-27T00:33:41.107Z	INFO	0x035e0af74f39fb6e72c21c1484305dbe5b028a72c3637c333c3c963f276944ee96_6138	status-cli/serve.go:107	retrieve messages...
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.129] Served personal_ecRecover                reqid=8 duration="37.079µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.131] Served personal_ecRecover                reqid=9 duration="21.951µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.133] Served personal_ecRecover                reqid=10 duration="47.329µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.135] Served personal_ecRecover                reqid=11 duration="20.217µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.137] Served personal_ecRecover                reqid=12 duration="17.824µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.139] Served personal_ecRecover                reqid=13 duration="17.162µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.141] Served personal_ecRecover                reqid=14 duration="21.77µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.142] Served personal_ecRecover                reqid=15 duration="20.789µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.144] Served personal_ecRecover                reqid=16 duration="22.061µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.145] Served personal_ecRecover                reqid=17 duration="20.118µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.147] Served personal_ecRecover                reqid=18 duration="16.21µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.149] Served personal_ecRecover                reqid=19 duration="21.771µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.151] Served personal_ecRecover                reqid=20 duration="20.859µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.155] Served personal_ecRecover                reqid=21 duration="21.67µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.156] Served personal_ecRecover                reqid=22 duration="21.78µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.158] Served personal_ecRecover                reqid=23 duration="20.538µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.160] Served personal_ecRecover                reqid=24 duration="22.201µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.162] Served personal_ecRecover                reqid=25 duration="23.624µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.163] Served personal_ecRecover                reqid=26 duration="24.185µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.165] Served personal_ecRecover                reqid=27 duration="24.947µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.167] Served personal_ecRecover                reqid=28 duration="34.204µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.168] Served personal_ecRecover                reqid=29 duration="53.891µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.170] Served personal_ecRecover                reqid=30 duration="24.135µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.172] Served personal_ecRecover                reqid=31 duration="22.472µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.174] Served personal_ecRecover                reqid=32 duration="22.191µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.176] Served personal_ecRecover                reqid=33 duration="21.199µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.178] Served personal_ecRecover                reqid=34 duration="22.432µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.179] Served personal_ecRecover                reqid=35 duration="23.604µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.180] Served personal_ecRecover                reqid=36 duration="20.849µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:41.182] Served personal_ecRecover                reqid=37 duration="24.175µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.580] Served personal_ecRecover                reqid=1 duration="44.513µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.582] Served personal_ecRecover                reqid=2 duration="21.971µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.583] Served personal_ecRecover                reqid=3 duration="16.641µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.586] Served personal_ecRecover                reqid=4 duration="23.804µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.587] Served personal_ecRecover                reqid=5 duration="16.511µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.589] Served personal_ecRecover                reqid=6 duration="16.701µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.590] Served personal_ecRecover                reqid=7 duration="18.174µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.591] Served personal_ecRecover                reqid=8 duration="19.136µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.593] Served personal_ecRecover                reqid=9 duration="17.002µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.594] Served personal_ecRecover                reqid=10 duration="16.26µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.596] Served personal_ecRecover                reqid=11 duration="15.749µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.598] Served personal_ecRecover                reqid=12 duration="16.331µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.599] Served personal_ecRecover                reqid=13 duration="18.775µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.601] Served personal_ecRecover                reqid=14 duration="18.144µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.602] Served personal_ecRecover                reqid=15 duration="17.222µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.604] Served personal_ecRecover                reqid=16 duration="16.511µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.606] Served personal_ecRecover                reqid=17 duration="18.845µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.608] Served personal_ecRecover                reqid=18 duration="18.765µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.609] Served personal_ecRecover                reqid=19 duration="21.991µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.611] Served personal_ecRecover                reqid=20 duration="19.006µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.612] Served personal_ecRecover                reqid=21 duration="22.512µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.616] Served personal_ecRecover                reqid=22 duration="20.919µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.617] Served personal_ecRecover                reqid=23 duration="16.371µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.628] Served personal_ecRecover                reqid=24 duration="23.504µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.645] Served personal_ecRecover                reqid=25 duration="25.097µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.653] Served personal_ecRecover                reqid=26 duration="24.687µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.657] Served personal_ecRecover                reqid=27 duration="21.76µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.659] Served personal_ecRecover                reqid=28 duration="21.169µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.661] Served personal_ecRecover                reqid=29 duration="18.635µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.664] Served personal_ecRecover                reqid=30 duration="16.832µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.670] Served personal_ecRecover                reqid=31 duration="23.955µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.677] Served personal_ecRecover                reqid=32 duration="20.328µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.679] Served personal_ecRecover                reqid=33 duration="17.923µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.680] Served personal_ecRecover                reqid=34 duration="16.802µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.682] Served personal_ecRecover                reqid=35 duration="16.39µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.683] Served personal_ecRecover                reqid=36 duration="16.742µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.685] Served personal_ecRecover                reqid=37 duration="18.414µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.686] Served personal_ecRecover                reqid=38 duration="22.943µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.688] Served personal_ecRecover                reqid=39 duration="16.441µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.689] Served personal_ecRecover                reqid=40 duration="18.785µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.693] Served personal_ecRecover                reqid=41 duration="21.64µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.694] Served personal_ecRecover                reqid=42 duration="21.46µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.696] Served personal_ecRecover                reqid=43 duration="15.92µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.698] Served personal_ecRecover                reqid=44 duration="17.994µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.699] Served personal_ecRecover                reqid=45 duration="16.14µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.701] Served personal_ecRecover                reqid=46 duration="21.1µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.702] Served personal_ecRecover                reqid=47 duration="17.353µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.704] Served personal_ecRecover                reqid=48 duration="17.673µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - WARN [12-27|00:33:41.705] Served personal_ecRecover                reqid=49 duration="22.853µs" err="signature must be 65 bytes long"
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x022c9bb111279b1264eb3c86d11baf886354bcfed8e7b46db96871686f9f91d96e_6134', '-kid', '0xc307f0b364bd3a14c06e19dd6c8a79ade6bbfee2cc7f1a70923e43fbd1b4514a']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022C9BB111279B1264EB3C86D11BAF886354BCFED8E7B46DB96871686F9F91D96E_6134 - 2024-12-27T00:33:41.858Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022C9BB111279B1264EB3C86D11BAF886354BCFED8E7B46DB96871686F9F91D96E_6134 - -name 0x022c9bb111279b1264eb3c86d11baf886354bcfed8e7b46db96871686f9f91d96e_6134
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022C9BB111279B1264EB3C86D11BAF886354BCFED8E7B46DB96871686F9F91D96E_6134 - -key-uid 0xc307f0b364bd3a14c06e19dd6c8a79ade6bbfee2cc7f1a70923e43fbd1b4514a
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022C9BB111279B1264EB3C86D11BAF886354BCFED8E7B46DB96871686F9F91D96E_6134 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022C9BB111279B1264EB3C86D11BAF886354BCFED8E7B46DB96871686F9F91D96E_6134 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022C9BB111279B1264EB3C86D11BAF886354BCFED8E7B46DB96871686F9F91D96E_6134 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022C9BB111279B1264EB3C86D11BAF886354BCFED8E7B46DB96871686F9F91D96E_6134 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022C9BB111279B1264EB3C86D11BAF886354BCFED8E7B46DB96871686F9F91D96E_6134 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022C9BB111279B1264EB3C86D11BAF886354BCFED8E7B46DB96871686F9F91D96E_6134 - 2024-12-27T00:33:41.858Z	INFO	0x022c9bb111279b1264eb3c86d11baf886354bcfed8e7b46db96871686f9f91d96e_6134	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022C9BB111279B1264EB3C86D11BAF886354BCFED8E7B46DB96871686F9F91D96E_6134 - INFO [12-27|00:33:41.915] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022C9BB111279B1264EB3C86D11BAF886354BCFED8E7B46DB96871686F9F91D96E_6134 - INFO [12-27|00:33:41.923] New local node record                    seq=1,727,788,945,676 id=69438348dfbb31cc ip=127.0.0.1 udp=0 tcp=46371
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022C9BB111279B1264EB3C86D11BAF886354BCFED8E7B46DB96871686F9F91D96E_6134 - INFO [12-27|00:33:41.923] Started P2P networking                   self="enode://5dbd4502d3777eaed0712bb0eb666ec37bc47b447e980e2fc051b89c9310b974d01140db788915cf01aabe910b671fabf8a73376ea89f437bed9ba3779218076@127.0.0.1:46371?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022C9BB111279B1264EB3C86D11BAF886354BCFED8E7B46DB96871686F9F91D96E_6134 - ERROR[12-27|00:33:41.923] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022C9BB111279B1264EB3C86D11BAF886354BCFED8E7B46DB96871686F9F91D96E_6134 - INFO [12-27|00:33:41.924] HTTP server started                      endpoint=127.0.0.1:6134 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03600E1152158616F5E0B6B8213BD9A2A0B52410F2AEF58398F02C1B681FBAD117_6131 - INFO [12-27|00:33:41.929] New local node record                    seq=1,735,259,611,919 id=83d47679e6120307 ip=172.200.199.144 udp=43387 tcp=23488
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022C9BB111279B1264EB3C86D11BAF886354BCFED8E7B46DB96871686F9F91D96E_6134 - INFO [12-27|00:33:41.949] New local node record                    seq=1,735,259,621,928 id=7c35e28989afe1a3 ip=10.1.0.12 udp=0 tcp=33591
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022C9BB111279B1264EB3C86D11BAF886354BCFED8E7B46DB96871686F9F91D96E_6134 - INFO [12-27|00:33:41.951] New local node record                    seq=1,735,259,621,929 id=7c35e28989afe1a3 ip=10.1.0.12 udp=33115 tcp=33591
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022C9BB111279B1264EB3C86D11BAF886354BCFED8E7B46DB96871686F9F91D96E_6134 - INFO [12-27|00:33:41.953] New local node record                    seq=1,735,259,621,930 id=7c35e28989afe1a3 ip=10.1.0.12 udp=33115 tcp=33591
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:42.112] Served personal_ecRecover                reqid=38 duration="34.324µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:42.114] Served personal_ecRecover                reqid=39 duration="24.275µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:42.119] Served personal_ecRecover                reqid=40 duration="23.493µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022C9BB111279B1264EB3C86D11BAF886354BCFED8E7B46DB96871686F9F91D96E_6134 - 2024-12-27T00:33:42.123Z	INFO	0x022c9bb111279b1264eb3c86d11baf886354bcfed8e7b46db96871686f9f91d96e_6134	status-cli/util.go:62	existing account, key UID: 0xc307f0b364bd3a14c06e19dd6c8a79ade6bbfee2cc7f1a70923e43fbd1b4514a
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022C9BB111279B1264EB3C86D11BAF886354BCFED8E7B46DB96871686F9F91D96E_6134 - INFO [12-27|00:33:42.125] New local node record                    seq=1,735,259,621,931 id=7c35e28989afe1a3 ip=10.1.0.12 udp=33115 tcp=33591
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:42.125] Served personal_ecRecover                reqid=41 duration="35.046µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:42.127] Served personal_ecRecover                reqid=42 duration="22.332µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:42.138] Served personal_ecRecover                reqid=43 duration="72.535µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:42.144] Served personal_ecRecover                reqid=44 duration="22.041µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:42.148] Served personal_ecRecover                reqid=45 duration="21.26µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:42.150] Served personal_ecRecover                reqid=46 duration="23.103µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:42.157] Served personal_ecRecover                reqid=47 duration="22.803µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022C9BB111279B1264EB3C86D11BAF886354BCFED8E7B46DB96871686F9F91D96E_6134 - 2024-12-27T00:33:42.159Z	INFO	0x022c9bb111279b1264eb3c86d11baf886354bcfed8e7b46db96871686f9f91d96e_6134	status-cli/util.go:93	messenger started, public key: 0x04457f448444e5030895c638f21cf1bdb9d69c25ce400d6cd133db29283eada5704a57a944ddd60698c5a466b8baed54d85226dae39b043f5448f0095bbbd7e397
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:42.161] Served personal_ecRecover                reqid=48 duration="23.164µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:42.166] Served personal_ecRecover                reqid=49 duration="20.328µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - WARN [12-27|00:33:42.168] Served personal_ecRecover                reqid=50 duration="17.883µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - INFO [12-27|00:33:42.985] New local node record                    seq=1,735,259,617,969 id=129d5d24c8c3adc3 ip=172.200.199.144 udp=44040 tcp=23497
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - 2024-12-27T00:33:43.197Z	INFO	0x036b8c7ea8e7a0651a39c433b661b77eb9fe31b8db28dfda593c30526ac726f5de_6139	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x02f47b0ac659301b20823022cc4f230e3319ead14f8e3edbfef4a9003f6fbffb8d_6132', '-kid', '0xe825e47f4e41919c36c4c43fe06f61d4f694721ce1168502cc077e2b58376ab6']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02F47B0AC659301B20823022CC4F230E3319EAD14F8E3EDBFEF4A9003F6FBFFB8D_6132 - 2024-12-27T00:33:43.857Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02F47B0AC659301B20823022CC4F230E3319EAD14F8E3EDBFEF4A9003F6FBFFB8D_6132 - -name 0x02f47b0ac659301b20823022cc4f230e3319ead14f8e3edbfef4a9003f6fbffb8d_6132
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02F47B0AC659301B20823022CC4F230E3319EAD14F8E3EDBFEF4A9003F6FBFFB8D_6132 - -key-uid 0xe825e47f4e41919c36c4c43fe06f61d4f694721ce1168502cc077e2b58376ab6
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02F47B0AC659301B20823022CC4F230E3319EAD14F8E3EDBFEF4A9003F6FBFFB8D_6132 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02F47B0AC659301B20823022CC4F230E3319EAD14F8E3EDBFEF4A9003F6FBFFB8D_6132 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02F47B0AC659301B20823022CC4F230E3319EAD14F8E3EDBFEF4A9003F6FBFFB8D_6132 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02F47B0AC659301B20823022CC4F230E3319EAD14F8E3EDBFEF4A9003F6FBFFB8D_6132 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02F47B0AC659301B20823022CC4F230E3319EAD14F8E3EDBFEF4A9003F6FBFFB8D_6132 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02F47B0AC659301B20823022CC4F230E3319EAD14F8E3EDBFEF4A9003F6FBFFB8D_6132 - 2024-12-27T00:33:43.857Z	INFO	0x02f47b0ac659301b20823022cc4f230e3319ead14f8e3edbfef4a9003f6fbffb8d_6132	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02F47B0AC659301B20823022CC4F230E3319EAD14F8E3EDBFEF4A9003F6FBFFB8D_6132 - INFO [12-27|00:33:43.917] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02F47B0AC659301B20823022CC4F230E3319EAD14F8E3EDBFEF4A9003F6FBFFB8D_6132 - INFO [12-27|00:33:43.923] New local node record                    seq=1,727,788,927,434 id=e9afe6ee53da8bfc ip=127.0.0.1 udp=0 tcp=42037
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02F47B0AC659301B20823022CC4F230E3319EAD14F8E3EDBFEF4A9003F6FBFFB8D_6132 - INFO [12-27|00:33:43.923] Started P2P networking                   self="enode://2081f0e4cf813441cd7e44b16e47e3c12de8a636f1e5662d8942216b029e8b85a31a7b4fcf19494e05d585f8599a5e4279137b103d76c0f9ddaca72f4149eecc@127.0.0.1:42037?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02F47B0AC659301B20823022CC4F230E3319EAD14F8E3EDBFEF4A9003F6FBFFB8D_6132 - ERROR[12-27|00:33:43.923] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02F47B0AC659301B20823022CC4F230E3319EAD14F8E3EDBFEF4A9003F6FBFFB8D_6132 - INFO [12-27|00:33:43.924] HTTP server started                      endpoint=127.0.0.1:6132 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02F47B0AC659301B20823022CC4F230E3319EAD14F8E3EDBFEF4A9003F6FBFFB8D_6132 - INFO [12-27|00:33:43.953] New local node record                    seq=1,735,259,623,930 id=65fea8b77adac77e ip=10.1.0.12 udp=0 tcp=42245
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02F47B0AC659301B20823022CC4F230E3319EAD14F8E3EDBFEF4A9003F6FBFFB8D_6132 - INFO [12-27|00:33:43.955] New local node record                    seq=1,735,259,623,931 id=65fea8b77adac77e ip=10.1.0.12 udp=58589 tcp=42245
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02F47B0AC659301B20823022CC4F230E3319EAD14F8E3EDBFEF4A9003F6FBFFB8D_6132 - INFO [12-27|00:33:43.958] New local node record                    seq=1,735,259,623,932 id=65fea8b77adac77e ip=10.1.0.12 udp=58589 tcp=42245
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02F47B0AC659301B20823022CC4F230E3319EAD14F8E3EDBFEF4A9003F6FBFFB8D_6132 - 2024-12-27T00:33:44.116Z	INFO	0x02f47b0ac659301b20823022cc4f230e3319ead14f8e3edbfef4a9003f6fbffb8d_6132	status-cli/util.go:62	existing account, key UID: 0xe825e47f4e41919c36c4c43fe06f61d4f694721ce1168502cc077e2b58376ab6
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02F47B0AC659301B20823022CC4F230E3319EAD14F8E3EDBFEF4A9003F6FBFFB8D_6132 - INFO [12-27|00:33:44.116] New local node record                    seq=1,735,259,623,933 id=65fea8b77adac77e ip=10.1.0.12 udp=58589 tcp=42245
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02F47B0AC659301B20823022CC4F230E3319EAD14F8E3EDBFEF4A9003F6FBFFB8D_6132 - 2024-12-27T00:33:44.143Z	INFO	0x02f47b0ac659301b20823022cc4f230e3319ead14f8e3edbfef4a9003f6fbffb8d_6132	status-cli/util.go:93	messenger started, public key: 0x04a2b208fdeac8b95bc0950d8bd91ab5abfbb3217f7882fdcf04fee8654766104a500f9f0909fd1be73acc378775cffd41976f449f2ffb4e01cbde30f353aa8b35
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:44.224] Served personal_ecRecover                reqid=1 duration="74.079µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:44.225] Served personal_ecRecover                reqid=2 duration="40.887µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:44.227] Served personal_ecRecover                reqid=3 duration="23.534µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:44.229] Served personal_ecRecover                reqid=4 duration="21.481µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:44.231] Served personal_ecRecover                reqid=5 duration="21.781µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:44.232] Served personal_ecRecover                reqid=6 duration="20.198µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:44.234] Served personal_ecRecover                reqid=7 duration="20.328µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:44.235] Served personal_ecRecover                reqid=8 duration="22.803µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:44.237] Served personal_ecRecover                reqid=9 duration="24.065µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:44.238] Served personal_ecRecover                reqid=10 duration="22.933µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:44.240] Served personal_ecRecover                reqid=11 duration="20.899µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:44.242] Served personal_ecRecover                reqid=12 duration="27.902µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:44.243] Served personal_ecRecover                reqid=13 duration="19.626µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:44.245] Served personal_ecRecover                reqid=14 duration="18.745µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:44.246] Served personal_ecRecover                reqid=15 duration="21.581µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0226CBC810A4C88C49DA9920B74287463556974170EB628CC791639263B7C9E324_6130 - INFO [12-27|00:33:44.981] New local node record                    seq=1,735,259,619,959 id=dd51cf4c0cbd33bc ip=172.200.199.144 udp=59711 tcp=23491
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.206] Served personal_ecRecover                reqid=16 duration="27.201µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.207] Served personal_ecRecover                reqid=17 duration="23.764µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.209] Served personal_ecRecover                reqid=18 duration="23.253µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.211] Served personal_ecRecover                reqid=19 duration="20.989µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.212] Served personal_ecRecover                reqid=20 duration="15.919µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.214] Served personal_ecRecover                reqid=21 duration="21.821µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.215] Served personal_ecRecover                reqid=22 duration="24.776µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.216] Served personal_ecRecover                reqid=23 duration="22.372µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.218] Served personal_ecRecover                reqid=24 duration="30.447µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.219] Served personal_ecRecover                reqid=25 duration="20.698µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.221] Served personal_ecRecover                reqid=26 duration="21.27µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.222] Served personal_ecRecover                reqid=27 duration="16.22µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.224] Served personal_ecRecover                reqid=28 duration="16.05µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.225] Served personal_ecRecover                reqid=29 duration="23.825µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.226] Served personal_ecRecover                reqid=30 duration="19.286µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.228] Served personal_ecRecover                reqid=31 duration="20.649µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.230] Served personal_ecRecover                reqid=32 duration="17.853µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.231] Served personal_ecRecover                reqid=33 duration="16.962µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.232] Served personal_ecRecover                reqid=34 duration="20.007µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.234] Served personal_ecRecover                reqid=35 duration="23.805µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.235] Served personal_ecRecover                reqid=36 duration="30.848µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.237] Served personal_ecRecover                reqid=37 duration="22.562µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.238] Served personal_ecRecover                reqid=38 duration="21.189µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.240] Served personal_ecRecover                reqid=39 duration="22.181µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.241] Served personal_ecRecover                reqid=40 duration="16.341µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.242] Served personal_ecRecover                reqid=41 duration="21.821µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.244] Served personal_ecRecover                reqid=42 duration="20.289µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:45.245] Served personal_ecRecover                reqid=43 duration="18.404µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0226CBC810A4C88C49DA9920B74287463556974170EB628CC791639263B7C9E324_6130 - 2024-12-27T00:33:45.275Z	INFO	0x0226cbc810a4c88c49da9920b74287463556974170eb628cc791639263b7c9e324_6130	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x02bf80242989f350415573d13a81866ff9e9f97bd335480ce4e4efb74692ca032c_6137', '-kid', '0xf573186115e5ee9069d7ecec95694c80d2605775d307b059410b275445ffde9c']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02BF80242989F350415573D13A81866FF9E9F97BD335480CE4E4EFB74692CA032C_6137 - 2024-12-27T00:33:45.865Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02BF80242989F350415573D13A81866FF9E9F97BD335480CE4E4EFB74692CA032C_6137 - -name 0x02bf80242989f350415573d13a81866ff9e9f97bd335480ce4e4efb74692ca032c_6137
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02BF80242989F350415573D13A81866FF9E9F97BD335480CE4E4EFB74692CA032C_6137 - -key-uid 0xf573186115e5ee9069d7ecec95694c80d2605775d307b059410b275445ffde9c
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02BF80242989F350415573D13A81866FF9E9F97BD335480CE4E4EFB74692CA032C_6137 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02BF80242989F350415573D13A81866FF9E9F97BD335480CE4E4EFB74692CA032C_6137 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02BF80242989F350415573D13A81866FF9E9F97BD335480CE4E4EFB74692CA032C_6137 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02BF80242989F350415573D13A81866FF9E9F97BD335480CE4E4EFB74692CA032C_6137 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02BF80242989F350415573D13A81866FF9E9F97BD335480CE4E4EFB74692CA032C_6137 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02BF80242989F350415573D13A81866FF9E9F97BD335480CE4E4EFB74692CA032C_6137 - 2024-12-27T00:33:45.865Z	INFO	0x02bf80242989f350415573d13a81866ff9e9f97bd335480ce4e4efb74692ca032c_6137	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02BF80242989F350415573D13A81866FF9E9F97BD335480CE4E4EFB74692CA032C_6137 - INFO [12-27|00:33:45.928] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02BF80242989F350415573D13A81866FF9E9F97BD335480CE4E4EFB74692CA032C_6137 - INFO [12-27|00:33:45.933] New local node record                    seq=1,727,788,973,055 id=55864dd925fc2809 ip=127.0.0.1 udp=0 tcp=46289
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02BF80242989F350415573D13A81866FF9E9F97BD335480CE4E4EFB74692CA032C_6137 - INFO [12-27|00:33:45.933] Started P2P networking                   self="enode://778f4f3858b9245ea8b1488fbd0515ec91204e02d07dc3e29a21274356f043ff6eef77fcf80db4e7d17aa94fd2ae4c39d139a97da80a5ad9f1c756ce41e1eae4@127.0.0.1:46289?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02BF80242989F350415573D13A81866FF9E9F97BD335480CE4E4EFB74692CA032C_6137 - ERROR[12-27|00:33:45.934] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02BF80242989F350415573D13A81866FF9E9F97BD335480CE4E4EFB74692CA032C_6137 - INFO [12-27|00:33:45.934] HTTP server started                      endpoint=127.0.0.1:6137 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02BF80242989F350415573D13A81866FF9E9F97BD335480CE4E4EFB74692CA032C_6137 - INFO [12-27|00:33:45.969] New local node record                    seq=1,735,259,625,946 id=42e6bac432049e8a ip=10.1.0.12 udp=44827 tcp=36949
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02BF80242989F350415573D13A81866FF9E9F97BD335480CE4E4EFB74692CA032C_6137 - INFO [12-27|00:33:45.971] New local node record                    seq=1,735,259,625,947 id=42e6bac432049e8a ip=10.1.0.12 udp=44827 tcp=36949
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02BF80242989F350415573D13A81866FF9E9F97BD335480CE4E4EFB74692CA032C_6137 - 2024-12-27T00:33:46.129Z	INFO	0x02bf80242989f350415573d13a81866ff9e9f97bd335480ce4e4efb74692ca032c_6137	status-cli/util.go:62	existing account, key UID: 0xf573186115e5ee9069d7ecec95694c80d2605775d307b059410b275445ffde9c
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02BF80242989F350415573D13A81866FF9E9F97BD335480CE4E4EFB74692CA032C_6137 - INFO [12-27|00:33:46.130] New local node record                    seq=1,735,259,625,948 id=42e6bac432049e8a ip=10.1.0.12 udp=44827 tcp=36949
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02BF80242989F350415573D13A81866FF9E9F97BD335480CE4E4EFB74692CA032C_6137 - 2024-12-27T00:33:46.155Z	INFO	0x02bf80242989f350415573d13a81866ff9e9f97bd335480ce4e4efb74692ca032c_6137	status-cli/util.go:93	messenger started, public key: 0x04ec4307c42514dd88c5beb6bda6a40a5e9e2a1bdff74308ecad175eb3627cb4ca69f69b2a3ae8e86729f399b289d923f82fe5b3c05b997b883c54ba3d9f4d42be
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:46.204] Served personal_ecRecover                reqid=44 duration="27.321µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:46.208] Served personal_ecRecover                reqid=45 duration="21.861µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:46.210] Served personal_ecRecover                reqid=46 duration="23.123µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:46.211] Served personal_ecRecover                reqid=47 duration="39.514µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:46.213] Served personal_ecRecover                reqid=48 duration="16.37µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - WARN [12-27|00:33:46.214] Served personal_ecRecover                reqid=49 duration="20.238µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022C9BB111279B1264EB3C86D11BAF886354BCFED8E7B46DB96871686F9F91D96E_6134 - INFO [12-27|00:33:46.945] New local node record                    seq=1,735,259,621,932 id=7c35e28989afe1a3 ip=172.200.199.144 udp=33115 tcp=23492
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X022C9BB111279B1264EB3C86D11BAF886354BCFED8E7B46DB96871686F9F91D96E_6134 - 2024-12-27T00:33:47.159Z	INFO	0x022c9bb111279b1264eb3c86d11baf886354bcfed8e7b46db96871686f9f91d96e_6134	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x0252e55cac8be876ae9e102cf207ca6ef5be2eff8feaafb79baf7b37311d530074_6133', '-kid', '0x94a79a7074a5cbfc27a6ee4fbe303fb7340f49f6a4bd14ab7757940237918d9e']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0252E55CAC8BE876AE9E102CF207CA6EF5BE2EFF8FEAAFB79BAF7B37311D530074_6133 - 2024-12-27T00:33:47.858Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0252E55CAC8BE876AE9E102CF207CA6EF5BE2EFF8FEAAFB79BAF7B37311D530074_6133 - -name 0x0252e55cac8be876ae9e102cf207ca6ef5be2eff8feaafb79baf7b37311d530074_6133
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0252E55CAC8BE876AE9E102CF207CA6EF5BE2EFF8FEAAFB79BAF7B37311D530074_6133 - -key-uid 0x94a79a7074a5cbfc27a6ee4fbe303fb7340f49f6a4bd14ab7757940237918d9e
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0252E55CAC8BE876AE9E102CF207CA6EF5BE2EFF8FEAAFB79BAF7B37311D530074_6133 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0252E55CAC8BE876AE9E102CF207CA6EF5BE2EFF8FEAAFB79BAF7B37311D530074_6133 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0252E55CAC8BE876AE9E102CF207CA6EF5BE2EFF8FEAAFB79BAF7B37311D530074_6133 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0252E55CAC8BE876AE9E102CF207CA6EF5BE2EFF8FEAAFB79BAF7B37311D530074_6133 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0252E55CAC8BE876AE9E102CF207CA6EF5BE2EFF8FEAAFB79BAF7B37311D530074_6133 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0252E55CAC8BE876AE9E102CF207CA6EF5BE2EFF8FEAAFB79BAF7B37311D530074_6133 - 2024-12-27T00:33:47.858Z	INFO	0x0252e55cac8be876ae9e102cf207ca6ef5be2eff8feaafb79baf7b37311d530074_6133	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0252E55CAC8BE876AE9E102CF207CA6EF5BE2EFF8FEAAFB79BAF7B37311D530074_6133 - INFO [12-27|00:33:47.920] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0252E55CAC8BE876AE9E102CF207CA6EF5BE2EFF8FEAAFB79BAF7B37311D530074_6133 - ERROR[12-27|00:33:47.926] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0252E55CAC8BE876AE9E102CF207CA6EF5BE2EFF8FEAAFB79BAF7B37311D530074_6133 - INFO [12-27|00:33:47.926] New local node record                    seq=1,727,788,936,547 id=2725eebdccf07536 ip=127.0.0.1 udp=0 tcp=33469
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0252E55CAC8BE876AE9E102CF207CA6EF5BE2EFF8FEAAFB79BAF7B37311D530074_6133 - INFO [12-27|00:33:47.926] Started P2P networking                   self="enode://b185c8abad52e07854f58e8ae8b6f81b1d79f68c39e12dfad459d1d521cd94a5aea205b3147ff20becd326e1def432dc75fc5f911548207504316d4f46d9a4d7@127.0.0.1:33469?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0252E55CAC8BE876AE9E102CF207CA6EF5BE2EFF8FEAAFB79BAF7B37311D530074_6133 - INFO [12-27|00:33:47.927] HTTP server started                      endpoint=127.0.0.1:6133 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0252E55CAC8BE876AE9E102CF207CA6EF5BE2EFF8FEAAFB79BAF7B37311D530074_6133 - INFO [12-27|00:33:47.958] New local node record                    seq=1,735,259,627,931 id=25af07a5fb4144af ip=10.1.0.12 udp=0 tcp=42827
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0252E55CAC8BE876AE9E102CF207CA6EF5BE2EFF8FEAAFB79BAF7B37311D530074_6133 - INFO [12-27|00:33:47.960] New local node record                    seq=1,735,259,627,932 id=25af07a5fb4144af ip=10.1.0.12 udp=39513 tcp=42827
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0252E55CAC8BE876AE9E102CF207CA6EF5BE2EFF8FEAAFB79BAF7B37311D530074_6133 - INFO [12-27|00:33:47.963] New local node record                    seq=1,735,259,627,933 id=25af07a5fb4144af ip=10.1.0.12 udp=39513 tcp=42827
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0252E55CAC8BE876AE9E102CF207CA6EF5BE2EFF8FEAAFB79BAF7B37311D530074_6133 - 2024-12-27T00:33:48.126Z	INFO	0x0252e55cac8be876ae9e102cf207ca6ef5be2eff8feaafb79baf7b37311d530074_6133	status-cli/util.go:62	existing account, key UID: 0x94a79a7074a5cbfc27a6ee4fbe303fb7340f49f6a4bd14ab7757940237918d9e
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0252E55CAC8BE876AE9E102CF207CA6EF5BE2EFF8FEAAFB79BAF7B37311D530074_6133 - INFO [12-27|00:33:48.127] New local node record                    seq=1,735,259,627,934 id=25af07a5fb4144af ip=10.1.0.12 udp=39513 tcp=42827
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0252E55CAC8BE876AE9E102CF207CA6EF5BE2EFF8FEAAFB79BAF7B37311D530074_6133 - 2024-12-27T00:33:48.150Z	INFO	0x0252e55cac8be876ae9e102cf207ca6ef5be2eff8feaafb79baf7b37311d530074_6133	status-cli/util.go:93	messenger started, public key: 0x04beaa2e3907a845a32dbdfb857681344504297dffedcd46a33dec97fdc9f98e5f3201bf74a2630ed1d33e8ce33bff8fe842d38219664c0255e416264dc280cd28
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02F47B0AC659301B20823022CC4F230E3319EAD14F8E3EDBFEF4A9003F6FBFFB8D_6132 - INFO [12-27|00:33:48.949] New local node record                    seq=1,735,259,623,934 id=65fea8b77adac77e ip=172.200.199.144 udp=58589 tcp=23493
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02F47B0AC659301B20823022CC4F230E3319EAD14F8E3EDBFEF4A9003F6FBFFB8D_6132 - 2024-12-27T00:33:49.143Z	INFO	0x02f47b0ac659301b20823022cc4f230e3319ead14f8e3edbfef4a9003f6fbffb8d_6132	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x0292e28506f89def6bef386de97d7344e7b4afe5e8281e1cb2318cf83ec2c96ce5_6135', '-kid', '0xc57c8da211d8ee6ddf284e8515416793a2f77952051c57e437c1331d8b967571']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0292E28506F89DEF6BEF386DE97D7344E7B4AFE5E8281E1CB2318CF83EC2C96CE5_6135 - 2024-12-27T00:33:49.866Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0292E28506F89DEF6BEF386DE97D7344E7B4AFE5E8281E1CB2318CF83EC2C96CE5_6135 - -name 0x0292e28506f89def6bef386de97d7344e7b4afe5e8281e1cb2318cf83ec2c96ce5_6135
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0292E28506F89DEF6BEF386DE97D7344E7B4AFE5E8281E1CB2318CF83EC2C96CE5_6135 - -key-uid 0xc57c8da211d8ee6ddf284e8515416793a2f77952051c57e437c1331d8b967571
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0292E28506F89DEF6BEF386DE97D7344E7B4AFE5E8281E1CB2318CF83EC2C96CE5_6135 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0292E28506F89DEF6BEF386DE97D7344E7B4AFE5E8281E1CB2318CF83EC2C96CE5_6135 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0292E28506F89DEF6BEF386DE97D7344E7B4AFE5E8281E1CB2318CF83EC2C96CE5_6135 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0292E28506F89DEF6BEF386DE97D7344E7B4AFE5E8281E1CB2318CF83EC2C96CE5_6135 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0292E28506F89DEF6BEF386DE97D7344E7B4AFE5E8281E1CB2318CF83EC2C96CE5_6135 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0292E28506F89DEF6BEF386DE97D7344E7B4AFE5E8281E1CB2318CF83EC2C96CE5_6135 - 2024-12-27T00:33:49.866Z	INFO	0x0292e28506f89def6bef386de97d7344e7b4afe5e8281e1cb2318cf83ec2c96ce5_6135	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0292E28506F89DEF6BEF386DE97D7344E7B4AFE5E8281E1CB2318CF83EC2C96CE5_6135 - INFO [12-27|00:33:49.928] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0292E28506F89DEF6BEF386DE97D7344E7B4AFE5E8281E1CB2318CF83EC2C96CE5_6135 - ERROR[12-27|00:33:49.936] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0292E28506F89DEF6BEF386DE97D7344E7B4AFE5E8281E1CB2318CF83EC2C96CE5_6135 - INFO [12-27|00:33:49.937] New local node record                    seq=1,727,788,954,796 id=7765e02f60d69100 ip=127.0.0.1 udp=0 tcp=37795
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0292E28506F89DEF6BEF386DE97D7344E7B4AFE5E8281E1CB2318CF83EC2C96CE5_6135 - INFO [12-27|00:33:49.937] Started P2P networking                   self="enode://d42e32353d012032d56bf227c8b1ed5e78b14a4d3b6e6d7dc251f569ee38c418d232fa638a4b0edf0c21237698cb8535b44c75979076926193275ed8db99a5d8@127.0.0.1:37795?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0292E28506F89DEF6BEF386DE97D7344E7B4AFE5E8281E1CB2318CF83EC2C96CE5_6135 - INFO [12-27|00:33:49.937] HTTP server started                      endpoint=127.0.0.1:6135 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0292E28506F89DEF6BEF386DE97D7344E7B4AFE5E8281E1CB2318CF83EC2C96CE5_6135 - INFO [12-27|00:33:49.970] New local node record                    seq=1,735,259,629,950 id=9c85bb18e61906e6 ip=10.1.0.12 udp=34876 tcp=39733
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0292E28506F89DEF6BEF386DE97D7344E7B4AFE5E8281E1CB2318CF83EC2C96CE5_6135 - INFO [12-27|00:33:49.973] New local node record                    seq=1,735,259,629,951 id=9c85bb18e61906e6 ip=10.1.0.12 udp=34876 tcp=39733
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0292E28506F89DEF6BEF386DE97D7344E7B4AFE5E8281E1CB2318CF83EC2C96CE5_6135 - 2024-12-27T00:33:50.132Z	INFO	0x0292e28506f89def6bef386de97d7344e7b4afe5e8281e1cb2318cf83ec2c96ce5_6135	status-cli/util.go:62	existing account, key UID: 0xc57c8da211d8ee6ddf284e8515416793a2f77952051c57e437c1331d8b967571
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0292E28506F89DEF6BEF386DE97D7344E7B4AFE5E8281E1CB2318CF83EC2C96CE5_6135 - INFO [12-27|00:33:50.132] New local node record                    seq=1,735,259,629,952 id=9c85bb18e61906e6 ip=10.1.0.12 udp=34876 tcp=39733
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0292E28506F89DEF6BEF386DE97D7344E7B4AFE5E8281E1CB2318CF83EC2C96CE5_6135 - 2024-12-27T00:33:50.159Z	INFO	0x0292e28506f89def6bef386de97d7344e7b4afe5e8281e1cb2318cf83ec2c96ce5_6135	status-cli/util.go:93	messenger started, public key: 0x046b7f5a61f23c59ae579fadf755cacc96ff369ddb41497b61425ef724a286434eb084f272ead3a47061b7a77e2c8f00fbabb1265ce9732e70cb53565804238090
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035E0AF74F39FB6E72C21C1484305DBE5B028A72C3637C333C3C963F276944EE96_6138 - INFO [12-27|00:33:50.930] New local node record                    seq=1,735,259,615,921 id=6f7801b73163c1c9 ip=172.200.199.144 udp=54255 tcp=23490
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02BF80242989F350415573D13A81866FF9E9F97BD335480CE4E4EFB74692CA032C_6137 - INFO [12-27|00:33:50.964] New local node record                    seq=1,735,259,625,949 id=42e6bac432049e8a ip=172.200.199.144 udp=44827 tcp=23494
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02BF80242989F350415573D13A81866FF9E9F97BD335480CE4E4EFB74692CA032C_6137 - 2024-12-27T00:33:51.155Z	INFO	0x02bf80242989f350415573d13a81866ff9e9f97bd335480ce4e4efb74692ca032c_6137	status-cli/serve.go:107	retrieve messages...
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 4 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0252E55CAC8BE876AE9E102CF207CA6EF5BE2EFF8FEAAFB79BAF7B37311D530074_6133 - INFO [12-27|00:33:52.953] New local node record                    seq=1,735,259,627,935 id=25af07a5fb4144af ip=172.200.199.144 udp=39513 tcp=23495
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0252E55CAC8BE876AE9E102CF207CA6EF5BE2EFF8FEAAFB79BAF7B37311D530074_6133 - 2024-12-27T00:33:53.150Z	INFO	0x0252e55cac8be876ae9e102cf207ca6ef5be2eff8feaafb79baf7b37311d530074_6133	status-cli/serve.go:107	retrieve messages...
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0292E28506F89DEF6BEF386DE97D7344E7B4AFE5E8281E1CB2318CF83EC2C96CE5_6135 - INFO [12-27|00:33:54.967] New local node record                    seq=1,735,259,629,953 id=9c85bb18e61906e6 ip=172.200.199.144 udp=34876 tcp=23496
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X0292E28506F89DEF6BEF386DE97D7344E7B4AFE5E8281E1CB2318CF83EC2C96CE5_6135 - 2024-12-27T00:33:55.161Z	INFO	0x0292e28506f89def6bef386de97d7344e7b4afe5e8281e1cb2318cf83ec2c96ce5_6135	status-cli/serve.go:107	retrieve messages...
[35mDEBUG   [0m src.steps.common:common.py:49 Entering context manager: add_packet_loss
[35mDEBUG   [0m src.node.rpc_client:rpc_client.py:21 Node: first_node sends request at address: http://127.0.0.1:30570 with payload: {"jsonrpc": "2.0", "method": "wakuext_fetchCommunity", "params": [{"communityKey": "0x03600e1152158616f5e0b6b8213bd9a2a0b52410f2aef58398f02c1b681fbad117", "waitForResponse": true, "tryDatabase": true}], "id": 1}
[31m[1mERROR   [0m src.node.rpc_client:rpc_client.py:32 Request to http://127.0.0.1:30570 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node
[35mDEBUG   [0m src.node.rpc_client:rpc_client.py:21 Node: first_node sends request at address: http://127.0.0.1:30570 with payload: {"jsonrpc": "2.0", "method": "wakuext_fetchCommunity", "params": [{"communityKey": "0x03600e1152158616f5e0b6b8213bd9a2a0b52410f2aef58398f02c1b681fbad117", "waitForResponse": true, "tryDatabase": true}], "id": 1}
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036B8C7EA8E7A0651A39C433B661B77EB9FE31B8DB28DFDA593C30526AC726F5DE_6139 - INFO [12-27|00:34:11.024] New local node record                    seq=1,735,259,617,970 id=129d5d24c8c3adc3 ip=10.1.0.12 udp=44040 tcp=37231
[31m[1mERROR   [0m src.node.rpc_client:rpc_client.py:32 Request to http://127.0.0.1:30570 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node
[35mDEBUG   [0m src.node.rpc_client:rpc_client.py:21 Node: first_node sends request at address: http://127.0.0.1:30570 with payload: {"jsonrpc": "2.0", "method": "wakuext_fetchCommunity", "params": [{"communityKey": "0x03600e1152158616f5e0b6b8213bd9a2a0b52410f2aef58398f02c1b681fbad117", "waitForResponse": true, "tryDatabase": true}], "id": 1}
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02AFC3FE72D25D01723D97275041E5C000248CA36851C4B7947623561DC957F618_6136 - INFO [12-27|00:34:23.932] New local node record                    seq=1,735,259,613,921 id=063f5cbc7080d01a ip=172.200.199.144 udp=60950 tcp=23489
[31m[1mERROR   [0m src.node.rpc_client:rpc_client.py:32 Request to http://127.0.0.1:30570 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node
[35mDEBUG   [0m src.steps.common:common.py:54 Exiting context manager: add_packet_loss
[35mDEBUG   [0m tests.conftest:conftest.py:42 Running fixture teardown: save_node_logs_on_fail
[35mDEBUG   [0m tests.conftest:conftest.py:45 Test failed, attempting to rename and move logs to the test_results folder
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x0292e28506f89def6bef386de97d7344e7b4afe5e8281e1cb2318cf83ec2c96ce5_6135.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x0292e28506f89def6bef386de97d7344e7b4afe5e8281e1cb2318cf83ec2c96ce5_6135.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x02f47b0ac659301b20823022cc4f230e3319ead14f8e3edbfef4a9003f6fbffb8d_6132.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x02f47b0ac659301b20823022cc4f230e3319ead14f8e3edbfef4a9003f6fbffb8d_6132.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x035e0af74f39fb6e72c21c1484305dbe5b028a72c3637c333c3c963f276944ee96_6138.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x035e0af74f39fb6e72c21c1484305dbe5b028a72c3637c333c3c963f276944ee96_6138.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x03600e1152158616f5e0b6b8213bd9a2a0b52410f2aef58398f02c1b681fbad117_6131.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x03600e1152158616f5e0b6b8213bd9a2a0b52410f2aef58398f02c1b681fbad117_6131.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x0252e55cac8be876ae9e102cf207ca6ef5be2eff8feaafb79baf7b37311d530074_6133.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x0252e55cac8be876ae9e102cf207ca6ef5be2eff8feaafb79baf7b37311d530074_6133.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x036b8c7ea8e7a0651a39c433b661b77eb9fe31b8db28dfda593c30526ac726f5de_6139.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x036b8c7ea8e7a0651a39c433b661b77eb9fe31b8db28dfda593c30526ac726f5de_6139.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x02bf80242989f350415573d13a81866ff9e9f97bd335480ce4e4efb74692ca032c_6137.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x02bf80242989f350415573d13a81866ff9e9f97bd335480ce4e4efb74692ca032c_6137.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x022c9bb111279b1264eb3c86d11baf886354bcfed8e7b46db96871686f9f91d96e_6134.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x022c9bb111279b1264eb3c86d11baf886354bcfed8e7b46db96871686f9f91d96e_6134.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file first_node.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_first_node.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x02afc3fe72d25d01723d97275041e5c000248ca36851c4b7947623561dc957f618_6136.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x02afc3fe72d25d01723d97275041e5c000248ca36851c4b7947623561dc957f618_6136.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x0226cbc810a4c88c49da9920b74287463556974170eb628cc791639263b7c9e324_6130.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x0226cbc810a4c88c49da9920b74287463556974170eb628cc791639263b7c9e324_6130.log
[35mDEBUG   [0m tests.conftest:conftest.py:62 Running fixture teardown: clear_open_nodes
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: first_node
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x03600e1152158616f5e0b6b8213bd9a2a0b52410f2aef58398f02c1b681fbad117_6131
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x02afc3fe72d25d01723d97275041e5c000248ca36851c4b7947623561dc957f618_6136
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x035e0af74f39fb6e72c21c1484305dbe5b028a72c3637c333c3c963f276944ee96_6138
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x036b8c7ea8e7a0651a39c433b661b77eb9fe31b8db28dfda593c30526ac726f5de_6139
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x0226cbc810a4c88c49da9920b74287463556974170eb628cc791639263b7c9e324_6130
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x022c9bb111279b1264eb3c86d11baf886354bcfed8e7b46db96871686f9f91d96e_6134
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x02f47b0ac659301b20823022cc4f230e3319ead14f8e3edbfef4a9003f6fbffb8d_6132
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x02bf80242989f350415573d13a81866ff9e9f97bd335480ce4e4efb74692ca032c_6137
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x0252e55cac8be876ae9e102cf207ca6ef5be2eff8feaafb79baf7b37311d530074_6133
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x0292e28506f89def6bef386de97d7344e7b4afe5e8281e1cb2318cf83ec2c96ce5_6135