[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: start_1_node
[32mINFO    [0m src.node.status_node:status_node.py:39 Starting node with command: ['./status-cli', 'serve', '-n', 'first_node', '-p', '7133']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025-02-09T00:27:39.283Z	INFO	status-cli/serve.go:34	Running serve command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -name first_node
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -port 7133
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -light false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -api-modules waku,wakuext,wakuv2,permissions,eth
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -telemetry-server-url
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -fleet status.staging
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025-02-09T00:27:39.283Z	INFO	first_node	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [02-09|00:27:41.503] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [02-09|00:27:41.508] New local node record                    seq=1,739,060,861,507 id=6d4862bb66b59d60 ip=127.0.0.1 udp=0 tcp=40009
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - ERROR[02-09|00:27:41.508] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [02-09|00:27:41.508] Started P2P networking                   self="enode://fe57ee4c28d77a1fa955a68cae1a0b5426a5aedfe604298ccca91116d182071ff5311678ecc9c8893edf44de233204526756d690c3477f720ef1e26c4e554b0d@127.0.0.1:40009?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [02-09|00:27:41.509] HTTP server started                      endpoint=127.0.0.1:7133 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [02-09|00:27:41.541] New local node record                    seq=1,739,060,861,513 id=f09b89011ceb0d61 ip=10.1.0.85 udp=0 tcp=33769
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [02-09|00:27:41.542] New local node record                    seq=1,739,060,861,514 id=f09b89011ceb0d61 ip=10.1.0.85 udp=35883 tcp=33769
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [02-09|00:27:41.544] New local node record                    seq=1,739,060,861,515 id=f09b89011ceb0d61 ip=10.1.0.85 udp=35883 tcp=33769
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025-02-09T00:27:41.985Z	INFO	first_node	status-cli/util.go:68	account created, key UID: 0xf7d2fc3f5fc6182c3086a3817568575393427b97a86d6ef7f4df2f2dcba38108
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [02-09|00:27:41.986] New local node record                    seq=1,739,060,861,516 id=f09b89011ceb0d61 ip=10.1.0.85 udp=35883 tcp=33769
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025-02-09T00:27:42.018Z	INFO	first_node	status-cli/util.go:93	messenger started, public key: 0x04a0ae0e027fc87431ca904e4e517b7faf0220c88d29f35ee22eaa70d788fb1408799b41d9e7b8e55863bd6577f04565c04923d63c238959ed9c7b0886c9118e8c
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [02-09|00:27:46.536] New local node record                    seq=1,739,060,861,517 id=f09b89011ceb0d61 ip=52.234.33.71 udp=35883 tcp=47050
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025-02-09T00:27:47.019Z	INFO	first_node	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132', '-kid', '0x317d1096e362af7561ea2f494e3cf3f715137ba7da24d801eea4ac7e10895318']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - 2025-02-09T00:27:47.302Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - -name 0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - -key-uid 0x317d1096e362af7561ea2f494e3cf3f715137ba7da24d801eea4ac7e10895318
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - 2025-02-09T00:27:47.302Z	INFO	0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [02-09|00:27:47.335] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [02-09|00:27:47.341] New local node record                    seq=1,737,419,587,417 id=a3e6d7f2cfadb3c4 ip=127.0.0.1 udp=0 tcp=37159
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [02-09|00:27:47.341] Started P2P networking                   self="enode://aad0dc447a381566b4aa3dc121ad9ba5674e454f820fcda769e16c748042a1e278d4c98d22a4e518f933d8135d897befd8ecfe65c0f92930c9606e794e24e381@127.0.0.1:37159?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - ERROR[02-09|00:27:47.341] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [02-09|00:27:47.342] HTTP server started                      endpoint=127.0.0.1:6132 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [02-09|00:27:47.370] New local node record                    seq=1,739,060,867,353 id=3d4a3a3a4dafb040 ip=10.1.0.85 udp=0 tcp=39107
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [02-09|00:27:47.371] New local node record                    seq=1,739,060,867,354 id=3d4a3a3a4dafb040 ip=10.1.0.85 udp=49983 tcp=39107
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [02-09|00:27:47.377] New local node record                    seq=1,739,060,867,355 id=3d4a3a3a4dafb040 ip=10.1.0.85 udp=49983 tcp=39107
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - 2025-02-09T00:27:47.503Z	INFO	0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132	status-cli/util.go:62	existing account, key UID: 0x317d1096e362af7561ea2f494e3cf3f715137ba7da24d801eea4ac7e10895318
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [02-09|00:27:47.504] New local node record                    seq=1,739,060,867,356 id=3d4a3a3a4dafb040 ip=10.1.0.85 udp=49983 tcp=39107
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - 2025-02-09T00:27:47.521Z	INFO	0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132	status-cli/util.go:93	messenger started, public key: 0x041389374bcaf9a1c36230942c58f4e3968c0a2472bfa9041916414f11d228a3b0605c6ede03ff65463fe8a22126d1f2c750991f03bdf352eeb6442611e2b87aa1
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138', '-kid', '0x1226dcff3cb70a51c0f10a4a47de02a888068b914e654e5626095edc6edf1707']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-02-09T00:27:49.302Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - -name 0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - -key-uid 0x1226dcff3cb70a51c0f10a4a47de02a888068b914e654e5626095edc6edf1707
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-02-09T00:27:49.302Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [02-09|00:27:49.334] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - ERROR[02-09|00:27:49.341] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [02-09|00:27:49.341] New local node record                    seq=1,737,419,642,180 id=e3228c0ebd0ad048 ip=127.0.0.1 udp=0 tcp=36639
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [02-09|00:27:49.341] Started P2P networking                   self="enode://e1e8dc76505064a0cd4888bcc75868421543cdfbbcdbe271fd2f512ec4e0013e1e8829edf9dfcf895198aad4056c5e9c238c1c63eab627cfd4fa85b5908c1664@127.0.0.1:36639?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [02-09|00:27:49.342] HTTP server started                      endpoint=127.0.0.1:6138 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [02-09|00:27:49.372] New local node record                    seq=1,739,060,869,345 id=f0f3bd8711cb7d18 ip=10.1.0.85 udp=51204 tcp=37985
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [02-09|00:27:49.375] New local node record                    seq=1,739,060,869,346 id=f0f3bd8711cb7d18 ip=10.1.0.85 udp=51204 tcp=37985
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-02-09T00:27:49.502Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/util.go:62	existing account, key UID: 0x1226dcff3cb70a51c0f10a4a47de02a888068b914e654e5626095edc6edf1707
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [02-09|00:27:49.504] New local node record                    seq=1,739,060,869,347 id=f0f3bd8711cb7d18 ip=10.1.0.85 udp=51204 tcp=37985
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-02-09T00:27:49.520Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/util.go:93	messenger started, public key: 0x04c05ffc7fbe973116e8a7017bbd49632c7aaa31715924eb62497ce229bd52a6ffe6904b99dd534f66d4b1364770dce92fcc97a901a1adb98dbebddaf6bd876eb6
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137', '-kid', '0x19f84f473f249eb2a536e729d1f2c0efd07cf8c214901a0faa4d83f2e71ece36']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-02-09T00:27:51.303Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - -name 0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - -key-uid 0x19f84f473f249eb2a536e729d1f2c0efd07cf8c214901a0faa4d83f2e71ece36
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-02-09T00:27:51.303Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [02-09|00:27:51.336] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [02-09|00:27:51.343] New local node record                    seq=1,737,419,633,056 id=4d486e8dbc7eb7b6 ip=127.0.0.1 udp=0 tcp=42047
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [02-09|00:27:51.344] Started P2P networking                   self="enode://88fdc7f7abca4ed0a72cfac7bbeb5ff6e6aeeb5dc2f2baf3f0e4dc9c1a9781862fa1544e09a59c772ded4335d9dbb9bc1e53eace961ebeb40bc9456f10dafa8f@127.0.0.1:42047?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - ERROR[02-09|00:27:51.344] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [02-09|00:27:51.344] HTTP server started                      endpoint=127.0.0.1:6137 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [02-09|00:27:51.371] New local node record                    seq=1,739,060,871,348 id=52c72216517240a7 ip=10.1.0.85 udp=54876 tcp=42765
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [02-09|00:27:51.373] New local node record                    seq=1,739,060,871,349 id=52c72216517240a7 ip=10.1.0.85 udp=54876 tcp=42765
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-02-09T00:27:51.503Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/util.go:62	existing account, key UID: 0x19f84f473f249eb2a536e729d1f2c0efd07cf8c214901a0faa4d83f2e71ece36
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [02-09|00:27:51.503] New local node record                    seq=1,739,060,871,350 id=52c72216517240a7 ip=10.1.0.85 udp=54876 tcp=42765
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-02-09T00:27:51.522Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/util.go:93	messenger started, public key: 0x04f4a3da8d5133481b6c157534cf62275127bb04b5f4dd1fde013c583a2708bc40001ecc2ffbf4edcc4f03aab32c3f76de8ff673dc40d690ccda6d9dea3ada4f6c
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [02-09|00:27:52.367] New local node record                    seq=1,739,060,867,357 id=3d4a3a3a4dafb040 ip=52.234.33.71 udp=49983 tcp=47040
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - 2025-02-09T00:27:52.521Z	INFO	0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134', '-kid', '0xc74a6694789777559695ac9bf06c43cc94c5d4dd1cbd3c1d3eaabe55410855c4']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - 2025-02-09T00:27:53.306Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - -name 0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - -key-uid 0xc74a6694789777559695ac9bf06c43cc94c5d4dd1cbd3c1d3eaabe55410855c4
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - 2025-02-09T00:27:53.306Z	INFO	0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [02-09|00:27:53.338] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [02-09|00:27:53.343] New local node record                    seq=1,737,419,605,674 id=1e19dde297f8874d ip=127.0.0.1 udp=0 tcp=35865
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [02-09|00:27:53.344] Started P2P networking                   self="enode://99a2b3d7a793500a85f73e4baddc4643c65467df907e6eb7d569a6434b36f4a3255fc0d41038ce07a88508f57eb8e3613c00a996639de8c6b65ea83232116fd0@127.0.0.1:35865?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - ERROR[02-09|00:27:53.344] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [02-09|00:27:53.345] HTTP server started                      endpoint=127.0.0.1:6134 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [02-09|00:27:53.368] New local node record                    seq=1,739,060,873,350 id=6283d9790d0d3b1c ip=10.1.0.85 udp=0 tcp=42461
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [02-09|00:27:53.369] New local node record                    seq=1,739,060,873,351 id=6283d9790d0d3b1c ip=10.1.0.85 udp=42509 tcp=42461
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [02-09|00:27:53.376] New local node record                    seq=1,739,060,873,352 id=6283d9790d0d3b1c ip=10.1.0.85 udp=42509 tcp=42461
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - 2025-02-09T00:27:53.505Z	INFO	0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134	status-cli/util.go:62	existing account, key UID: 0xc74a6694789777559695ac9bf06c43cc94c5d4dd1cbd3c1d3eaabe55410855c4
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [02-09|00:27:53.506] New local node record                    seq=1,739,060,873,353 id=6283d9790d0d3b1c ip=10.1.0.85 udp=42509 tcp=42461
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - 2025-02-09T00:27:53.531Z	INFO	0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134	status-cli/util.go:93	messenger started, public key: 0x044da57de11adc9391ad5ca1677b0ff2da9e02f50f2184d27852966cb46e21a0759e1e0af6514a5d60dbec05dda5ab574f265a71a340caa3f98c92f9091f927a6d
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [02-09|00:27:54.364] New local node record                    seq=1,739,060,869,348 id=f0f3bd8711cb7d18 ip=52.234.33.71 udp=51204 tcp=47041
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-02-09T00:27:54.520Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131', '-kid', '0xe171a00735b54dcf9ecb7a27904fdd4b143362df5354c1e469753d5f08023459']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - 2025-02-09T00:27:55.309Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - -name 0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - -key-uid 0xe171a00735b54dcf9ecb7a27904fdd4b143362df5354c1e469753d5f08023459
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - 2025-02-09T00:27:55.309Z	INFO	0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [02-09|00:27:55.342] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [02-09|00:27:55.347] New local node record                    seq=1,737,419,578,301 id=91b1bc7236045679 ip=127.0.0.1 udp=0 tcp=38857
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [02-09|00:27:55.347] Started P2P networking                   self="enode://91d8c4c0322908732547f0a21fe21a53e4a636758e1615a385e922f834ad499c271c69dcee9a8fefe3c7479c1584e71ead9adf547235b9547d0349db0b06bee9@127.0.0.1:38857?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - ERROR[02-09|00:27:55.350] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [02-09|00:27:55.350] HTTP server started                      endpoint=127.0.0.1:6131 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [02-09|00:27:55.378] New local node record                    seq=1,739,060,875,354 id=cbdfdeb71348f4b6 ip=10.1.0.85 udp=0 tcp=46711
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [02-09|00:27:55.379] New local node record                    seq=1,739,060,875,355 id=cbdfdeb71348f4b6 ip=10.1.0.85 udp=58568 tcp=46711
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [02-09|00:27:55.382] New local node record                    seq=1,739,060,875,356 id=cbdfdeb71348f4b6 ip=10.1.0.85 udp=58568 tcp=46711
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - 2025-02-09T00:27:55.515Z	INFO	0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131	status-cli/util.go:62	existing account, key UID: 0xe171a00735b54dcf9ecb7a27904fdd4b143362df5354c1e469753d5f08023459
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [02-09|00:27:55.515] New local node record                    seq=1,739,060,875,357 id=cbdfdeb71348f4b6 ip=10.1.0.85 udp=58568 tcp=46711
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - 2025-02-09T00:27:55.541Z	INFO	0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131	status-cli/util.go:93	messenger started, public key: 0x047171e21124210e88fa7e404355815ceac9793d65706770d642813fdfaacc4e0def04dd42a5be6f28ef68d9e76a297cb7f6fe0326d50547faffaffbaf0fd1a662
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [02-09|00:27:56.366] New local node record                    seq=1,739,060,871,351 id=52c72216517240a7 ip=52.234.33.71 udp=54876 tcp=47042
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-02-09T00:27:56.525Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/serve.go:107	retrieve messages...
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - WARN [02-09|00:27:56.545] Served personal_ecRecover                reqid=1 duration="45.745µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - WARN [02-09|00:27:56.552] Served personal_ecRecover                reqid=2 duration="25.197µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - WARN [02-09|00:27:56.554] Served personal_ecRecover                reqid=3 duration="17.583µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - WARN [02-09|00:27:56.562] Served personal_ecRecover                reqid=4 duration="22.292µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - WARN [02-09|00:27:56.566] Served personal_ecRecover                reqid=5 duration="17.693µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - WARN [02-09|00:27:56.569] Served personal_ecRecover                reqid=6 duration="22.012µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - WARN [02-09|00:27:56.576] Served personal_ecRecover                reqid=7 duration="21.239µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - WARN [02-09|00:27:56.579] Served personal_ecRecover                reqid=8 duration="24.786µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - WARN [02-09|00:27:56.582] Served personal_ecRecover                reqid=9 duration="16.431µs" err="signature must be 65 bytes long"
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136', '-kid', '0x81bb8c3cf7199471bd4b3dda97fca44a8d2a482f9cda5e413efb11fa68db3f52']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - 2025-02-09T00:27:57.307Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - -name 0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - -key-uid 0x81bb8c3cf7199471bd4b3dda97fca44a8d2a482f9cda5e413efb11fa68db3f52
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - 2025-02-09T00:27:57.307Z	INFO	0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [02-09|00:27:57.342] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [02-09|00:27:57.347] New local node record                    seq=1,737,419,623,946 id=877b25ac259fbb61 ip=127.0.0.1 udp=0 tcp=38421
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [02-09|00:27:57.347] Started P2P networking                   self="enode://3c43eceef4f4dee8fd369a60b6400d45eefc85a84579959675a0d624fbbe868f4dbc522c79a78bf55c7844278981e3bd2bbe4ed39727170d2035215ea236eb0c@127.0.0.1:38421?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - ERROR[02-09|00:27:57.349] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [02-09|00:27:57.349] HTTP server started                      endpoint=127.0.0.1:6136 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [02-09|00:27:57.381] New local node record                    seq=1,739,060,877,363 id=28baa28a323fd42c ip=10.1.0.85 udp=43989 tcp=34349
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [02-09|00:27:57.383] New local node record                    seq=1,739,060,877,364 id=28baa28a323fd42c ip=10.1.0.85 udp=43989 tcp=34349
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - 2025-02-09T00:27:57.525Z	INFO	0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136	status-cli/util.go:62	existing account, key UID: 0x81bb8c3cf7199471bd4b3dda97fca44a8d2a482f9cda5e413efb11fa68db3f52
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [02-09|00:27:57.526] New local node record                    seq=1,739,060,877,365 id=28baa28a323fd42c ip=10.1.0.85 udp=43989 tcp=34349
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - 2025-02-09T00:27:57.552Z	INFO	0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136	status-cli/util.go:93	messenger started, public key: 0x042898fe963497a6d5cdf4bae695090aae18993c81f12e39be2b51b3980b806fa22fd3688e25d44663ce4c02010d7d8856c7bff8c610d1c0d3be4f2d1187426bfe
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [02-09|00:27:58.365] New local node record                    seq=1,739,060,873,354 id=6283d9790d0d3b1c ip=52.234.33.71 udp=42509 tcp=47043
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - 2025-02-09T00:27:58.531Z	INFO	0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135', '-kid', '0x5991c117b01d9f460b63cae2ec74abb9afd2b85661af889425db7acf2047c393']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - 2025-02-09T00:27:59.308Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - -name 0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - -key-uid 0x5991c117b01d9f460b63cae2ec74abb9afd2b85661af889425db7acf2047c393
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - 2025-02-09T00:27:59.308Z	INFO	0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [02-09|00:27:59.340] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [02-09|00:27:59.347] New local node record                    seq=1,737,419,614,800 id=3120ffa1600d036e ip=127.0.0.1 udp=0 tcp=33557
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [02-09|00:27:59.347] Started P2P networking                   self="enode://1eee99e98b47a050566c4564713970fad84b9429798d00aea57ad2415987c1634a030183bee393717b626509c0bb811572a545295a0a6affb26c297bb7a1fbf9@127.0.0.1:33557?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - ERROR[02-09|00:27:59.348] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [02-09|00:27:59.349] HTTP server started                      endpoint=127.0.0.1:6135 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [02-09|00:27:59.378] New local node record                    seq=1,739,060,879,352 id=a00cb648b5eaf0f5 ip=10.1.0.85 udp=0 tcp=45207
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [02-09|00:27:59.381] New local node record                    seq=1,739,060,879,353 id=a00cb648b5eaf0f5 ip=10.1.0.85 udp=35907 tcp=45207
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [02-09|00:27:59.385] New local node record                    seq=1,739,060,879,354 id=a00cb648b5eaf0f5 ip=10.1.0.85 udp=35907 tcp=45207
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - 2025-02-09T00:27:59.530Z	INFO	0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135	status-cli/util.go:62	existing account, key UID: 0x5991c117b01d9f460b63cae2ec74abb9afd2b85661af889425db7acf2047c393
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [02-09|00:27:59.532] New local node record                    seq=1,739,060,879,355 id=a00cb648b5eaf0f5 ip=10.1.0.85 udp=35907 tcp=45207
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - 2025-02-09T00:27:59.553Z	INFO	0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135	status-cli/util.go:93	messenger started, public key: 0x04890fe10a90ba0a415f5f05e7becd52b45f8f4c7c38236a549036dde17457d50811ab1bfb1b3144b4f859a3c323542ff810a716ef579e51035298bc110536cb3c
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [02-09|00:28:00.370] New local node record                    seq=1,739,060,875,358 id=cbdfdeb71348f4b6 ip=52.234.33.71 udp=58568 tcp=47044
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - 2025-02-09T00:28:00.543Z	INFO	0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133', '-kid', '0xa9461a9f60364bb61116eabe5cc9b95fd07f7c283d742e3ad11dfd6dbe9b5d89']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-02-09T00:28:01.319Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - -name 0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - -key-uid 0xa9461a9f60364bb61116eabe5cc9b95fd07f7c283d742e3ad11dfd6dbe9b5d89
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-02-09T00:28:01.319Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [02-09|00:28:01.363] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [02-09|00:28:01.370] New local node record                    seq=1,737,419,596,535 id=ceb3ac46208d5874 ip=127.0.0.1 udp=0 tcp=37145
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [02-09|00:28:01.371] Started P2P networking                   self="enode://258928b145e8e2cfa71d9f79b1c6107f8a42182ee831449209e212c28895554f9555253596f26c14c2f2aebc9bab14e51fea9341444f9f3da43e3fb66230428b@127.0.0.1:37145?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - ERROR[02-09|00:28:01.373] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [02-09|00:28:01.374] HTTP server started                      endpoint=127.0.0.1:6133 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [02-09|00:28:01.406] New local node record                    seq=1,739,060,881,380 id=16a12b98a47731c1 ip=10.1.0.85 udp=56489 tcp=37599
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [02-09|00:28:01.407] New local node record                    seq=1,739,060,881,381 id=16a12b98a47731c1 ip=10.1.0.85 udp=56489 tcp=37599
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-02-09T00:28:01.631Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/util.go:62	existing account, key UID: 0xa9461a9f60364bb61116eabe5cc9b95fd07f7c283d742e3ad11dfd6dbe9b5d89
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [02-09|00:28:01.632] New local node record                    seq=1,739,060,881,382 id=16a12b98a47731c1 ip=10.1.0.85 udp=56489 tcp=37599
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-02-09T00:28:01.683Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/util.go:93	messenger started, public key: 0x040da8af244c48efedcce3e6d3c3ff3fa0059e8f99a00ee714878a2bd4596de3ce1a5d9869df28bd689db33753d4b39223a1a5d78d16b123c27c2c4d23a9e72f3e
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [02-09|00:28:02.379] New local node record                    seq=1,739,060,877,366 id=28baa28a323fd42c ip=52.234.33.71 udp=43989 tcp=47045
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - 2025-02-09T00:28:02.552Z	INFO	0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130', '-kid', '0xd8d0a6ec6b7198cb0217115fd766fab8ff146a351ef79446c2dec6d7dbf7a007']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-02-09T00:28:03.303Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/serve.go:70	message received: 07280189-0cd4-4887-a385-d6c95753c517_message_from_0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137_20 (ID=0xe83451890cabb56fa426e4df61f6a024330e1dfc6f0d888567c5a05b85bd7942)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-02-09T00:28:03.303Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/serve.go:70	message received: 02e50dc9-932e-4b2b-bf0c-5a8f7951f45e_message_from_0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137_2 (ID=0xb578858d20b00b1a8d41af5692ed07c6dd1d1fe93d08b94163c5a687a16a5640)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-02-09T00:28:03.303Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/serve.go:70	message received: fb1adfeb-4213-4ca5-9a27-8ef885f326a6 (ID=0xdfa8b5e7b12fd04213cc51117c4bc6c94fa3dd8d6bb8a54c13accdb73e30dcc3)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-02-09T00:28:03.303Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/serve.go:70	message received: c0f59888-2b78-452b-9f7f-73b3054866cf_message_from_0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137_8 (ID=0xf08e0f99e233e560d09e0ee25bff09e37d7af720e949874f32f4dd25e36d1004)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-02-09T00:28:03.303Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/serve.go:70	message received: f9c420c2-9d63-49e2-8d5b-6984f2f0202a_message_from_0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137_4 (ID=0x50e1b33e0dc70d301209cc14c5204a6f5fcff881b904ae50c3d9c902a8b42730)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-02-09T00:28:03.303Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/serve.go:70	message received: 7e57a3c0-aee0-4423-b987-e990f905b990_message_from_0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137_0 (ID=0x03ed5ca8731bc6beb005bc0d266245c806767a17b837ab183324942d947b00f8)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-02-09T00:28:03.303Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/serve.go:70	message received: dc0b17b7-77be-443d-b3cd-40917e235592_message_from_0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137_24 (ID=0x8cd235191b033f73e9d5e132a57efa2cd78c9ace2f1a1b4ccd59f51b6fe023fe)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-02-09T00:28:03.303Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/serve.go:70	message received: f7071405-e601-456d-abce-5465a43d6be6_message_from_0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137_16 (ID=0x005964a853961c4ecf7f4cb2951f6c9a1ed312ffb053c947811ac48e43320453)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-02-09T00:28:03.303Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/serve.go:70	message received: 48247f60-ecad-40f0-9cf8-07e1dd730a1a_message_from_0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137_10 (ID=0x19f8b6996f4238983a8f3f555ca13411a4a63f13ca9f531dad638ba0db70ecaf)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-02-09T00:28:03.303Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/serve.go:70	message received: 8829f807-7dcb-4b5f-9622-b5176cccaea8_message_from_0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137_12 (ID=0x885d53a53985f3aad7180b09fdb1a25d311b50fac76ca7db4d0da00703d67726)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-02-09T00:28:03.303Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/serve.go:70	message received: 3bcae01b-bf0b-47a2-a83e-ad05680ef1e3_message_from_0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137_6 (ID=0x2703bba5cb8279a7a840e95e444be2d3074de18392cff8599f445be466a2daa9)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-02-09T00:28:03.303Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/serve.go:70	message received: 0f4856e1-3da3-462e-ab75-85e62dd3423c_message_from_0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137_22 (ID=0x1f2478f5e8d7cca56bfd43c20387b77180ab2a9f2bcbcc21d83ffae8591bdb61)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-02-09T00:28:03.303Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/serve.go:70	message received: 4680a0a5-9b12-4168-a9cb-a285a6c5a4d6_message_from_0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137_18 (ID=0x9fefcf74ccc169589dabb71ec8486a61b980c352abfab19ffd86138886db57d3)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-02-09T00:28:03.304Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/serve.go:70	message received: 03df1836-a5ce-471a-aa8e-aa208920da64_message_from_0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137_14 (ID=0xfc51b918866847f6ebc803bdba22e2c98049d50c08b92ae6bbf81561976e3026)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - 2025-02-09T00:28:03.341Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - -name 0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - -key-uid 0xd8d0a6ec6b7198cb0217115fd766fab8ff146a351ef79446c2dec6d7dbf7a007
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - 2025-02-09T00:28:03.341Z	INFO	0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - WARN [02-09|00:28:03.368] Served personal_ecRecover                reqid=1 duration="147.205µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - WARN [02-09|00:28:03.375] Served personal_ecRecover                reqid=2 duration="29.625µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - WARN [02-09|00:28:03.383] Served personal_ecRecover                reqid=3 duration="32.26µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - WARN [02-09|00:28:03.388] Served personal_ecRecover                reqid=4 duration="23.093µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - WARN [02-09|00:28:03.398] Served personal_ecRecover                reqid=5 duration="69.951µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [02-09|00:28:03.399] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [02-09|00:28:03.407] New local node record                    seq=1,737,419,564,795 id=21e155c21669159a ip=127.0.0.1 udp=0 tcp=43775
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [02-09|00:28:03.407] Started P2P networking                   self="enode://3adb140cde1eb80c72ac2a83452dabbd2d236498950c66e2194aba96737679facd1c9dc1ec9a7a2052df0b0b89ad1b038868776452403d573e8f3551b0e26fbc@127.0.0.1:43775?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - ERROR[02-09|00:28:03.408] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [02-09|00:28:03.411] HTTP server started                      endpoint=127.0.0.1:6130 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - WARN [02-09|00:28:03.414] Served personal_ecRecover                reqid=6 duration="37.861µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - WARN [02-09|00:28:03.424] Served personal_ecRecover                reqid=7 duration="30.237µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - WARN [02-09|00:28:03.428] Served personal_ecRecover                reqid=8 duration="28.293µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - WARN [02-09|00:28:03.432] Served personal_ecRecover                reqid=9 duration="25.878µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - WARN [02-09|00:28:03.437] Served personal_ecRecover                reqid=10 duration="54.472µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - WARN [02-09|00:28:03.448] Served personal_ecRecover                reqid=11 duration="31.018µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - WARN [02-09|00:28:03.452] Served personal_ecRecover                reqid=12 duration="27.061µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - WARN [02-09|00:28:03.454] Served personal_ecRecover                reqid=13 duration="33.954µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [02-09|00:28:03.460] New local node record                    seq=1,739,060,883,418 id=d451981602357e13 ip=10.1.0.85 udp=44697 tcp=35337
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [02-09|00:28:03.462] New local node record                    seq=1,739,060,883,419 id=d451981602357e13 ip=10.1.0.85 udp=44697 tcp=35337
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - WARN [02-09|00:28:03.527] Served personal_ecRecover                reqid=1 duration="82.244µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - WARN [02-09|00:28:03.530] Served personal_ecRecover                reqid=2 duration="23.253µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - WARN [02-09|00:28:03.532] Served personal_ecRecover                reqid=3 duration="22.883µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - WARN [02-09|00:28:03.535] Served personal_ecRecover                reqid=4 duration="62.527µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - WARN [02-09|00:28:03.538] Served personal_ecRecover                reqid=5 duration="62.757µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - WARN [02-09|00:28:03.541] Served personal_ecRecover                reqid=6 duration="24.916µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - WARN [02-09|00:28:03.544] Served personal_ecRecover                reqid=7 duration="21.27µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - WARN [02-09|00:28:03.548] Served personal_ecRecover                reqid=8 duration="23.885µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - WARN [02-09|00:28:03.552] Served personal_ecRecover                reqid=9 duration="59.151µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - 2025-02-09T00:28:03.711Z	INFO	0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130	status-cli/util.go:62	existing account, key UID: 0xd8d0a6ec6b7198cb0217115fd766fab8ff146a351ef79446c2dec6d7dbf7a007
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [02-09|00:28:03.712] New local node record                    seq=1,739,060,883,420 id=d451981602357e13 ip=10.1.0.85 udp=44697 tcp=35337
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - 2025-02-09T00:28:03.740Z	INFO	0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130	status-cli/util.go:93	messenger started, public key: 0x04c61f8fa3515a136d6a0860b6cdb68ecd4b2d8df3f494a1b628b5f159c8168eb431422a84d88654a8bcffcccf7130e656351c12b7f31eb621de6d944d9c62b38d
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [02-09|00:28:04.364] New local node record                    seq=1,739,060,869,349 id=f0f3bd8711cb7d18 ip=52.234.33.71 udp=51204 tcp=47040
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [02-09|00:28:04.376] New local node record                    seq=1,739,060,879,356 id=a00cb648b5eaf0f5 ip=52.234.33.71 udp=35907 tcp=47046
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - 2025-02-09T00:28:04.555Z	INFO	0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139', '-kid', '0x98806521a617d0fb4d2140c292e22157c3d3197b212f81cd0a3bf164774580f0']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - 2025-02-09T00:28:05.318Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - -name 0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - -key-uid 0x98806521a617d0fb4d2140c292e22157c3d3197b212f81cd0a3bf164774580f0
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - 2025-02-09T00:28:05.318Z	INFO	0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [02-09|00:28:05.356] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.21.10
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [02-09|00:28:05.365] New local node record                    seq=1,737,419,651,311 id=acb6477d150fec3c ip=127.0.0.1 udp=0 tcp=38543
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [02-09|00:28:05.365] Started P2P networking                   self="enode://437d152e7e8c57d86065f0879910c1f64ae6e14f007b9dc5b5c671ecfb463b66da4ffe7a8753f396f6232e58841a36808d6b65b1c05fb2a3aa9d8ed97ef447e0@127.0.0.1:38543?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - ERROR[02-09|00:28:05.365] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [02-09|00:28:05.366] HTTP server started                      endpoint=127.0.0.1:6139 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [02-09|00:28:05.404] New local node record                    seq=1,739,060,885,377 id=6e7a55992b8c2bdd ip=10.1.0.85 udp=57638 tcp=43237
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [02-09|00:28:05.409] New local node record                    seq=1,739,060,885,378 id=6e7a55992b8c2bdd ip=10.1.0.85 udp=57638 tcp=43237
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - WARN [02-09|00:28:05.545] Served personal_ecRecover                reqid=1 duration="56.937µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - WARN [02-09|00:28:05.547] Served personal_ecRecover                reqid=2 duration="60.373µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - WARN [02-09|00:28:05.549] Served personal_ecRecover                reqid=3 duration="52.739µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - WARN [02-09|00:28:05.550] Served personal_ecRecover                reqid=4 duration="25.568µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - WARN [02-09|00:28:05.552] Served personal_ecRecover                reqid=5 duration="26.82µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - WARN [02-09|00:28:05.554] Served personal_ecRecover                reqid=6 duration="26.57µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - WARN [02-09|00:28:05.557] Served personal_ecRecover                reqid=7 duration="24.526µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - WARN [02-09|00:28:05.560] Served personal_ecRecover                reqid=8 duration="25.838µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - 2025-02-09T00:28:05.561Z	INFO	0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139	status-cli/util.go:62	existing account, key UID: 0x98806521a617d0fb4d2140c292e22157c3d3197b212f81cd0a3bf164774580f0
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [02-09|00:28:05.562] New local node record                    seq=1,739,060,885,379 id=6e7a55992b8c2bdd ip=10.1.0.85 udp=57638 tcp=43237
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - WARN [02-09|00:28:05.562] Served personal_ecRecover                reqid=9 duration="27.411µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - 2025-02-09T00:28:05.586Z	INFO	0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139	status-cli/util.go:93	messenger started, public key: 0x040d9cf92cec5a7f9e887525cd79bfc4a927af9e1ce7c4d89246d974613d6ea084c360b2bd11007d57e296de08a6fb0dd0d813d28e57cf5f797745241ddabdd973
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [02-09|00:28:06.366] New local node record                    seq=1,739,060,871,352 id=52c72216517240a7 ip=52.234.33.71 udp=54876 tcp=47041
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [02-09|00:28:06.405] New local node record                    seq=1,739,060,881,383 id=16a12b98a47731c1 ip=52.234.33.71 udp=56489 tcp=47047
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-02-09T00:28:06.684Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/serve.go:107	retrieve messages...
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 4 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - WARN [02-09|00:28:07.556] Served personal_ecRecover                reqid=1 duration="56.987µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - WARN [02-09|00:28:07.558] Served personal_ecRecover                reqid=2 duration="26.129µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - WARN [02-09|00:28:07.560] Served personal_ecRecover                reqid=3 duration="45.285µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - WARN [02-09|00:28:07.562] Served personal_ecRecover                reqid=4 duration="24.957µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - WARN [02-09|00:28:07.564] Served personal_ecRecover                reqid=5 duration="25.358µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - WARN [02-09|00:28:07.566] Served personal_ecRecover                reqid=6 duration="26.74µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - WARN [02-09|00:28:07.568] Served personal_ecRecover                reqid=7 duration="24.947µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - WARN [02-09|00:28:07.570] Served personal_ecRecover                reqid=8 duration="24.546µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [02-09|00:28:08.457] New local node record                    seq=1,739,060,883,421 id=d451981602357e13 ip=52.234.33.71 udp=44697 tcp=47048
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - 2025-02-09T00:28:08.740Z	INFO	0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130	status-cli/serve.go:107	retrieve messages...
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - WARN [02-09|00:28:08.751] Served personal_ecRecover                reqid=1 duration="71.844µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - WARN [02-09|00:28:08.759] Served personal_ecRecover                reqid=2 duration="41.498µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - WARN [02-09|00:28:08.760] Served personal_ecRecover                reqid=3 duration="23.915µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - WARN [02-09|00:28:08.763] Served personal_ecRecover                reqid=4 duration="28.764µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - WARN [02-09|00:28:09.584] Served personal_ecRecover                reqid=1 duration="60.303µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - WARN [02-09|00:28:09.586] Served personal_ecRecover                reqid=2 duration="32.13µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - WARN [02-09|00:28:09.588] Served personal_ecRecover                reqid=3 duration="27.862µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - WARN [02-09|00:28:09.589] Served personal_ecRecover                reqid=4 duration="25.448µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - WARN [02-09|00:28:09.591] Served personal_ecRecover                reqid=5 duration="27.421µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - WARN [02-09|00:28:09.593] Served personal_ecRecover                reqid=6 duration="25.188µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - WARN [02-09|00:28:09.594] Served personal_ecRecover                reqid=7 duration="24.476µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - WARN [02-09|00:28:09.596] Served personal_ecRecover                reqid=8 duration="27.662µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - WARN [02-09|00:28:09.746] Served personal_ecRecover                reqid=5 duration="41.948µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - WARN [02-09|00:28:09.748] Served personal_ecRecover                reqid=6 duration="25.177µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - WARN [02-09|00:28:09.752] Served personal_ecRecover                reqid=7 duration="25.417µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - WARN [02-09|00:28:09.754] Served personal_ecRecover                reqid=8 duration="24.405µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [02-09|00:28:10.398] New local node record                    seq=1,739,060,885,380 id=6e7a55992b8c2bdd ip=52.234.33.71 udp=57638 tcp=47050
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - 2025-02-09T00:28:10.589Z	INFO	0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139	status-cli/serve.go:107	retrieve messages...
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - WARN [02-09|00:28:10.619] Served personal_ecRecover                reqid=1 duration="51.076µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - WARN [02-09|00:28:10.621] Served personal_ecRecover                reqid=2 duration="22.762µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - WARN [02-09|00:28:10.623] Served personal_ecRecover                reqid=3 duration="21.771µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - WARN [02-09|00:28:10.624] Served personal_ecRecover                reqid=4 duration="16.852µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - WARN [02-09|00:28:10.626] Served personal_ecRecover                reqid=5 duration="19.967µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - WARN [02-09|00:28:10.627] Served personal_ecRecover                reqid=6 duration="25.137µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - WARN [02-09|00:28:10.629] Served personal_ecRecover                reqid=7 duration="23.194µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - WARN [02-09|00:28:10.631] Served personal_ecRecover                reqid=8 duration="36.007µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.steps.common:common.py:49 Entering context manager: add_packet_loss
[35mDEBUG   [0m src.node.rpc_client:rpc_client.py:21 Node: first_node sends request at address: http://127.0.0.1:7133 with payload: {"jsonrpc": "2.0", "method": "wakuext_fetchCommunity", "params": [{"communityKey": "0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c", "waitForResponse": true, "tryDatabase": true}], "id": 1}
[35mDEBUG   [0m src.node.rpc_client:rpc_client.py:25 Received response: {"jsonrpc":"2.0","id":1,"result":{"id":"0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c","memberRole":0,"isControlNode":false,"verified":false,"joined":false,"joinedAt":0,"spectated":false,"requestedAccessAt":0,"name":"vac_qa_community_2","description":"vac_qa_community_2","introMessage":"","outroMessage":"","tags":[],"chats":{"f7cbbc22-47ae-45fd-b4f5-8d645f5b4fb1":{"id":"f7cbbc22-47ae-45fd-b4f5-8d645f5b4fb1","name":"general","color":"#ffffff","emoji":"","description":"General channel for the community","members":null,"permissions":{"access":1},"canPost":false,"canView":false,"canPostReactions":false,"viewersCanPostReactions":false,"position":0,"categoryID":"","tokenGated":false,"hideIfPermissionsNotMet":false,"missingEncryptionKey":false}},"categories":{},"images":null,"permissions":{"access":3},"members":{"0x0404411a1eddc09847ff39f7f42c25f136b6266fca84105aaa851be9402c5ed4e89da072a9fc5ff93a942bf957728ff78731176e0b6cf677b6be8106bc2bc2bb09":{"last_update_clock":1738975190},"0x041389374bcaf9a1c36230942c58f4e3968c0a2472bfa9041916414f11d228a3b0605c6ede03ff65463fe8a22126d1f2c750991f03bdf352eeb6442611e2b87aa1":{"roles":[1]},"0x042041921e6700e2845e961fa3ad8795c171e4732441ba3a209f62dbc0e7757f62378b69b40597b04bb6af7fe11acf3d4f498235324ffbabdd9da28135c4d59942":{"last_update_clock":1738715842},"0x0434c77234eb3e0af9c79b1a791c8a9674415ae417c97928d10db853da42e631bf18630ee06c325f62a7745dafe64f1ae253db0be84a53f3dcb2319b7ad8e4c8a7":{"last_update_clock":1738888753},"0x043f646b2a47df708461057b97cc8b3a8999972ff51c78ce230f11dcf137ad20828af2338afe48a902c61aa9203ea470ee3827a7dbcbd9781fc3c131ef42054dba":{"last_update_clock":1738802301},"0x0457e28f604162ad4d896cd5b8ebd7ff92f8973a5d87cfe13c6a96427d7085bae166d4ce11d860f69612701bffb2f852155829e8fabfad2f644b075c707bbd6ade":{"last_update_clock":1738629416},"0x04848c19d86864e132b2c06e100d8bcd418c8b0eeb0c98b80cdc80dbec87c3cb222299ff4c5327f49bbf5aace880abb7903b2c38afc3cc81cf81d0c91eec46ce4e":{"last_update_clock":1738542981}},"canRequestAccess":true,"canManageUsers":false,"canDeleteMessageForEveryone":false,"canJoin":false,"color":"#ffffff","isMember":false,"muted":false,"muteTill":"0001-01-01T00:00:00Z","adminSettings":{"pinMessageAllMembersEnabled":false},"encrypted":false,"pendingAndBannedMembers":{},"tokenPermissions":{},"communityTokensMetadata":null,"activeMembersCount":0,"pubsubTopic":"","pubsubTopicKey":"","shard":null,"lastOpenedAt":0,"clock":1738975199575}}

[35mDEBUG   [0m src.node.rpc_client:rpc_client.py:21 Node: first_node sends request at address: http://127.0.0.1:7133 with payload: {"jsonrpc": "2.0", "method": "wakuext_fetchCommunity", "params": [{"communityKey": "0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e", "waitForResponse": true, "tryDatabase": true}], "id": 1}
[1m[31mERROR   [0m src.node.rpc_client:rpc_client.py:32 Request to http://127.0.0.1:7133 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node
[35mDEBUG   [0m src.node.rpc_client:rpc_client.py:21 Node: first_node sends request at address: http://127.0.0.1:7133 with payload: {"jsonrpc": "2.0", "method": "wakuext_fetchCommunity", "params": [{"communityKey": "0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e", "waitForResponse": true, "tryDatabase": true}], "id": 1}
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [02-09|00:28:24.376] New local node record                    seq=1,739,060,879,357 id=a00cb648b5eaf0f5 ip=52.234.33.71 udp=35907 tcp=47046
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [02-09|00:28:26.537] New local node record                    seq=1,739,060,861,518 id=f09b89011ceb0d61 ip=10.1.0.85 udp=35883 tcp=33769
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [02-09|00:28:29.377] New local node record                    seq=1,739,060,879,358 id=a00cb648b5eaf0f5 ip=52.234.33.71 udp=35907 tcp=47046
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [02-09|00:28:31.366] New local node record                    seq=1,739,060,871,353 id=52c72216517240a7 ip=52.234.33.71 udp=54876 tcp=47042
[1m[31mERROR   [0m src.node.rpc_client:rpc_client.py:32 Request to http://127.0.0.1:7133 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node
[35mDEBUG   [0m src.node.rpc_client:rpc_client.py:21 Node: first_node sends request at address: http://127.0.0.1:7133 with payload: {"jsonrpc": "2.0", "method": "wakuext_fetchCommunity", "params": [{"communityKey": "0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e", "waitForResponse": true, "tryDatabase": true}], "id": 1}
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - WARN [02-09|00:28:36.687] Served personal_ecRecover                reqid=1 duration="65.012µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - WARN [02-09|00:28:36.688] Served personal_ecRecover                reqid=2 duration="23.414µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - WARN [02-09|00:28:36.690] Served personal_ecRecover                reqid=3 duration="22.312µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - WARN [02-09|00:28:36.691] Served personal_ecRecover                reqid=4 duration="21.67µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - WARN [02-09|00:28:36.692] Served personal_ecRecover                reqid=5 duration="21.47µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - WARN [02-09|00:28:36.694] Served personal_ecRecover                reqid=6 duration="21.54µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - WARN [02-09|00:28:36.695] Served personal_ecRecover                reqid=7 duration="19.316µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - WARN [02-09|00:28:36.696] Served personal_ecRecover                reqid=8 duration="27.02µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [02-09|00:28:39.376] New local node record                    seq=1,739,060,879,359 id=a00cb648b5eaf0f5 ip=52.234.33.71 udp=35907 tcp=47046
[1m[31mERROR   [0m src.node.rpc_client:rpc_client.py:32 Request to http://127.0.0.1:7133 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node
[35mDEBUG   [0m src.steps.common:common.py:54 Exiting context manager: add_packet_loss
[35mDEBUG   [0m tests.conftest:conftest.py:42 Running fixture teardown: save_node_logs_on_fail
[35mDEBUG   [0m tests.conftest:conftest.py:45 Test failed, attempting to rename and move logs to the test_results folder
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file first_node.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_first_node.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132.log to test_results/testfetchcommunity_test_fetch_community_with_packet_loss_0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132.log
[35mDEBUG   [0m tests.conftest:conftest.py:62 Running fixture teardown: clear_open_nodes
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: first_node
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139