[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: start_1_node
[32mINFO    [0m src.node.status_node:status_node.py:39 Starting node with command: ['./status-cli', 'serve', '-n', 'first_node', '-p', '32663']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025-03-04T00:42:44.183Z	INFO	status-cli/serve.go:34	Running serve command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -name first_node
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -port 32663
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -light false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -api-modules waku,wakuext,wakuv2,permissions,eth
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -telemetry-server-url
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -fleet status.staging
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025-03-04T00:42:44.183Z	INFO	first_node	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [03-04|00:42:46.486] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.22.3
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [03-04|00:42:46.492] New local node record                    seq=1,741,048,966,491 id=b855da46f4d0e09d ip=127.0.0.1 udp=0 tcp=42333
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [03-04|00:42:46.492] Started P2P networking                   self="enode://07044e87af69639e2b0f201d73c9dc67b996a2946ccdde95ccdf01c744a95b4a4b25bd0ae1947bc24d20e04da1033f3003400ed42aab23e299d0d2ab6f13ffff@127.0.0.1:42333?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - ERROR[03-04|00:42:46.493] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [03-04|00:42:46.494] HTTP server started                      endpoint=127.0.0.1:32663 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [03-04|00:42:46.517] New local node record                    seq=1,741,048,966,497 id=fbe0f0d3f467c024 ip=10.1.0.163 udp=43917 tcp=38579
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [03-04|00:42:46.523] New local node record                    seq=1,741,048,966,498 id=fbe0f0d3f467c024 ip=10.1.0.163 udp=43917 tcp=38579
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025-03-04T00:42:46.997Z	INFO	first_node	status-cli/util.go:68	account created, key UID: 0x00cf2170ab09a6074307c7b429c271a78c9034a970591fc1d0ea1f9623bd08bb
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [03-04|00:42:46.997] New local node record                    seq=1,741,048,966,499 id=fbe0f0d3f467c024 ip=10.1.0.163 udp=43917 tcp=38579
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025-03-04T00:42:47.025Z	INFO	first_node	status-cli/util.go:93	messenger started, public key: 0x046b2ca344bf7648fe338ce883fe8744f33bbf6fed3640fbdd2092e54de1875c65b2055b5d4b9895e79b3ea71a4cc0740075194e77dad477b9bbf34c3fab1063fa
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - 2025-03-04T00:42:52.025Z	INFO	first_node	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135', '-kid', '0x5991c117b01d9f460b63cae2ec74abb9afd2b85661af889425db7acf2047c393']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - 2025-03-04T00:42:52.305Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - -name 0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - -key-uid 0x5991c117b01d9f460b63cae2ec74abb9afd2b85661af889425db7acf2047c393
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - 2025-03-04T00:42:52.305Z	INFO	0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [03-04|00:42:52.342] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.22.3
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - ERROR[03-04|00:42:52.349] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [03-04|00:42:52.349] New local node record                    seq=1,737,419,614,800 id=3120ffa1600d036e ip=127.0.0.1 udp=0 tcp=33713
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [03-04|00:42:52.349] Started P2P networking                   self="enode://1eee99e98b47a050566c4564713970fad84b9429798d00aea57ad2415987c1634a030183bee393717b626509c0bb811572a545295a0a6affb26c297bb7a1fbf9@127.0.0.1:33713?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [03-04|00:42:52.350] HTTP server started                      endpoint=127.0.0.1:6135 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [03-04|00:42:52.379] New local node record                    seq=1,741,048,972,361 id=9d60355aa0b08986 ip=10.1.0.163 udp=0 tcp=44429
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [03-04|00:42:52.381] New local node record                    seq=1,741,048,972,362 id=9d60355aa0b08986 ip=10.1.0.163 udp=47338 tcp=44429
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [03-04|00:42:52.385] New local node record                    seq=1,741,048,972,363 id=9d60355aa0b08986 ip=10.1.0.163 udp=47338 tcp=44429
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - 2025-03-04T00:42:52.526Z	INFO	0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135	status-cli/util.go:62	existing account, key UID: 0x5991c117b01d9f460b63cae2ec74abb9afd2b85661af889425db7acf2047c393
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [03-04|00:42:52.528] New local node record                    seq=1,741,048,972,364 id=9d60355aa0b08986 ip=10.1.0.163 udp=47338 tcp=44429
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - 2025-03-04T00:42:52.545Z	INFO	0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135	status-cli/util.go:93	messenger started, public key: 0x04890fe10a90ba0a415f5f05e7becd52b45f8f4c7c38236a549036dde17457d50811ab1bfb1b3144b4f859a3c323542ff810a716ef579e51035298bc110536cb3c
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139', '-kid', '0x98806521a617d0fb4d2140c292e22157c3d3197b212f81cd0a3bf164774580f0']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - 2025-03-04T00:42:54.304Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - -name 0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - -key-uid 0x98806521a617d0fb4d2140c292e22157c3d3197b212f81cd0a3bf164774580f0
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - 2025-03-04T00:42:54.304Z	INFO	0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [03-04|00:42:54.344] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.22.3
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [03-04|00:42:54.351] New local node record                    seq=1,737,419,651,311 id=acb6477d150fec3c ip=127.0.0.1 udp=0 tcp=36371
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - ERROR[03-04|00:42:54.351] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [03-04|00:42:54.351] Started P2P networking                   self="enode://437d152e7e8c57d86065f0879910c1f64ae6e14f007b9dc5b5c671ecfb463b66da4ffe7a8753f396f6232e58841a36808d6b65b1c05fb2a3aa9d8ed97ef447e0@127.0.0.1:36371?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [03-04|00:42:54.352] HTTP server started                      endpoint=127.0.0.1:6139 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [03-04|00:42:54.379] New local node record                    seq=1,741,048,974,363 id=a825b9962a64d458 ip=10.1.0.163 udp=0 tcp=44281
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [03-04|00:42:54.382] New local node record                    seq=1,741,048,974,364 id=a825b9962a64d458 ip=10.1.0.163 udp=47146 tcp=44281
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [03-04|00:42:54.383] New local node record                    seq=1,741,048,974,365 id=a825b9962a64d458 ip=10.1.0.163 udp=47146 tcp=44281
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - 2025-03-04T00:42:54.523Z	INFO	0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139	status-cli/util.go:62	existing account, key UID: 0x98806521a617d0fb4d2140c292e22157c3d3197b212f81cd0a3bf164774580f0
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [03-04|00:42:54.523] New local node record                    seq=1,741,048,974,366 id=a825b9962a64d458 ip=10.1.0.163 udp=47146 tcp=44281
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - 2025-03-04T00:42:54.542Z	INFO	0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139	status-cli/util.go:93	messenger started, public key: 0x040d9cf92cec5a7f9e887525cd79bfc4a927af9e1ce7c4d89246d974613d6ea084c360b2bd11007d57e296de08a6fb0dd0d813d28e57cf5f797745241ddabdd973
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132', '-kid', '0x317d1096e362af7561ea2f494e3cf3f715137ba7da24d801eea4ac7e10895318']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - 2025-03-04T00:42:56.304Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - -name 0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - -key-uid 0x317d1096e362af7561ea2f494e3cf3f715137ba7da24d801eea4ac7e10895318
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - 2025-03-04T00:42:56.304Z	INFO	0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [03-04|00:42:56.342] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.22.3
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [03-04|00:42:56.350] New local node record                    seq=1,737,419,587,417 id=a3e6d7f2cfadb3c4 ip=127.0.0.1 udp=0 tcp=46089
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [03-04|00:42:56.350] Started P2P networking                   self="enode://aad0dc447a381566b4aa3dc121ad9ba5674e454f820fcda769e16c748042a1e278d4c98d22a4e518f933d8135d897befd8ecfe65c0f92930c9606e794e24e381@127.0.0.1:46089?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - ERROR[03-04|00:42:56.351] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [03-04|00:42:56.351] HTTP server started                      endpoint=127.0.0.1:6132 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [03-04|00:42:56.383] New local node record                    seq=1,741,048,976,361 id=78bd73a613c927b7 ip=10.1.0.163 udp=49045 tcp=41737
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [03-04|00:42:56.385] New local node record                    seq=1,741,048,976,362 id=78bd73a613c927b7 ip=10.1.0.163 udp=49045 tcp=41737
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - 2025-03-04T00:42:56.520Z	INFO	0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132	status-cli/util.go:62	existing account, key UID: 0x317d1096e362af7561ea2f494e3cf3f715137ba7da24d801eea4ac7e10895318
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [03-04|00:42:56.522] New local node record                    seq=1,741,048,976,363 id=78bd73a613c927b7 ip=10.1.0.163 udp=49045 tcp=41737
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - 2025-03-04T00:42:56.542Z	INFO	0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132	status-cli/util.go:93	messenger started, public key: 0x041389374bcaf9a1c36230942c58f4e3968c0a2472bfa9041916414f11d228a3b0605c6ede03ff65463fe8a22126d1f2c750991f03bdf352eeb6442611e2b87aa1
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [03-04|00:42:57.377] New local node record                    seq=1,741,048,972,365 id=9d60355aa0b08986 ip=20.161.78.223 udp=47338 tcp=4226
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - 2025-03-04T00:42:57.545Z	INFO	0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130', '-kid', '0xd8d0a6ec6b7198cb0217115fd766fab8ff146a351ef79446c2dec6d7dbf7a007']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - 2025-03-04T00:42:58.310Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - -name 0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - -key-uid 0xd8d0a6ec6b7198cb0217115fd766fab8ff146a351ef79446c2dec6d7dbf7a007
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - 2025-03-04T00:42:58.311Z	INFO	0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [03-04|00:42:58.353] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.22.3
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - ERROR[03-04|00:42:58.359] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [03-04|00:42:58.359] New local node record                    seq=1,737,419,564,795 id=21e155c21669159a ip=127.0.0.1 udp=0 tcp=44543
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [03-04|00:42:58.359] Started P2P networking                   self="enode://3adb140cde1eb80c72ac2a83452dabbd2d236498950c66e2194aba96737679facd1c9dc1ec9a7a2052df0b0b89ad1b038868776452403d573e8f3551b0e26fbc@127.0.0.1:44543?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [03-04|00:42:58.359] HTTP server started                      endpoint=127.0.0.1:6130 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [03-04|00:42:58.394] New local node record                    seq=1,741,048,978,370 id=e0b3a71556493098 ip=10.1.0.163 udp=0 tcp=41951
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [03-04|00:42:58.395] New local node record                    seq=1,741,048,978,371 id=e0b3a71556493098 ip=10.1.0.163 udp=53581 tcp=41951
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [03-04|00:42:58.397] New local node record                    seq=1,741,048,978,372 id=e0b3a71556493098 ip=10.1.0.163 udp=53581 tcp=41951
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - 2025-03-04T00:42:58.541Z	INFO	0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130	status-cli/util.go:62	existing account, key UID: 0xd8d0a6ec6b7198cb0217115fd766fab8ff146a351ef79446c2dec6d7dbf7a007
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [03-04|00:42:58.541] New local node record                    seq=1,741,048,978,373 id=e0b3a71556493098 ip=10.1.0.163 udp=53581 tcp=41951
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - 2025-03-04T00:42:58.562Z	INFO	0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130	status-cli/util.go:93	messenger started, public key: 0x04c61f8fa3515a136d6a0860b6cdb68ecd4b2d8df3f494a1b628b5f159c8168eb431422a84d88654a8bcffcccf7130e656351c12b7f31eb621de6d944d9c62b38d
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - 2025-03-04T00:42:59.542Z	INFO	0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136', '-kid', '0x81bb8c3cf7199471bd4b3dda97fca44a8d2a482f9cda5e413efb11fa68db3f52']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - 2025-03-04T00:43:00.310Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - -name 0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - -key-uid 0x81bb8c3cf7199471bd4b3dda97fca44a8d2a482f9cda5e413efb11fa68db3f52
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - 2025-03-04T00:43:00.310Z	INFO	0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [03-04|00:43:00.349] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.22.3
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [03-04|00:43:00.358] New local node record                    seq=1,737,419,623,946 id=877b25ac259fbb61 ip=127.0.0.1 udp=0 tcp=41489
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [03-04|00:43:00.358] Started P2P networking                   self="enode://3c43eceef4f4dee8fd369a60b6400d45eefc85a84579959675a0d624fbbe868f4dbc522c79a78bf55c7844278981e3bd2bbe4ed39727170d2035215ea236eb0c@127.0.0.1:41489?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - ERROR[03-04|00:43:00.360] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [03-04|00:43:00.361] HTTP server started                      endpoint=127.0.0.1:6136 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [03-04|00:43:00.388] New local node record                    seq=1,741,048,980,364 id=cdddce8ac1ed8cb7 ip=10.1.0.163 udp=0 tcp=38837
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [03-04|00:43:00.389] New local node record                    seq=1,741,048,980,365 id=cdddce8ac1ed8cb7 ip=10.1.0.163 udp=57816 tcp=38837
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [03-04|00:43:00.391] New local node record                    seq=1,741,048,980,366 id=cdddce8ac1ed8cb7 ip=10.1.0.163 udp=57816 tcp=38837
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - 2025-03-04T00:43:00.537Z	INFO	0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136	status-cli/util.go:62	existing account, key UID: 0x81bb8c3cf7199471bd4b3dda97fca44a8d2a482f9cda5e413efb11fa68db3f52
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [03-04|00:43:00.538] New local node record                    seq=1,741,048,980,367 id=cdddce8ac1ed8cb7 ip=10.1.0.163 udp=57816 tcp=38837
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - 2025-03-04T00:43:00.558Z	INFO	0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136	status-cli/util.go:93	messenger started, public key: 0x042898fe963497a6d5cdf4bae695090aae18993c81f12e39be2b51b3980b806fa22fd3688e25d44663ce4c02010d7d8856c7bff8c610d1c0d3be4f2d1187426bfe
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [03-04|00:43:01.514] New local node record                    seq=1,741,048,966,500 id=fbe0f0d3f467c024 ip=20.161.78.223 udp=43917 tcp=4227
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - 2025-03-04T00:43:01.542Z	INFO	0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134', '-kid', '0xc74a6694789777559695ac9bf06c43cc94c5d4dd1cbd3c1d3eaabe55410855c4']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - 2025-03-04T00:43:02.310Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - -name 0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - -key-uid 0xc74a6694789777559695ac9bf06c43cc94c5d4dd1cbd3c1d3eaabe55410855c4
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - 2025-03-04T00:43:02.310Z	INFO	0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [03-04|00:43:02.353] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.22.3
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [03-04|00:43:02.360] New local node record                    seq=1,737,419,605,674 id=1e19dde297f8874d ip=127.0.0.1 udp=0 tcp=34047
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [03-04|00:43:02.360] Started P2P networking                   self="enode://99a2b3d7a793500a85f73e4baddc4643c65467df907e6eb7d569a6434b36f4a3255fc0d41038ce07a88508f57eb8e3613c00a996639de8c6b65ea83232116fd0@127.0.0.1:34047?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - ERROR[03-04|00:43:02.360] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [03-04|00:43:02.361] HTTP server started                      endpoint=127.0.0.1:6134 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - INFO [03-04|00:43:02.377] New local node record                    seq=1,741,048,972,366 id=9d60355aa0b08986 ip=20.161.78.223 udp=47338 tcp=4224
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [03-04|00:43:02.396] New local node record                    seq=1,741,048,982,375 id=d8b19fc97290df15 ip=10.1.0.163 udp=0 tcp=39879
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [03-04|00:43:02.398] New local node record                    seq=1,741,048,982,376 id=d8b19fc97290df15 ip=10.1.0.163 udp=59269 tcp=39879
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [03-04|00:43:02.400] New local node record                    seq=1,741,048,982,377 id=d8b19fc97290df15 ip=10.1.0.163 udp=59269 tcp=39879
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - 2025-03-04T00:43:02.547Z	INFO	0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134	status-cli/util.go:62	existing account, key UID: 0xc74a6694789777559695ac9bf06c43cc94c5d4dd1cbd3c1d3eaabe55410855c4
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [03-04|00:43:02.548] New local node record                    seq=1,741,048,982,378 id=d8b19fc97290df15 ip=10.1.0.163 udp=59269 tcp=39879
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - 2025-03-04T00:43:02.572Z	INFO	0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134	status-cli/util.go:93	messenger started, public key: 0x044da57de11adc9391ad5ca1677b0ff2da9e02f50f2184d27852966cb46e21a0759e1e0af6514a5d60dbec05dda5ab574f265a71a340caa3f98c92f9091f927a6d
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - 2025-03-04T00:43:03.562Z	INFO	0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131', '-kid', '0xe171a00735b54dcf9ecb7a27904fdd4b143362df5354c1e469753d5f08023459']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - 2025-03-04T00:43:04.316Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - -name 0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - -key-uid 0xe171a00735b54dcf9ecb7a27904fdd4b143362df5354c1e469753d5f08023459
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - 2025-03-04T00:43:04.316Z	INFO	0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [03-04|00:43:04.360] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.22.3
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - ERROR[03-04|00:43:04.366] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [03-04|00:43:04.366] New local node record                    seq=1,737,419,578,301 id=91b1bc7236045679 ip=127.0.0.1 udp=0 tcp=33761
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [03-04|00:43:04.366] Started P2P networking                   self="enode://91d8c4c0322908732547f0a21fe21a53e4a636758e1615a385e922f834ad499c271c69dcee9a8fefe3c7479c1584e71ead9adf547235b9547d0349db0b06bee9@127.0.0.1:33761?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [03-04|00:43:04.367] HTTP server started                      endpoint=127.0.0.1:6131 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [03-04|00:43:04.401] New local node record                    seq=1,741,048,984,379 id=019fd0704f1fab75 ip=10.1.0.163 udp=0 tcp=37729
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [03-04|00:43:04.403] New local node record                    seq=1,741,048,984,380 id=019fd0704f1fab75 ip=10.1.0.163 udp=51454 tcp=37729
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [03-04|00:43:04.404] New local node record                    seq=1,741,048,984,381 id=019fd0704f1fab75 ip=10.1.0.163 udp=51454 tcp=37729
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - 2025-03-04T00:43:04.561Z	INFO	0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131	status-cli/util.go:62	existing account, key UID: 0xe171a00735b54dcf9ecb7a27904fdd4b143362df5354c1e469753d5f08023459
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - INFO [03-04|00:43:04.562] New local node record                    seq=1,741,048,984,382 id=019fd0704f1fab75 ip=10.1.0.163 udp=51454 tcp=37729
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - 2025-03-04T00:43:04.588Z	INFO	0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131	status-cli/util.go:93	messenger started, public key: 0x047171e21124210e88fa7e404355815ceac9793d65706770d642813fdfaacc4e0def04dd42a5be6f28ef68d9e76a297cb7f6fe0326d50547faffaffbaf0fd1a662
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - 2025-03-04T00:43:05.558Z	INFO	0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138', '-kid', '0x1226dcff3cb70a51c0f10a4a47de02a888068b914e654e5626095edc6edf1707']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-03-04T00:43:06.329Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - -name 0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - -key-uid 0x1226dcff3cb70a51c0f10a4a47de02a888068b914e654e5626095edc6edf1707
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-03-04T00:43:06.330Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [03-04|00:43:06.374] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.22.3
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - ERROR[03-04|00:43:06.379] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [03-04|00:43:06.379] New local node record                    seq=1,737,419,642,180 id=e3228c0ebd0ad048 ip=127.0.0.1 udp=0 tcp=37601
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [03-04|00:43:06.379] Started P2P networking                   self="enode://e1e8dc76505064a0cd4888bcc75868421543cdfbbcdbe271fd2f512ec4e0013e1e8829edf9dfcf895198aad4056c5e9c238c1c63eab627cfd4fa85b5908c1664@127.0.0.1:37601?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [03-04|00:43:06.380] HTTP server started                      endpoint=127.0.0.1:6138 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [03-04|00:43:06.416] New local node record                    seq=1,741,048,986,391 id=3eccf2f897ee958e ip=10.1.0.163 udp=47863 tcp=34923
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [03-04|00:43:06.424] New local node record                    seq=1,741,048,986,392 id=3eccf2f897ee958e ip=10.1.0.163 udp=47863 tcp=34923
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-03-04T00:43:06.580Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/util.go:62	existing account, key UID: 0x1226dcff3cb70a51c0f10a4a47de02a888068b914e654e5626095edc6edf1707
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [03-04|00:43:06.583] New local node record                    seq=1,741,048,986,393 id=3eccf2f897ee958e ip=10.1.0.163 udp=47863 tcp=34923
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-03-04T00:43:06.608Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/util.go:93	messenger started, public key: 0x04c05ffc7fbe973116e8a7017bbd49632c7aaa31715924eb62497ce229bd52a6ffe6904b99dd534f66d4b1364770dce92fcc97a901a1adb98dbebddaf6bd876eb6
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - 2025-03-04T00:43:07.573Z	INFO	0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133', '-kid', '0xa9461a9f60364bb61116eabe5cc9b95fd07f7c283d742e3ad11dfd6dbe9b5d89']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-03-04T00:43:08.319Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - -name 0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - -key-uid 0xa9461a9f60364bb61116eabe5cc9b95fd07f7c283d742e3ad11dfd6dbe9b5d89
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-03-04T00:43:08.319Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [03-04|00:43:08.363] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.22.3
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [03-04|00:43:08.371] New local node record                    seq=1,737,419,596,535 id=ceb3ac46208d5874 ip=127.0.0.1 udp=0 tcp=36067
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [03-04|00:43:08.371] Started P2P networking                   self="enode://258928b145e8e2cfa71d9f79b1c6107f8a42182ee831449209e212c28895554f9555253596f26c14c2f2aebc9bab14e51fea9341444f9f3da43e3fb66230428b@127.0.0.1:36067?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - ERROR[03-04|00:43:08.373] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [03-04|00:43:08.373] HTTP server started                      endpoint=127.0.0.1:6133 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [03-04|00:43:08.401] New local node record                    seq=1,741,048,988,377 id=18705cfa74b550d7 ip=10.1.0.163 udp=0 tcp=34443
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [03-04|00:43:08.402] New local node record                    seq=1,741,048,988,378 id=18705cfa74b550d7 ip=10.1.0.163 udp=34310 tcp=34443
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [03-04|00:43:08.406] New local node record                    seq=1,741,048,988,379 id=18705cfa74b550d7 ip=10.1.0.163 udp=34310 tcp=34443
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-03-04T00:43:08.563Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/util.go:62	existing account, key UID: 0xa9461a9f60364bb61116eabe5cc9b95fd07f7c283d742e3ad11dfd6dbe9b5d89
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - INFO [03-04|00:43:08.564] New local node record                    seq=1,741,048,988,380 id=18705cfa74b550d7 ip=10.1.0.163 udp=34310 tcp=34443
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-03-04T00:43:08.593Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/util.go:93	messenger started, public key: 0x040da8af244c48efedcce3e6d3c3ff3fa0059e8f99a00ee714878a2bd4596de3ce1a5d9869df28bd689db33753d4b39223a1a5d78d16b123c27c2c4d23a9e72f3e
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [03-04|00:43:09.376] New local node record                    seq=1,741,048,974,367 id=a825b9962a64d458 ip=20.161.78.223 udp=47146 tcp=4224
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X036DDC1C91806EEFCFBD8EB1ACCADC7EFF82D79F1FED6E8FCCD08F9CF737D02C1F_6131 - 2025-03-04T00:43:09.589Z	INFO	0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131	status-cli/serve.go:107	retrieve messages...
[32mINFO    [0m src.node.status_node:status_node.py:52 Serving node with command: ['./status-cli', 'serve-account', '-n', '0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137', '-kid', '0x19f84f473f249eb2a536e729d1f2c0efd07cf8c214901a0faa4d83f2e71ece36']
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 2 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-03-04T00:43:10.326Z	INFO	status-cli/serve.go:34	Running serve-account command, with:
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - -name 0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - -key-uid 0x19f84f473f249eb2a536e729d1f2c0efd07cf8c214901a0faa4d83f2e71ece36
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - -interactive false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - -add
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - -debug false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - -help false
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-03-04T00:43:10.326Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/util.go:55	starting messenger
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [03-04|00:43:10.378] Starting peer-to-peer node               instance=StatusIM/linux-amd64/go1.22.3
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - ERROR[03-04|00:43:10.384] Unavailable modules in HTTP API list     unavailable=[wakuv2] available="[admin debug web3 eth rpcstats appmetrics appgeneral peer personal status pending ens communitytokens stickers updates settings accounts multiaccounts browsers permissions mailservers gif chat wallet waku wakuext localnotifications]"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [03-04|00:43:10.384] New local node record                    seq=1,737,419,633,056 id=4d486e8dbc7eb7b6 ip=127.0.0.1 udp=0 tcp=35293
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [03-04|00:43:10.384] Started P2P networking                   self="enode://88fdc7f7abca4ed0a72cfac7bbeb5ff6e6aeeb5dc2f2baf3f0e4dc9c1a9781862fa1544e09a59c772ded4335d9dbb9bc1e53eace961ebeb40bc9456f10dafa8f@127.0.0.1:35293?discport=0"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [03-04|00:43:10.385] HTTP server started                      endpoint=127.0.0.1:6137 auth=false prefix= cors= vhosts=
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [03-04|00:43:10.413] New local node record                    seq=1,741,048,990,391 id=cd24a227b2197482 ip=10.1.0.163 udp=57510 tcp=42103
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [03-04|00:43:10.415] New local node record                    seq=1,741,048,990,392 id=cd24a227b2197482 ip=10.1.0.163 udp=57510 tcp=42103
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-03-04T00:43:10.576Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/util.go:62	existing account, key UID: 0x19f84f473f249eb2a536e729d1f2c0efd07cf8c214901a0faa4d83f2e71ece36
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - INFO [03-04|00:43:10.577] New local node record                    seq=1,741,048,990,393 id=cd24a227b2197482 ip=10.1.0.163 udp=57510 tcp=42103
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-03-04T00:43:10.605Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/util.go:93	messenger started, public key: 0x04f4a3da8d5133481b6c157534cf62275127bb04b5f4dd1fde013c583a2708bc40001ecc2ffbf4edcc4f03aab32c3f76de8ff673dc40d690ccda6d9dea3ada4f6c
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-03-04T00:43:11.608Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/serve.go:107	retrieve messages...
[35mDEBUG   [0m src.libs.common:common.py:15 Sleeping for 4 seconds
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X03084787B0EB1391FD622FDA8FEE5F9FDA3571467EE2C4DBCCE9D10E4CB50442AD_6133 - 2025-03-04T00:43:13.594Z	INFO	0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133	status-cli/serve.go:107	retrieve messages...
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02C805D0BC6C60EAE2DF62A9780B0B46B75301283075057ECDC677A2DC7A3CBFE1_6139 - INFO [03-04|00:43:14.376] New local node record                    seq=1,741,048,974,368 id=a825b9962a64d458 ip=20.161.78.223 udp=47146 tcp=4224
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [03-04|00:43:15.381] New local node record                    seq=1,741,048,980,368 id=cdddce8ac1ed8cb7 ip=20.161.78.223 udp=57816 tcp=4228
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X035CD90EF0ACDD7CA1173984B56C36A1D9A0119D00F787C3B99BC9705B6D394094_6137 - 2025-03-04T00:43:15.606Z	INFO	0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137	status-cli/serve.go:107	retrieve messages...
[35mDEBUG   [0m src.node.rpc_client:rpc_client.py:21 Node: first_node sends request at address: http://127.0.0.1:32663 with payload: {"jsonrpc": "2.0", "method": "wakuext_fetchCommunity", "params": [{"communityKey": "0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43", "waitForResponse": true, "tryDatabase": true}], "id": 1}
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [03-04|00:43:20.382] New local node record                    seq=1,741,048,980,369 id=cdddce8ac1ed8cb7 ip=20.161.78.223 udp=57816 tcp=4228
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - WARN [03-04|00:43:23.549] Served personal_ecRecover                reqid=1 duration="57.898µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - WARN [03-04|00:43:23.551] Served personal_ecRecover                reqid=2 duration="31.759µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02D815E00131E404D7DE053208ED6DB77A996403243C52BF8B20922A5E947BBD43_6135 - WARN [03-04|00:43:23.561] Served personal_ecRecover                reqid=3 duration="29.054µs" err="signature must be 65 bytes long"
[31m[1mERROR   [0m src.node.rpc_client:rpc_client.py:32 Request to http://127.0.0.1:32663 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node
[35mDEBUG   [0m src.node.rpc_client:rpc_client.py:21 Node: first_node sends request at address: http://127.0.0.1:32663 with payload: {"jsonrpc": "2.0", "method": "wakuext_fetchCommunity", "params": [{"communityKey": "0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43", "waitForResponse": true, "tryDatabase": true}], "id": 1}
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02E2DAF7144BE6E5FEF22E6EA21F04302A51CBA97EBE58C010478D8EAC1AEE62C6_6134 - INFO [03-04|00:43:27.393] New local node record                    seq=1,741,048,982,379 id=d8b19fc97290df15 ip=20.161.78.223 udp=59269 tcp=4231
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [03-04|00:43:31.514] New local node record                    seq=1,741,048,966,501 id=fbe0f0d3f467c024 ip=10.1.0.163 udp=43917 tcp=38579
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [03-04|00:43:31.581] New local node record                    seq=1,741,048,966,502 id=fbe0f0d3f467c024 ip=10.1.0.163 udp=43917 tcp=38579
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-03-04T00:43:31.716Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/serve.go:70	message received: 7031b63c-5da3-4119-a08b-2986228e99c5_message_from_0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138_24 (ID=0xe72c3b9ceed50f10fe93bf316dd771e76ce319fbac2d0e29d72fec1be8e95387)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-03-04T00:43:31.716Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/serve.go:70	message received: 1c6ce413-e332-4528-bcac-77e25950288b_message_from_0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138_22 (ID=0x8f13e62b427328aaf169339b2093f1f35bff5b568677bc82a657481437dcc6b8)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-03-04T00:43:31.716Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/serve.go:70	message received: 35aa3f49-31eb-493d-a70a-9cb8f9d44d85_message_from_0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138_20 (ID=0xac4b29b9c5c1988d2a816eba356db21be3f2fd1939a68ade3efa7af4fece2c46)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-03-04T00:43:31.716Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/serve.go:70	message received: c2b45888-9a78-403a-baaf-adffb55b0cd3_message_from_0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138_18 (ID=0x921bfab2dc4e8919a2cc5a0b2d0e209a0c469ea6c32531fff245f26743dc119f)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - WARN [03-04|00:43:32.668] Served personal_ecRecover                reqid=1 duration="61.394µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - WARN [03-04|00:43:32.670] Served personal_ecRecover                reqid=2 duration="24.095µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - WARN [03-04|00:43:32.672] Served personal_ecRecover                reqid=3 duration="27.391µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - WARN [03-04|00:43:32.674] Served personal_ecRecover                reqid=4 duration="23.003µs" err="signature must be 65 bytes long"
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-03-04T00:43:32.686Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/serve.go:70	message received: 697c6605-96da-4dfb-9abe-74d0bbba3ae4_message_from_0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138_8 (ID=0x74b1f0b5e49737eebd5355f7c3da5e7d62d3af5e4d89c4b89cdcb3e7622ea2c5)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-03-04T00:43:32.686Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/serve.go:70	message received: b195669e-f1d6-4098-a2db-27edaa095e7e_message_from_0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138_2 (ID=0x2fbcf5f1574d2097abc2e777396fb4e4a39980176214ee0755012c054bf6fe66)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-03-04T00:43:32.686Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/serve.go:70	message received: fa0bb6c7-9e5e-43e7-8f84-bf79ad7dae97_message_from_0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138_14 (ID=0xae5d0b8a92f89056a0ceff1caa0ada9f1b9d04c4197d6d5becbbffaab2888a05)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-03-04T00:43:32.686Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/serve.go:70	message received: 0070f1a8-6572-4661-8dfd-8448c158f180_message_from_0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138_12 (ID=0x1106f79d2c71cd4bcb6f9cf391befc09654a5cff288d097bf2165c6ea3073b00)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-03-04T00:43:32.686Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/serve.go:70	message received: cf02584b-ed8e-4d22-8b37-2e944d93ebd9_message_from_0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138_6 (ID=0xf7db8f040967f42e9b7f990b286c06ffbf394093b0e449be2f230a678b0d58d5)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-03-04T00:43:32.686Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/serve.go:70	message received: 337749d5-51f0-443c-88a7-1adf1ea08f6a_message_from_0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138_4 (ID=0xe7550593ea220c80e6fb30df5ca4b93a9856c5dec01ebbd35c16d7955bb2e124)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-03-04T00:43:32.686Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/serve.go:70	message received: ce2c2f39-2aa6-4e26-ae7a-c24873026e60_message_from_0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138_0 (ID=0xbae9498c07a9274ce2e19006d3ecb1b127c2888628cdfb583636b496ba4f3f7b)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-03-04T00:43:32.686Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/serve.go:70	message received: 2143d678-9e2f-47d6-9770-b5c7a0e4c575_message_from_0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138_16 (ID=0x5232d9dc5680f694910e7662e07bc932fd972e8ee3c0da74b38f42e88473cfea)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - 2025-03-04T00:43:32.686Z	INFO	0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138	status-cli/serve.go:70	message received: 6999b4ff-954c-4e7b-a7df-68a6d029326e_message_from_0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138_10 (ID=0x2ae649c7755d9d75df7bc6b689e06b6019779837907f4eec665686e0b4bb8e07)
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02CBC80D3F2C70DE89BC14DF08CD90AF4D038A1AC46CA994A1C1DBAFEFF4BD46B2_6130 - INFO [03-04|00:43:33.390] New local node record                    seq=1,741,048,978,374 id=e0b3a71556493098 ip=20.161.78.223 udp=53581 tcp=4230
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [03-04|00:43:35.502] New local node record                    seq=1,741,048,966,503 id=fbe0f0d3f467c024 ip=10.1.0.163 udp=43917 tcp=38579
[35mDEBUG   [0m src.node.status_node:status_node.py:65 FIRST_NODE - INFO [03-04|00:43:35.504] New local node record                    seq=1,741,048,966,504 id=fbe0f0d3f467c024 ip=10.1.0.163 udp=43917 tcp=38579
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [03-04|00:43:35.927] New local node record                    seq=1,741,048,976,364 id=78bd73a613c927b7 ip=10.1.0.163 udp=49045 tcp=41737
[31m[1mERROR   [0m src.node.rpc_client:rpc_client.py:32 Request to http://127.0.0.1:32663 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node
[35mDEBUG   [0m src.node.rpc_client:rpc_client.py:21 Node: first_node sends request at address: http://127.0.0.1:32663 with payload: {"jsonrpc": "2.0", "method": "wakuext_fetchCommunity", "params": [{"communityKey": "0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43", "waitForResponse": true, "tryDatabase": true}], "id": 1}
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [03-04|00:43:36.943] New local node record                    seq=1,741,048,980,370 id=cdddce8ac1ed8cb7 ip=10.1.0.163 udp=57816 tcp=38837
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [03-04|00:43:38.017] New local node record                    seq=1,741,048,976,365 id=78bd73a613c927b7 ip=10.1.0.163 udp=49045 tcp=41737
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X02195F3912BCA1C5B6EA510D10A67F6C6AEBA77702A48591A9C98240931603971C_6132 - INFO [03-04|00:43:38.020] New local node record                    seq=1,741,048,976,366 id=78bd73a613c927b7 ip=10.1.0.163 udp=49045 tcp=41737
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [03-04|00:43:38.395] New local node record                    seq=1,741,048,980,371 id=cdddce8ac1ed8cb7 ip=10.1.0.163 udp=57816 tcp=38837
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X039E80917B3BFD4803FE7803AE300A62C373A7E0BE767C16178980884A56208467_6136 - INFO [03-04|00:43:38.398] New local node record                    seq=1,741,048,980,372 id=cdddce8ac1ed8cb7 ip=10.1.0.163 udp=57816 tcp=38837
[35mDEBUG   [0m src.node.status_node:status_node.py:65 0X021B95D970E2773934F546C0B698AAAF3E7754AB90CEC96EB720B66FAE1120421E_6138 - INFO [03-04|00:43:46.412] New local node record                    seq=1,741,048,986,394 id=3eccf2f897ee958e ip=20.161.78.223 udp=47863 tcp=4232
[31m[1mERROR   [0m src.node.rpc_client:rpc_client.py:32 Request to http://127.0.0.1:32663 usig method wakuext_fetchCommunity timed out after 10 seconds. Node: first_node
[35mDEBUG   [0m tests.conftest:conftest.py:42 Running fixture teardown: save_node_logs_on_fail
[35mDEBUG   [0m tests.conftest:conftest.py:45 Test failed, attempting to rename and move logs to the test_results folder
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130.log to test_results/testleavecommunity_test_leave_community_baseline_0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132.log to test_results/testleavecommunity_test_leave_community_baseline_0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138.log to test_results/testleavecommunity_test_leave_community_baseline_0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135.log to test_results/testleavecommunity_test_leave_community_baseline_0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139.log to test_results/testleavecommunity_test_leave_community_baseline_0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134.log to test_results/testleavecommunity_test_leave_community_baseline_0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137.log to test_results/testleavecommunity_test_leave_community_baseline_0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133.log to test_results/testleavecommunity_test_leave_community_baseline_0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131.log to test_results/testleavecommunity_test_leave_community_baseline_0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file 0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136.log to test_results/testleavecommunity_test_leave_community_baseline_0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136.log
[35mDEBUG   [0m tests.conftest:conftest.py:55 Moved log file first_node.log to test_results/testleavecommunity_test_leave_community_baseline_first_node.log
[35mDEBUG   [0m tests.conftest:conftest.py:62 Running fixture teardown: clear_open_nodes
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: first_node
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x02d815e00131e404d7de053208ed6db77a996403243c52bf8b20922a5e947bbd43_6135
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x02c805d0bc6c60eae2df62a9780b0b46b75301283075057ecdc677a2dc7a3cbfe1_6139
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x02195f3912bca1c5b6ea510d10a67f6c6aeba77702a48591a9c98240931603971c_6132
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x02cbc80d3f2c70de89bc14df08cd90af4d038a1ac46ca994a1c1dbafeff4bd46b2_6130
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x039e80917b3bfd4803fe7803ae300a62c373a7e0be767c16178980884a56208467_6136
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x02e2daf7144be6e5fef22e6ea21f04302a51cba97ebe58c010478d8eac1aee62c6_6134
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x036ddc1c91806eefcfbd8eb1accadc7eff82d79f1fed6e8fccd08f9cf737d02c1f_6131
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x021b95d970e2773934f546c0b698aaaf3e7754ab90cec96eb720b66fae1120421e_6138
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x03084787b0eb1391fd622fda8fee5f9fda3571467ee2c4dbcce9d10e4cb50442ad_6133
[32mINFO    [0m src.node.status_node:status_node.py:73 Stopping node with name: 0x035cd90ef0acdd7ca1173984b56c36a1d9a0119d00f787c3b99bc9705b6d394094_6137